<?php
declare(strict_types=1);
// Some data we get from outside sources is bad or at least mis-defined
// Use lower case for all of these, and then compare to a lower cased version
const HAS_NO_VOLUME = array("zookeys", "studia hibernica", "analecta hibernica", "british art studies", "der spiegel",
                            "international astronomical union circular", "yale french studies", "capjournal",
                            "cap journal", "phytokeys", "starinar", "balcanica", "american museum novitates",
                            "european journal of taxonomy");  // Some journals have issues only, no volume numbers
// oceanic linguistics special publications has the problem that issues will not show up within temlpates
const HAS_NO_ISSUE = array("special papers in palaeontology", "oceanic linguistics special publications");  // Some journals have volumes only, no issue numbers
const PREFER_VOLUMES = array("illinois classical studies"); // When issue=volume, drop issue.  JSTOR calls volumes issues
const PREFER_ISSUES = array("mammalian species", "bulletin of the united states national museum");
const BAD_ACCEPTED_MANUSCRIPT_TITLES = array("oup accepted manuscript", "placeholder for bad pdf file", 
                                             "placeholder", "symbolic placeholder", "[placeholder]", 
                                             "placeholder for arabic language transliteration", "article not found");
const BAD_AUTHORS = array("unknown", "missing", "- -.", "- -", "no authorship indicated", "no authorship", "no author",
                           "no authors", "no author indicated", "no authorship indicated", "dk eyewitness", "united states",
                           "great britain", "indiatoday", "natural history museum bern", "daily sabah", 'el país', 'el pais', 
			   "radio", "rundfunk");
const NON_HUMAN_AUTHORS = array('collaborat', 'reporter', 'journalist', 'correspondent', 'anchor', 'staff', 'foreign',
                                'national', 'endowment', ' for the ', 'humanities', 'committee', 'group',
                                'society', ' of america', 'association', ' at the ', 'board of ', 'communications',
                                'corporation', 'incorporated', 'editorial', 'university', 'dept. of', 'department',
                                'dept of ', 'college', 'center for', 'office of', 'editor', 'institut', 'world bank',
                                'world news', 'national news', 'eyewitness', 'information', 'business', 'bureau',
                                'us census', 'indiatoday', 'natural history', 'museum', '試験所', 'circuit',
                                'external', 'relations', 'nations', 'united', 'radio', 'rundfunk', 'new york');
const BAD_PUBLISHERS = array('london', 'edinburgi', 'edinburgh', 'no publisher', 'no publisher given',
                             'no publisher specified', 'unknown', 'publisher not identified', 'report');

const ARE_WORKS = array('medrxiv'); // Things with dois that should be {{cite document|work=THIS}}

const BAD_DOI_ARRAY = ['10.1126/science' => TRUE, '' => TRUE, '10.1267/science.040579197' => TRUE, '10.0000/Rubbish_bot_failure_test' => TRUE, '10.0000/Rubbish_bot_failure_test2' => TRUE];

const PUBLISHERS_ARE_WORKS = array('the san diego union-tribune', 'forbes', 'salon', 'san jose mercury news', 'san jose mercury-news', 'new york times',
                                   'the new york times', 'daily news online', 'daily news', 'the sun', 'the times',
                                   'the star', 'washington post', 'the washington post', 'the tribune',
                                   'los angeles times', 'la times', 'the la times', 'htmlgiant', 'the los angeles times',
                                   'sandiegouniontribune.com', 'forbes.com', 'salon.com', 'mercurynews.com', 'nytimes.com',
                                   'thedailynewsonline.com', 'thesun.com', 'thetimes.com', 'thestar.com',
                                   'washingtonpost.com', 'thetribune.com', 'latimes.com', 'htmlgiant.com',
                                   'the guardian', 'fox sports', 'mlb.com', 'espn.com', 'forbes media', 'forbes online',
                                   'cbs sports', 'national journal', 'foxnews', 'the hill', 'nationaljournal.com',
                                   'the huffington post', 'the times digital archive', 'belmontstakes.com', 'the times archives',
                                   'new york times.com', 'news shopper', 'birmingham post', 'the independent',
                                   'rediff.com', 'squashplayer.co.uk', 'fixtures live', 'the star online',
                                   'oneindia', 'international business times', 'the hindu', 'daily news and analysis',
                                   'nfl.com', 'foxsports.com', 'the new yorker', 'findlaw.com', 'newsmax',
                                   'washtimes.com', 'washington times', 'findlaw', 'new york times magazine',
                                   'stripes', 'arizona daily star', 'the times of india', 'the times-news', 'san diego union tribune',
                                   'the star (malaysia)', 'utusan malaysia', 'daily news, sri lanka', 'daily news & analysis',
                                   'new york daily news', 'new york daily news', 'daily news (new york)', 
                                   'anchorage daily news', 'palm beach daily news', 'daily news egypt', 'the daily news egypt',
                                   'daily news latino', 'forbes méxico', 'forbes mexico', 'forbes india', 'forbesmiddleeast',
                                   'forbes middle east', 'forbes russia', 'forbes.ru', 'forbes afrique', 'forbes magazine',
                                   'forbes asia', 'forbes israel', 'forbes global 2000', 'forbes china', '[[forbes]] (Russia)',
                                   'forbes việt nam', 'forbes vietnam', 'forbes viet nam', 'forbes contributor blogs',
                                   'the baltimore sun', 'nba.com', 'philippine news agency', 'www.pna.gov.ph',
				   'pia.gov.ph', 'philippine information agency',
                                   // WP:CITALICSRFC and MOS:ITALICWEBCITE  ?????     'abc news', 'nbc news', 'cbs news', 'bbc news'
                                  ); // LOWER CASE!  WWW not there too! 

const WORKS_ARE_PUBLISHERS = array('united states census bureau'); // LOWER CASE!

const DUBIOUS_JOURNALS = array('fda', 'reuters', 'associated press', 'ap', 'ap wire', 'report', 'nist', 'national institute of standards and technology'); // Things we add, but only if publisher and agency are both blank

// Catch 'authors' such as "hearst magazines", "time inc", "nielsen business media, inc"
// Ordered alphabetically.
const PUBLISHER_ENDINGS = ["books", "corporation", 'centre', 'center', 'company', "inc.", "inc", "magazines",
                           'museum', "press", "publishers", "publishing", 'science'];
const BAD_TITLES = array("unknown", "missing", "arxiv e-prints", "arxiv mathematics e-prints", 
                         "ssrn electronic journal", "dissertations available from proquest",
                         "ebscohost login",  "library login", "google groups", "sciencedirect", "cur_title",
                         "wordpress › error", "ssrn temporarily unavailable", "log in - proquest",
                         "shibboleth authentication request", "nookmarkable url intermediate page",
                         "google books", "rte.ie", "loading", "google book",
                         "the article you have been looking for has expired and is not longer available on our system. this is due to newswire licensing terms.",
                         "openid transaction in progress", 'download limit exceeded', 'privacy settings',
                         "untitled-1", "untitled-2", "professional paper", "zbmath",
                         "theses and dissertations available from proquest", "proquest ebook central", "report",
                         "bloomberg - are you a robot?", "page not found",
                         "breaking news, analysis, politics, blogs, news photos, video, tech reviews",
                         "breaking news, analysis, politics, blogs, news photos, video, tech reviews - time.com",
                         "redirect notice", "oxford music online", "trove - archived webpage", "pagina inicia",
                         "404 not found", "404页面", "sign up ", "index of /home", "usa today - today's breaking news, us & world news",
			 "403 unauthorized", "404错误", "internal server error", "error", "404", "error - lexisnexis® publisher");
const IN_PRESS_ALIASES = array("in press", "inpress", "pending", "published", 
                               "published online", "no-no", "n/a", "online ahead of print", 
                               "unpublished", "unknown", "tba", "forthcoming", "in the press", 
                               "na", "submitted", "tbd", "missing");
const NON_JOURNAL_BIBCODES = array('arXiv', 'gr.qc', 'hep.ex', 'hep.lat', 'hep.ph', 'hep.th', 'astro.ph',
                                   'math', 'nucl.ex', 'nucl.th', 'physics', 'quant.ph', 'alg.geom',
                                   'cond.mat', 'cs.', 'econ.', 'eess.', 'nlin.');
const NON_PUBLISHERS = ['books.google', 'google books', 'google news', 'google.co', 'google book',
                        'zenodo', 'archive.org', 'citeseerx.ist.psu.edu', 'archive.fo', 'archive.today',
                        'hdl.handle.net', 'pub med', 'researchgate']; // Google Inc is a valid publisher, however.
const BAD_ZOTERO_TITLES = ['Browse publications', 'Central Authentication Service', 'http://', 'https://',
                                 'ZbMATH - the first resource for mathematics', 'MR: Matches for:',
                                 ' Log In', 'Log In ', 'Sign in', 'Bookmarkable URL intermediate page', 'Shibboleth Authentication Request',
                                 'domain for sale', 'website for sale', 'domain is for sale', 'website is for sale',
                                 'lease this domain', 'domain available', 'metaTags', 'An Error Occurred', 'User Cookie',
                                 'Cookies Disabled', 'page not found', '411 error', 'url not found',
                                 'limit exceeded', 'Error Page', '}}', '{{', 'EU Login', 'bad gateway', 'Captcha',
                                 '.com', '.gov', '.org', 'View PDF', 'Wayback Machine', 'does not exist', 
                                 'Subscribe to read', 'Wiley Online Library', 'pagina is niet gevonden',
                                 'Zoeken in over NA', 'na een 404', '404 error', 'Account Suspended',
                                 'Error 404', 'EZProxy', 'EBSCOhost Login', '404 - Not Found', '404!',
                                 'Temporarily Unavailable', ' has expired', 'not longer available',
                                 'Article expired', 'This is due to newswire licensing terms',
                                 'OpenId transaction in progress', 'Download Limit Exceeded', 'Internet Archive Wayback Machine',
                                 'Url（アドレス）が変わりました', '404エラ', 'お探しのページは見つかりませんでした',
                                 'privacy settings', 'cookie settings', 'WebCite query', 'Ой!',
                                 'Untitled-1', 'Untitled-2', 'Untitled-3', 'Untitled-4', 'Untitled-5',
                                 'Untitled-6', 'Untitled-7', 'Untitled-8', 'Untitled-9', 'Are you a robot',
                                 'Aanmelden of registreren om te bekijken', 'register to view', 'being redirected',
                                 'has been registered', 'Aanmelden bij Facebook', 'Einloggen', 'The Times & the Sunday Times',
                                 'Login • Instagram', 'subscriber to read', 'has now officially closed',
                                 'An Error Has Occured', 'an error has occurred', 'YouTube, a Google company',
                                 'Seite nicht gefunden', 'Página no encontrada', 'الصفحة غير موجودة', '找不到网页',
                                 'страница не найдена', 'Page non trouvée', 'An error occured',
                                 'Compare Payday Loans', 'Find the Best Loan Deal', '..::.. Error', "Pagina inicia",
                                 'Help Center - The Arizona Republic', '404 ERROR', '404 - URL invalid',
                                 "404. That's an error", '404 - Page Not Found', 'Página não existe', 
                                 'This is not the page you requested', 'Page Not Found', '404 - - ',
                                 '404 &#124; ',  'Missing page', '404 - File or directory not found', '错误页面',
                                 '404 Page - ', '404: Page Not Found ', '404: PAGE NOT FOUND', '404 Error',
                                 '404 | ', '页面不存在', 'De pagina is niet gevonden', '404 - ', ' Stranica nije pronađena',
                                 '404 Page', '404. The page', "wasn't found on this server", '404. The URL', 
                                 'ShieldSquare', '404 Not Found', "404页面", "Sign up | LinkedIn", 'The-star.co.kr',
			         'Connecting to the iTunes Store', '500 Internal Server Error', 'DomainMarket.com',
			         'bluehost.com'];

const CANONICAL_PUBLISHER_URLS = array ('elsevier.com', 'springer.com', 'sciencedirect.com', 'tandfonline.com',
                                'taylorandfrancis.com', 'wiley.com', 'sagepub.com', 'sagepublications.com',
                                'scielo.org', 'scielo.br', 'degruyter.com', 'hindawi.com', 'inderscience.com',
                                'cambridge.org', '.oup.com', 'nature.com', 'macmillan.com', 'ieeexplore.ieee.org',
                                'worldscientific.com', 'iospress.com', 'iospress.nl', 'pnas.org', 'journals.ametsoc.org',
                                'pubs.geoscienceworld.org', 'pubs.rsc.org', 'journals.uchicago.edu',
                                'annualreviews.org', 'aip.scitation.org', 'psyche.entclub.org', 'thelancet.com',
                                'amjbot.org', 'gsapubs.org', 'jwildlifedis.org', 'msptm.org', 'nrcresearchpress.',
                                'fundacionmenteclara.org.ar', 'iopscience.iop.org', 'bmj.com/cgi/pmidlookup',
                                'sciencemag.org', 'doi.apa.org', 'psycnet.apa.org', 'journals.upress.ufl.edu',
                                'clinchem.org', 'cell.com', 'aeaweb.org', 'chestpubs.org', 'journal.chestnet.org',
                                'chestjournal.org', 'biomedcentral.com', 'journals.royalsociety.org',
                                'mdpi.com', 'frontiersin.org', 'scholarpedia.org',
                                //  Below are journal search engines
                                '.serialssolutions.com', '.ebscohost.com',
                                //  Below are proxys
                                'proxy.libraries', 'proxy.lib.', '.ezproxy.', '-ezproxy.', '/ezproxy.',
                                //  Below are sites that are simply DOI resolvers, like dx.doi.org
                                'doi.library.ubc.ca');

const PROXY_HOSTS_TO_ALWAYS_DROP = array('proxy.libraries', 'proxy.lib.', '.ezproxy.', '-ezproxy.', '/ezproxy.',
                                  '.serialssolutions.com', 'search.ebscohost.com', 'findarticles.com',
                                  'journals.royalsociety.org', '.idm.oclc.org'); // Drop these if there is a valid DOI

const PROXY_HOSTS_TO_DROP = array('proxy.libraries', 'proxy.lib.', '.ezproxy.', '-ezproxy.', '/ezproxy.',
                                  '.serialssolutions.com', '.ebscohost.com', 'linkinghub.elsevier.com',
                                  'doi.library.ubc.ca', 'ingentaconnect.com/content', 'sciencedirect.com/science?_ob',
                                  'informaworld.com/smpp', '.search.serialssolutions.com', 'doi.apa.org',
                                  'onlinelibrary.wiley.com/resolve/openurl', 'findarticles.com', 'psycnet.apa.org',
                                  'delivery.acm.org'); // Drop these if there is a valid FREE DOI

const WEB_NEWSPAPERS = array('bbc news', 'bbc', 'news.bbc.co.uk', 'bbc sports', 'bbc sport', 'www.bbc.co.uk', 'the economist', 'washington post',
			     'philippine daily inquirer', 'www.inquirer.net', 'manila bulletin', 'mb.com.ph', 'the philippine star', 'www.philstar.com',
			     'the manila times', 'www.manilatimes.net', 'manila standard', 'manilastandard.net', 'sunstar', 'www.sunstar.com.ph',
			     'malaya (newspaper)', 'malaya.com.ph', 'daily tribune (philippines)', 'tribune.net.ph', 'businessworld',
			     'www.bworldonline.com', 'businessmirror', 'businessmirror.com.ph', 'united news', 'www.unitednews.net.ph',
			     'mindanao gold star daily', 'mindanaogoldstardaily.com', 'tempo (newspaper)', 'www.tempo.com.ph',
			     "people's journal", 'journal.com.ph', 'abante', 'www.abante.com.ph', 'balita (newspaper)', 'balita.net.ph',
			     'inquirer bandera', 'bandera.inquirer.net', 'pilipino star ngayon', 'irishtimes.com', 'the irish times',
			     'the seattle times', 'the news tribune', 'the spokesman-review', 'the montana standard', 'the missoulian',
			     'the spokesman-review', 'bozeman daily chronicle', 'the new york times', 'argus leader', 'the washington post',
			     'rapid city journal', 'austin daily herald', 'la crosse tribune', 'chicago tribune',
			     'rochester democrat and chronicle', 'the boston globe', 'the indianapolis news');

const HOSTS_TO_NOT_ADD  = array('this.fails', 'www.ncbi.nlm.nih.gov', 'dx.doi.org', 'doi.org');

const HOSTNAME_MAP  = array('public.ebookcentral.proquest.com' => '[[ProQuest]]',
                            'proquest.com' => '[[ProQuest]]',
                            'search.proquest.com' => '[[ProQuest]]',
                            'cnn.com' => '[[CNN]]',
                            'foxnews.com' => '[[Fox News]]',
                            'msnbc.com' => '[[MSNBC]]',
                            'nbcnews.com' => '[[NBC News]]',
                            'cbsnews.com' => '[[CBS News]]',
                            'cbs.com' => '[[CBS]]',
                            'abc.com' => '[[American Broadcasting Company]]',
                            'nytimes.com' => '[[The New York Times]]',
                            'newyorker.com' => '[[The New Yorker]]',
                            'independent.co.uk' => '[[Independent.co.uk]]',
                            'cnbc.com' => '[[CNBC]]',
                            'theatlantic.com' => '[[The Atlantic]]',
                            'jpl.nasa.gov' => '[[Jet Propulsion Laboratory]]',
                            'latimes.com' => '[[Los Angeles Times]]',
                            'reuters.com' => '[[Reuters]]',
                            'dailynews.com' => '[[Los Angeles Daily News]]',
                            'gsfc.nasa.gov' => '[[Goddard Space Flight Center]]',
                            'newsweek.com' => '[[Newsweek]]',
                            'observer.com' => '[[The New York Observer]]',
                            'pbs.org' => '[[PBS]]',
                            'mediaincanada.com' => '[[Media of Canada]]',
                            'zap2it.com' => '[[Zap2it]]',
                            'fda.gov' => '[[Food and Drug Administration]]',
                            'rte.ie' => '[[RTÉ.ie]]',
                            'rockpapershotgun.com' => '[[Rock Paper Shotgun]]',
                            'gameinformer.com' => '[[Game Informer]]',
                            'lemonde.fr' => '[[Le Monde]]',
                            'pcgamer.com' => '[[PC Gamer]]',
                            'metacritic.com' => '[[Metacritic]]',
                            'redbull.com' => '[[Red Bull]]',
                            'abcnews.com' => '[[ABC News]]',
                            'abcnews.go.com' => '[[ABC News]]',
                            'allmusic.com' => '[[AllMusic]]',
                            'ancestry.com' => '[[Ancestry.com]]',
                            'answers.com' => '[[Answers.com]]',
                            'ap.org' => '[[Associated Press]]',
                            'apnews.com' => '[[Associated Press]]',
                            'avclub.com' => '[[The A.V. Club]]',
                            'baidu.com' => '[[Baidu]]',
                            'sohu.com' => '[[Sohu]]',
                            'bloomberg.com' => '[[Bloomberg News]]',
                            'breitbart.com' => '[[Breitbart News]]',
                            'businessinsider.com' => '[[Business Insider]]',
                            'buzzfeed.com' => '[[BuzzFeed]]',
                            'buzzfeednews.com' => '[[BuzzFeed News]]',
                            'csmonitor.com' => '[[The Christian Science Monitor]]',
                            'rollingstone.com' => '[[Rolling Stone]]',
                            'dailydot.com' => '[[The Daily Dot]]',
                            'dailymail.com' => '[[Daily Mail]]',
                            'dailymail.co.uk' => '[[Daily Mail]]',
                            'deseretnews.com' => '[[Deseret News]]',
                            'dailywire.com' => '[[The Daily Wire]]',
                            'democracynow.org' => '[[Democracy Now!]]',
                            'economist.com' => '[[The Economist]]',
                            'facebook.com' => '[[Facebook]]',
                            'epochtimes.com' => '[[The Epoch Times]]',
                            'examiner.com' => '[[Examiner.com]]',
                            'familysearch.org' => '[[FamilySearch]]',
                            'findagrave.com' => '[[Find a Grave]]',
                            'forbes.com' => '[[Forbes]]',
                            'foxbusiness.com' => '[[Fox Business]]',
                            'hollywoodreporter.com' => '[[The Hollywood Reporter]]',
                            'screenrant.com' => '[[Screen Rant]]',
                            'huffingtonpost.com' => '[[HuffPost]]',
                            'ibtimes.co.in' => '[[International Business Times]]',
                            'ibtimes.com' => '[[International Business Times]]',
                            'imdb.com' => '[[IMDb]]',
                            'mashable.com' => '[[Mashable]]',
                            'mediamatters.org' => '[[Media Matters for America]]',
                            'mirror.co.uk' => '[[Daily Mirror]]',
                            'nationalgeographic.com' => '[[National Geographic Society]]',
                            'nationalreview.com' => '[[National Review]]',
                            'newrepublic.com' => '[[The New Republic]]',
                            'npr.org' => '[[NPR]]',
                            'nydailynews.com' => '[[New York Daily News]]',
                            'politico.com' => '[[Politico]]',
                            'rottentomatoes.com' => '[[Rotten Tomatoes]]',
                            'scientificamerican.com' => '[[Scientific American]]',
                            'thedailybeast.com' => '[[The Daily Beast]]',
                            'theepochtimes.com' => '[[The Epoch Times]]',
                            'theglobeandmail.com' => '[[The Globe and Mail]]',
                            'theguardian.com' => '[[TheGuardian.com]]',
                            'thehindu.com' => '[[The Hindu]]',
                            'theonion.com' => '[[The Onion]]',
                            'theregister.co.uk' => '[[The Register]]',
                            'thetimes.co.uk' => '[[The Times]]',
                            'thesundaytimes.co.uk' => '[[The Sunday Times]]',
                            'thinkprogress.org' => '[[ThinkProgress]]',
                            'timesofindia.com' => '[[The Times of India]]',
                            'timesofindia.indiatimes.com' => '[[The Times of India]]',
                            'usatoday.com' => '[[USA Today]]',
                            'urbandictionary.com' => '[[Urban Dictionary]]',
                            'washingtonpost.com' => '[[The Washington Post]]',
                            'washingtontimes.com' => '[[The Washington Times]]',
                            'msn.com' => '[[MSN]]',
                            'microsoft.com' => '[[Microsoft]]',
                            'youtube.com' => '[[YouTube]]',
                            'zdnet.com' => '[[ZDNet]]',
                            'netflix.com' => '[[Netflix]]',
                            'chicagotribune.com' => '[[Chicago Tribune]]',
                            'bostonglobe.com' => '[[The Boston Globe]]',
                            'bleacherreport.com' => '[[Bleacher Report]]',
                            'timesofisrael.com' => '[[The Times of Israel]]',
                            'jewishweek.timesofisrael.com' => '[[The Jewish Week]]',
                            'miamiherald.com' => '[[Miami Herald]]',
                            'desmoinesregister.com' => '[[The Des Moines Register]]',
                            'thestar.com' => '[[Toronto Star]]',
                            'tennessean.com' => '[[The Tennessean]]',
                            'startribune.com' => '[[Star Tribune]]',
                            'comedy.co.uk' => '[[British Comedy Guide]]',
                            'legacy.com' => '[[Legacy.com]]',
                            'slantmagazine.com' => '[[Slant Magazine]]',
                            'nme.com' => '[[NME]]',
                            'eurokdj.com' => 'Eurodance Encyclopaedia',
                            'videostatic.com' => 'VideoStatic',
                            'discogs.com' => '[[Discogs]]',
                            'musicnotes.com' => 'Musicnotes',
                            'amazon.com' => 'Amazon',
                            'amazon.de' => 'Amazon Germany',
                            'amazon.co.uk' => 'Amazon UK',
                            'tophit.ru' => '[[Tophit]]',
                            'acharts.us' => 'αCharts',
                            'bet.com' => '[[BET]]',
                            'mtv.com' => '[[MTV]]',
                            'ultratop.be' => '[[Ultratop]]',
                            'billboard.com' => '[[Billboard (magazine)|Billboard]]',
                            'officialcharts.com' => '[[Official Charts Company|Official Charts]]',
                            'loudwire.com' => '[[Loudwire]]',
                            'altpress.com' => '[[Alternative Press (magazine)|Alternative Press]]',
                            'noise11.com' => 'noise11.com',
                            'bac-lac.gc.ca' => '[[Library and Archives Canada]]',
                            'itunes.apple.com' => '[[iTunes]]',
                            'cdjapan.co.jp' => 'CDJapan',
                            'rocksmith.ubi.com' => 'Rocksmith+',
                            'setlist.fm' => 'setlist.fm',
                            'digitalspy.co.uk' => '[[Digital Spy]]',
                            'digitalspy.com' => '[[Digital Spy]]',
                            'buzzjack.com' => 'BuzzJack',
                            'open.spotify.com' => '[[Spotify]]',
                            'whosampled.com' => '[[WhoSampled]]',
                            'fuse.tv' => '[[Fuse (TV channel)|Fuse]]',
                            'collider.com' => '[[Collider (website)|Collider]]',
                            'space.com' => '[[Space.com]]',
                            'github.com' => '[[GitHub]]',
                            'strategicmanagementinsight.com' => 'StrategicManagementInsight.com',
                            'edge-online.com'  => 'Edge',
                            'boxlifemagazine.com'  => 'BoxLife',
                            'hroarr.com'  => 'HROARR',
                            'mensfitness.co.uk'  => "Men's Fitness",
                            'riaa.com'  => '[[Recording Industry Association of America]]',
                            'secondhandsongs.com'  => 'SecondHandSongs',
                            'alfred.com'  => 'Alfred Music',
                            'capitalxtra.com'  => 'Capital XTRA',
                            'theboot.com'  => 'The Boot',
                            'ew.com'  => '[[Entertainment Weekly]]',
                            'antena3.com'  => '[[Antena 3 (Spanish TV channel)|Antena 3]]',
                            'complex.com'  => '[[Complex Networks]]',
                            'articles.latimes.com'  => '[[Los Angeles Times]]',
                            'providencephoenix.com'  => 'Providence Phoenix',
                            'queenvault.com'  => 'Queen Vault',
                            'classicbands.com'  => 'ClassicBands.com',
                            'seenews.com'  => 'SeeNews',
                            'mtv.de'  => 'MTV Germany',
                            'eurogamer.net'  => '[[Eurogamer]]',
                            'happygamer.com'  => 'Happy Gamer',
                            'polygon.com'  => '[[Polygon (website)|Polygon]]',
                            'edweek.org'  => '[[Education Week]]',
                            'hotnewhiphop.com'  => 'HNHH',
                            'beatport.com'  => '[[Beatport]]',
                            'pitchfork.com'  => '[[Pitchfork (website)|Pitchfork]]',
                            'sheetmusicnow.com'  => 'Sheet Music Now',
                            'mayoclinic.org'  => '[[Mayo Clinic]]',
                            'elitefts.com'  => 'elitefts',
                            'loc.gov'  => '[[Library of Congress]]',
                            'livescience.com'  => '[[Live Science]]',
                            'insider.com'  => '[[Insider.com]]',
                            'latino.foxnews.com'  => '[[Fox News]]',
                            'dw.com'  => '[[Deutsche Welle]]',
                            'rnz.co.nz'  => '[[Radio New Zealand]]',
                            'pro-football-reference.com'  => '[[Pro-Football-Reference.com]]',
                            'nba.com' => '[[NBA.com]]',
                            'mlb.com' => '[[MLB.com]]',
                            'nfl.com' => '[[NFL.com]]',
                            'showbuzzdaily.com' => '[[Showbuzzdaily.com]]',
                            'ratingsryan.com' => 'Ratings Ryan',
                            'vanityfair.com' => '[[Vanity Fair (magazine)|Vanity Fair]]',
                            'songlines.co.uk' => '[[Songlines (magazine)|Songlines]]',
                            'abc.net.au' => '[[Australian Broadcasting Corporation]]',
                            'espnscrum.com' => '[[ESPNscrum]]',
                            'thestatesman.com' => '[[The Statesman (India)|The Statesman]]',
                            'dailysabah.com' => '[[Daily Sabah]]',
                            'ibm.com' => '[[IBM]]',
                            'ieee.org' => '[[Institute of Electrical and Electronics Engineers]] (IEEE)',
			    'bandera.inquirer.net' => '[[Inquirer Bandera|Bandera]]',
			    'inquirer.net' => '[[Philippine Daily Inquirer]]',
			    'mb.com.ph' => '[[Manila Bulletin]]',
			    'philstar.com/pilipino-star-ngayon' => '[[Pilipino Star Ngayon]]',
			    'philstar.com' => '[[The Philippine STAR]]',
			    'manilatimes.net' => '[[The Manila Times]]',
			    'manilastandard.net' => '[[Manila Standard]]',
			    'sunstar.com.ph' => '[[SunStar]]',
			    'malaya.com.ph' => '[[Malaya (newspaper)|Malaya]]',
			    'tribune.net.ph' => '[[Daily Tribune (Philippines)|Daily Tribune]]',
			    'bworldonline.com' => '[[BusinessWorld]]',
			    'businessmirror.com.ph' => '[[BusinessMirror]]',
			    'unitednews.net.ph' => '[[United News]]',
			    'mindanaogoldstardaily.com' => '[[Mindanao Gold Star Daily]]',
			    'tempo.com.ph' => '[[Tempo (newspaper)|Tempo]]',
			    'journal.com.ph' => "[[People's Journal]]",
			    'abante.com.ph' => '[[Abante]]',
			    'balita.net.ph' => '[[Balita (newspaper)|Balita]]',
			    'pna.gov.ph' => 'Philippine News Agency',
			    'pia.gov.ph' => 'Philippine Information Agency',
			    'irishtimes.com' => '[[The Irish Times]]',
			    'wikinews.org' => '[[Wikinews]]',
			    'royal.uk' => 'The Royal Family',
			    'cinemaexpress.com' => '[[Cinema Express]]',
			    'sify.com' => '[[Sify]]',
                           ); // Be warned, some website host a seperate sunday edition, etc.  Be careful and when in doubt link to hostname

const NO_DATE_WEBSITES = array('wikipedia.org', 'web.archive.org', 'perma-archives.org', 'webarchive.proni.gov.uk', 'perma.cc',
                              'wayback', 'web.archive.bibalex.org', 'web.petabox.bibalex.org', 'webharvest.gov', 'archive.wikiwix.com',
                              'archive.is', 'archive-it.org', 'nationalarchives.gov.uk', 'freezepage.com', 'webcitation.org',
                              'waybackmachine.org', 'siarchives.si.edu', 'gutenberg.org', 'archive.fo', 'archive.today', 'archive.ph',
                              'oireachtas.ie', 'webarchive.nla.gov.au', 'ebooks.adelaide.edu.au', 'archive.md', 'imdb.com',
                              'apps.des.qld.gov.au', 'billboard.com', 'music.apple.com', 'spotify.com', 'fred.stlouisfed.org',
                              'simonsfoundation.org', 'chroniclingamerica.loc.gov', 'github.com');

const ZOTERO_AVOID_REGEX = array("twitter\.",               // This should be {{cite tweet}}
                                 // Zotero seems to be doing better now "youtube\.", "youtu\.be",
                                 "books\.google\.",         // We have special google books code
                                 "google\.com/search",      // Google search results
                                 "jstor\.org/stable/",      // We have special jstor code
                                 "ned\.ipac\.caltech\.edu", // Gives no real title
                                 "pep\-web\.org",           // Does not parse very well at all
                                 "ezproxy", "arkive\.org", "bloomberg\.com/tosv2.html",  // Junk
                                 "worldcat\.org",           // Should use parameters and google instead
                                 "kyobobook\.co\.kr",       // Bookstore that give junk
                                 "facebook\.com",           // login and junk
                                 "leighrayment\.com",       // highjacked
                                 "seapower\-digital\.com",  // highjacked
                                 "scholarlycommons\.pacific\.edu\/euler\-works", // returns journal reference to works, not the actual work
                                 "miar\.ub\.edu\/issn", // ISSN description, not actually the journal
                                 "britishnewspaperarchive\.co\.uk", // Requires registration
                                 "pressreader\.com", // Bad titles
                                 "ebooks\.adelaide\.edu\.au", // Dead
                                 "tnmaps\.tn\.nic\.in", // maps
                                 "lincstothepast\.com",
                                 "washingtonpost\.com", // Fails 100%
                                 "cagematch\.net", // Fails 100%
                                 "www\.cbc\.ca", // Fails 100%
                                 "www\.emporis\.com", // Fails 100%
                                 "usnews\.com", // Fails 100%
                                 "www\.ascap\.com", // Fails 100%
                                 "www\.thefutoncritic\.com", // Fails 100%
                                 "www\.bom\.gov\.au", // Fails 100%
                                 "www\.dailytelegraph\.com\.au", // Fails 100%
                                 "www\.pwinsider\.com", // Fails 100%
                                 "www\.wrecksite\.eu", // Fails 100%
                                 "www\.heraldsun\.com\.au", // Fails 100%
                                 "www\.neighbourhood\.statistics\.gov\.uk", // Fails 100%
                                 "www\.playbill\.com", // Fails 100%
                                 "olympics\.com", // Fails 100%
                                 "www\.legislation\.gov\.uk", // Fails 100%
                                 "stats\.espncricinfo\.com", // Fails 100%
                                 "www\.almasdarnews\.com", // Fails 100%
                                 "www\.encyclopedia\.com", // Fails 100%
                                 "swedishcharts\.com", // Fails 100%
                                 "www\.teamusa\.org", // Fails 100%
                                 "www\.couriermail\.com\.au", // Fails 100%
                                 "www\.faa\.gov", // Fails 100%
                                 "www\.hockeydb\.com", // Fails 100%
                                 "info\.hazu\.hr", // Fails 100%
                                 "australian-charts\.com", // Fails 100%
                                 "startribune\.newspapers\.com", // Fails 100%
                                 "www\.olympic\.org", // Fails 100%
                                 "www\.billboard-japan\.com", // Fails 100%
                                 "www\.censusindia\.gov\.in", // Fails 100%
                                 "censusindia\.gov\.in", // Fails 100%
                                 "charts\.nz", // Fails 100%
                                 "radiomap\.eu", // Fails 100%
                                 "www\.virtualwall\.org", // Fails 100%
				 "steubencourier\.com", // USA Today highjakced
				 "biodiversity\.org\.au", // Zotero gives bad data
				 "findarticles\.com", // Gone
                                );
const NON_JOURNAL_WEBSITES = array('-news.co.uk/', '.ajc.com/', '.al.com/',
	                  '.ap.org/', '.bbm.ca/', '.dw.com/', '.fec.gov/', '.ft.com/',
	                  '.google.com/', '.ign.com/', '.jd.com/', '.mic.com/', '.newsbank.com/',
	                  '.nj.com/', '.pbs.org/', '.qq.com/', '.rt.com/', '.svg.com/', '.time.com/',
	                  '.vk.com/', '.yy.com/', '/ajc.com/', '/al.com/', '/ap.org/', '/bbm.ca/',
	                  '/dw.com/', '/ft.com/', '/jd.com/', '/mic.com/', '/nj.com/', '/qq.com/',
	                  '/rt.com/', '/time.com/', '/vk.com/', '/yy.com/', '112.international/',
	                  '112.ua/', '2009-2017.state.gov/', '247sports.com/', '360.cn/',
	                  '411mania.com/', '4gamer.net/', '90minut.pl/', 'TV.com/', 'aa.com.tr/',
	                  'abc.com/', 'abc.net.au/', 'abcnews.com/', 'abcnews.go.com/', 'about.com/',
	                  'academia.edu/', 'adb.anu.edu.au/', 'adfontesmedia.com/', 'adl.org/',
	                  'adobe.com/', 'adventuregamers.com/', 'afi.com/', 'afp.com/',
	                  'airlinehistory.co.uk/', 'aliexpress.com/', 'aljazeera.com/',
	                  'aljazeera.net/', 'allaccess.com/', 'allafrica.com/', 'allgame.com/',
	                  'allmovie.com/', 'allmusic.com/', 'almasdarnews.com/', 'alternet.org/',
	                  'altpress.com/', 'amazon.ca/', 'amazon.cn/', 'amazon.co.jp/',
	                  'amazon.co.uk/', 'amazon.com.au/', 'amazon.com.br/', 'amazon.com.mx/',
	                  'amazon.com.sg/', 'amazon.com.tr/', 'amazon.com/', 'amazon.de/',
	                  'amazon.es/', 'amazon.fr/', 'amazon.in/', 'amazon.it/', 'amazon.nl/',
	                  'amnesty.org/', 'amr.abime.net/', 'anandtech.com/', 'ancestry.com/',
	                  'animenewsnetwork.com/', 'aninews.in/', 'anphoblacht.com/', 'answers.com/',
	                  'antwerpen-indymedia.be/', 'aparat.com/', 'apnews.com/', 'apple.com/',
	                  'arabnews.com/', 'arcade-museum.com/', 'archive.org/', 'archives.gov/',
	                  'aria.com.au/', 'armeniasputnik.am/', 'army.mil/', 'armyrecognition.com/',
	                  'arstechnica.co.uk/', 'arstechnica.com/', 'articles.latimes.com/',
	                  'ascap.com/', 'askmen.com/', 'askubuntu.com/', 'atomicavenue.com/',
	                  'atptour.com/', 'atpworldtour.com/', 'australian-charts.com/',
	                  'austriancharts.at/', 'autoblog.com/', 'avclub.com/',
	                  'aviation-safety.net/', 'avn.com/', 'axios.com/', 'azcentral.com/',
	                  'baidu.com/', 'ballotpedia.org/', 'baltimoresun.com/', 'banned.video/',
	                  'baseball-almanac.com/', 'baseball-reference.com/', 'baseballamerica.com/',
	                  'basketball-reference.com/', 'bbc.co.uk/', 'bbc.com/', 'bd.fom.ru/',
	                  'behindthevoiceactors.com/', 'behindwoods.com/', 'bellingcat.com/',
	                  'bestgore.com/', 'bfi.org.uk/', 'bharat.republicworld.com/',
	                  'bigmuddyimc.org/', 'bild.de/', 'billboard-japan.com/', 'billboard.com/',
	                  'billingsgazette.com/', 'bing.com/', 'biography.com/',
	                  'bioguide.congress.gov/', 'blabbermouth.net/', 'bleacherreport.com/',
	                  'blogspot.com/', 'bloodhorse.com/', 'bloomberg.com/', 'bluesnews.com/',
	                  'boingboing.net/', 'bollywoodhungama.com/', 'bom.gov.au/',
	                  'bongacams.com/', 'boston.com/', 'bostonglobe.com/', 'boxofficemojo.com/',
	                  'boxrec.com/', 'breitbart.com/', 'britannica.com/',
	                  'british-history.ac.uk/', 'broadwayworld.com/', 'burkespeerage.com/',
	                  'businessinsider.com/', 'businessweek.com/', 'businesswire.com/',
	                  'bustle.com/', 'buzzfeed.com/', 'buzzfeednews.com/', 'c-span.org/',
	                  'cabi.org/', 'cagematch.net/', 'californiaglobe.com/', 'canada.ca/',
	                  'caranddriver.com/', 'catalyst-journal.com/', 'catholic-hierarchy.org/',
	                  'cato.org/', 'cbc.ca/', 'cbr.com/', 'cbs.com/', 'cbslocal.com/',
	                  'cbsnews.com/', 'cbspressexpress.com/', 'cbssports.com/', 'cdc.gov/',
	                  'celebritynetworth.com/', 'census.gov/', 'censusindia.gov.in/',
	                  'cepr.net/', 'cesnur.net/', 'cgtn.com/', 'channelnewsasia.com/',
	                  'channelnewsassia.com/', 'chart-track.co.uk/', 'charts.monitorlatino.com/',
	                  'charts.nz/', 'chaturbate.com/', 'chess.com/', 'chicagotribune.com/',
	                  'chinadaily.com.cn/', 'chinadailyasia.com/', 'chinadailyhk.com/',
	                  'chron.com/', 'cia.gov/', 'cinemos.com/', 'clerk.house.gov/',
	                  'cleveland.com/', 'cliffsnotes.com/', 'climatefeedback.org/', 'cmt.com/',
	                  'cnbc.com/', 'cnet.com/', 'cnn.com/', 'cnsnews.com/', 'codastory.com/',
	                  'coflein.gov.uk/', 'coindesk.com/', 'collider.com/', 'combinedfleet.com/',
	                  'comicbook.com/', 'commonsensemedia.org/', 'company-histories.com/',
	                  'complex.com/', 'comptiq.com/', 'congress.gov/', 'conservativereview.com/',
	                  'consortiumnews.com/', 'cornell.edu/', 'cosmopolitan.com/',
	                  'council.rollingstone.com/', 'counterpunch.org/', 'couriermail.com.au/',
	                  'courtlistener.com/', 'cracked.com/', 'cricketarchive.com/',
	                  'crockford.org.uk/', 'crunchbase.com/', 'csdn.net/', 'csmonitor.com/',
	                  'ctvnews.ca/', 'dailycaller.com/', 'dailycallernewsfoundation.org/',
	                  'dailydot.com/', 'dailykos.com/', 'dailym.ai/', 'dailymail.co.uk/',
	                  'dailymail.com.au/', 'dailymail.com/', 'dailynews.com/', 'dailysabah.com/',
	                  'dailystar.co.uk/', 'dailytelegraph.com.au/', 'dailytelegraph.com/',
	                  'dailywire.com/', 'dallasnews.com/', 'data.census.gov/',
	                  'data.worldbank.org/', 'davidemaggio.it/', 'dawn.com/', 'deadline.com/',
	                  'deadlinehollywooddaily.com/', 'debretts.com/', 'deccanchronicle.com/',
	                  'deccanherald.com/', 'defense-blog.com/', 'defense.gov/',
	                  'democracynow.org/', 'dengekionline.com/', 'denofgeek.com/',
	                  'denverpost.com/', 'deseretnews.com/', 'desmoinesregister.com/',
	                  'digit.in/', 'digitallibrary.un.org/', 'digitallydownloaded.net/',
	                  'digitalspy.co.uk/', 'digitalspy.com/', 'discogs.com/', 'dnaindia.com/',
	                  'docs.google.com/', 'dotesports.com/', 'dreamteamfc.com/',
	                  'drive.google.com/', 'dutchcharts.nl/', 'dw.com/', 'easyallies.com/',
	                  'ebay.com/', 'ec.europa.eu/', 'economist.com/', 'edition.cnn.com/',
	                  'egmnow.com/', 'electronicintifada.net/', 'elitedaily.com/',
	                  'eliteprospects.com/', 'elspa.com/', 'emmys.com/', 'emporis.com/',
	                  'encyclopedia.com/', 'engadget.com/', 'englishfootballleaguetables.co.uk/',
	                  'entrepreneur.com/', 'eonline.com/', 'epa.gov/', 'epochtimes.com/',
	                  'equibase.com/', 'espn.co.uk/', 'espn.com/', 'espn.go.com/',
	                  'espncricinfo.com/', 'eur-lex.europa.eu/', 'eurogamer.net/',
	                  'euronews.com/', 'europarl.europa.eu/', 'ew.com/', 'examiner.com/',
	                  'express.co.uk/', 'f4wonline.com/', 'faa.gov/', 'facebook.com/',
	                  'factcheck.org/', 'fair.org/', 'familysearch.org/', 'famitsu.com/',
	                  'famousbirthdays.com/', 'fandom.com/', 'fas.org/', 'fccinfo.com/',
	                  'fda.gov/', 'federalregister.gov/', 'fightful.com/', 'filmaffinity.com/',
	                  'filmibeat.com/', 'finance.yahoo.com/', 'financialexpress.com/',
	                  'findagrave.com/', 'findarticles.com/', 'findmypast.co.uk/',
	                  'firstpost.com/', 'fivethirtyeight.com/', 'fjc.gov/', 'fleetphoto.ru/',
	                  'flickr.com/', 'flightglobal.com/', 'folkhalsomyndigheten.se/',
	                  'football-italia.net/', 'forbes.com/', 'foreignpolicy.com/',
	                  'fortune.com/', 'forward.com/', 'foxbusiness.com/', 'foxnews.com/',
	                  'foxsports.com.au/', 'foxsports.com/', 'france24.com/', 'freep.com/',
	                  'frontpagemag.com/', 'frontpagemagazine.com/', 'fundinguniverse.com/',
	                  'funimation.com/', 'fws.gov/', 'g1.globo.com/', 'galegroup.com/',
	                  'gallica.bnf.fr/', 'gamasutra.com/', 'gamedeveloper.com/',
	                  'gameinformer.com/', 'gamekult.com/', 'gamer.nl/', 'gamerankings.com/',
	                  'gamerevolution.com/', 'gamesindustry.biz/', 'gamespot.com/',
	                  'gamesradar.com/', 'gamestar.de/', 'gamestudies.org/',
	                  'gameswirtschaft.de/', 'gamezone.com/', 'gamingbolt.com/',
	                  'gaonchart.co.kr/', 'gawker.com/', 'gematsu.com/', 'geni.com/',
	                  'genius.com/', 'github.com/', 'gizmodo.com/', 'glitchwave.com/',
	                  'globalissues.org/', 'globalnews.ca/', 'globalresearch.ca/',
	                  'globalresearch.org/', 'globalsecurity.org/', 'globaltimes.cn/',
	                  'gmanetwork.com/', 'goal.com/', 'goo.gl/', 'goodreads.com/',
	                  'google.com.hk/', 'google.com/', 'gov.uk/', 'govinfo.gov/', 'govtrack.us/',
	                  'gpo.gov/', 'grammy.com/', 'grubstreet.com/', 'gsfc.nasa.gov/',
	                  'guardian.co.uk/', 'guinnessworldrecords.com/', 'gulfnews.com/',
	                  'haaretz.co.il/', 'haaretz.com/', 'hansard.millbanksystems.com/',
	                  'hardcoregamer.com/', 'hardcoregaming101.net/', 'heatst.com/',
	                  'heavy.com/', 'heraldscotland.com/', 'heraldsun.com.au/',
	                  'heroesneverdie.com/', 'hindustantimes.com/', 'hiphopdx.com/',
	                  'hispantv.com/', 'hispantv.ir/', 'history.com/', 'hitparade.ch/',
	                  'hk.appledaily.com/', 'hobbyconsolas.com/', 'hockey-reference.com/',
	                  'hockeydb.com/', 'hollywoodreporter.com/', 'hopenothate.org.uk/',
	                  'hotnewhiphop.com/', 'house.gov/', 'hrw.org/', 'huanqiu.com/',
	                  'huffingtonpost.ca/', 'huffingtonpost.co.uk/', 'huffingtonpost.com.au/',
	                  'huffingtonpost.com.mx/', 'huffingtonpost.com/', 'huffingtonpost.de/',
	                  'huffingtonpost.es/', 'huffingtonpost.fr/', 'huffingtonpost.gr/',
	                  'huffingtonpost.in/', 'huffingtonpost.it/', 'huffingtonpost.jp/',
	                  'huffingtonpost.kr/', 'huffpost.com/', 'huffpostbrasil.com/',
	                  'huffpostmaghreb.com/', 'huguenot-museum-germany.com/', 'humanevents.com/',
	                  'hurriyet.com.tr/', 'hurriyetdailynews.com/', 'iaaf.org/',
	                  'ibtimes.co.in/', 'ibtimes.co.uk/', 'ibtimes.com.au/', 'ibtimes.com.cn/',
	                  'ibtimes.com/', 'ibtimes.sg/', 'idlebrain.com/', 'idolator.com/',
	                  'ifcncodeofprinciples.poynter.org/', 'ign.com/', 'ijr.com/', 'imax.com/',
	                  'imc-africa.mayfirst.org/', 'imdb.com/', 'imf.org/', 'independent.co.uk/',
	                  'independent.ie/', 'indiaglitz.com/', 'indianexpress.com/',
	                  'indiatimes.com/', 'indiatoday.in/', 'indiatoday.intoday.in/',
	                  'indiewire.com/', 'indybay.org/', 'indymedia.ie/', 'indymedia.nl/',
	                  'indymedia.no/', 'indymedia.org.uk/', 'indymedia.org/', 'indymedia.us/',
	                  'indymediapr.org/', 'info.hazu.hr/', 'infowars.com/', 'infowars.net/',
	                  'infowars.tv/', 'inquirer.com/', 'inquisitr.com/', 'instagram.com/',
	                  'int.soccerway.com/', 'interfax.com.ua/', 'invenglobal.com/',
	                  'investopedia.com/', 'investors.com/', 'iol.co.za/', 'ipscuba.net/',
	                  'ipsnews.net/', 'ipsnoticias.net/', 'ipsos.com/', 'iranicaonline.org/',
	                  'irishtimes.com/', 'issuu.com/', 'isuresults.com/', 'itftennis.com/',
	                  'itmedia.co.jp/', 'itunes.apple.com/', 'jacobinmag.com/', 'janes.com/',
	                  'japantimes.co.jp/', 'jeuxvideo.com/', 'jewishvirtuallibrary.org/',
	                  'jezebel.com/', 'jihadwatch.org/', 'jmdb.ne.jp/', 'journalism.org/',
	                  'jpl.nasa.gov/', 'jpost.com/', 'jsonline.com/', 'justadventure.com/',
	                  'justice.gov/', 'kansascity.com/', 'khronos.org/', 'kicker.de/',
	                  'kickstarter.com/', 'knowyourmeme.com/', 'kommersant.com/',
	                  'kommersant.ru/', 'kommersant.uk/', 'kotaku.com/', 'lambiek.net/',
	                  'last.fm/', 'latimes.com/', 'law.com/', 'law.justia.com/', 'legacy.com/',
	                  'legacy.usatf.org/', 'legislation.gov.uk/', 'lemonde.fr/', 'lenta.ru/',
	                  'lescharts.com/', 'lexicarbrasil.com.br/', 'licensing.fcc.gov/',
	                  'lifesite.net/', 'lifesitenews.com/', 'lifewire.com/', 'linkedin.com/',
	                  'livejournal.com/', 'liveleak.com/', 'livemint.com/', 'loc.gov/',
	                  'loudwire.com/', 'lulu.com/', 'm-create.com/',
	                  'mailonline.pressreader.com/', 'mailonsunday.co.uk/',
	                  'mailpictures.newsprints.co.uk/', 'mailplus.co.uk/', 'majornelson.com/',
	                  'maps.google.com/', 'marca.com/', 'marist.edu/', 'marketwatch.com/',
	                  'marquiswhoswho.com/', 'mashable.com/', 'match.uefa.com/',
	                  'mathoverflow.net/', 'maxpreps.com/', 'mcvuk.com/',
	                  'mediabiasfactcheck.com/', 'mediaincanada.com/', 'mediaite.com/',
	                  'mediamatters.org/', 'medium.com/', 'memri.org/', 'memritv.org/',
	                  'mercurynews.com/', 'meretmarine.com/', 'merriam-webster.com/',
	                  'metabomb.net/', 'metacritic.com/', 'metal-archives.com/',
	                  'metal-experience.com/', 'metalsucks.net/', 'metmuseum.org/',
	                  'metro.co.uk/', 'metro.news/', 'mfa.gov.tr/', 'mg.co.za/',
	                  'miamiherald.com/', 'michiganimc.org/', 'microsoft.com/', 'mid.ru/',
	                  'midiaindependente.org/', 'milb.com/', 'mintpressnews.com/',
	                  'mirror.co.uk/', 'mlb.com/', 'mlb.mlb.com/', 'mlbtraderumors.com/',
	                  'mlg.com/', 'mlive.com/', 'mlssoccer.com/', 'mmafighting.com/',
	                  'mmajunkie.com/', 'monde-diplomatique.fr/', 'mondediplo.com/',
	                  'mondialisation.ca/', 'mondoweiss.net/', 'monitor.com/',
	                  'morningstaronline.co.uk/', 'motherjones.com/', 'motorsportmemorial.org/',
	                  'mrc.org/', 'mrctv.org/', 'msdn.microsoft.com/', 'msn.com/', 'msnbc.com/',
	                  'mtv.com/', 'museeprotestant.org/', 'music.apple.com/', 'mylife.com/',
	                  'mynintendonews.com/', 'nasa.gov/', 'natalie.mu/',
	                  'national-football-teams.com/', 'nationalenquirer.com/',
	                  'nationalgeographic.com/', 'nationalreview.com/', 'naturalnews.com/',
	                  'naver.com/', 'nba.com/', 'nbcnews.com/', 'ncaa.com/', 'ncdc.noaa.gov/',
	                  'nces.ed.gov/', 'ndtv.com/', 'neighbourhood.statistics.gov.uk/',
	                  'netflix.com/', 'newindianexpress.com/', 'newrepublic.com/',
	                  'news.abs-cbn.com/', 'news.cn/', 'news.com.au/', 'news.google.com/',
	                  'news.sky.com/', 'news.yahoo.com/', 'news18.com/', 'news24.com/',
	                  'newsbank.com/', 'newsblaze.com.au/', 'newsblaze.com/', 'newsbreak.com/',
	                  'newsbusters.org/', 'newscientist.com/', 'newsday.com/',
	                  'newsinfo.inquirer.net/', 'newsmax.com/', 'newsmaxtv.com/',
	                  'newsoftheworld.co.uk/', 'newsoftheworld.com/', 'newspapers.com/',
	                  'newstarget.com/', 'newswars.com/', 'newsweek.com/', 'newyorker.com/',
	                  'nfl.com/', 'nhl.com/', 'nies.go.jp/', 'nintendoforcemagazine.com/',
	                  'nintendolife.com/', 'nintendoworldreport.com/', 'njpw.co.jp/',
	                  'nla.gov.au/', 'nme.com/', 'nndb.com/', 'nobelprize.org/', 'nola.com/',
	                  'northjersey.com/', 'nowrunning.com/', 'npr.org/', 'nps.gov/', 'nrk.no/',
	                  'nrl.com/', 'nst.com.my/', 'nydailynews.com/', 'nymag.com/', 'nypost.com/',
	                  'nytimes.com/', 'nzherald.co.nz/', 'nztop40.co.nz/', 'oann.com/',
	                  'observer.com/', 'occupydemocrats.com/', 'ocregister.com/', 'office.com/',
	                  'officialcharts.com/', 'officialgazette.gov.ph/', 'offiziellecharts.de/',
	                  'okezone.com/', 'olympedia.org/', 'olympic.org/', 'olympics.com/',
	                  'onlineworldofwrestling.com/', 'open.spotify.com/', 'opensecrets.org/',
	                  'opindia.com/', 'opindia.in/', 'order-order.com/', 'oregonlive.com/',
	                  'oricon.co.jp/', 'orlandosentinel.com/', 'ourcampaigns.com/',
	                  'oursportscentral.com/', 'outlookindia.com/', 'ozfootball.net/',
	                  'page3.com/', 'pagesix.com/', 'panampost.com/', 'panda.tv/',
	                  'papers.ssrn.com/', 'paperspast.natlib.govt.nz/', 'parliament.uk/',
	                  'parlinfo.aph.gov.au/', 'patch.com/', 'patheos.com/', 'paultan.org/',
	                  'pbs.org/', 'pcgamer.com/', 'pcgamesn.com/', 'people-press.org/',
	                  'people.com/', 'pep.ph/', 'pewforum.org/', 'pewglobal.org/',
	                  'pewhispanic.org/', 'pewinternet.org/', 'pewresearch.org/',
	                  'pewsocialtrends.org/', 'philly.com/', 'phillyimc.org/', 'philstar.com/',
	                  'phoronix.com/', 'pinknews.co.uk/', 'pitchfork.com/', 'pjv101.net/',
	                  'planet4589.org/', 'plato.stanford.edu/', 'playbill.com/', 'playboy.com/',
	                  'playstation.com/', 'pocketgamer.com/', 'politicalgraveyard.com/',
	                  'politico.com/', 'politifact.com/', 'poll.qu.edu/', 'polygon.com/',
	                  'popmatters.com/', 'portal.dnb.de/', 'post-gazette.com/',
	                  'pressreader.com/', 'presstv.co.uk/', 'presstv.com/', 'presstv.ir/',
	                  'presstv.tv/', 'pride.com/', 'primagames.com/', 'prnewswire.co.uk/',
	                  'prnewswire.com/', 'pro-football-reference.com/', 'profightdb.com/',
	                  'profootballtalk.nbcsports.com/', 'projectveritas.com/', 'propublica.org/',
	                  'prowrestling.net/', 'prowrestlinghistory.com/', 'pu.nl/',
	                  'publishersweekly.com/', 'purexbox.com/', 'pushsquare.com/',
	                  'pwinsider.com/', 'pwtorch.com/', 'quackwatch.org/', 'quadrant.org.au/',
	                  'quillette.com/', 'quora.com/', 'qz.com/', 'racing-reference.info/',
	                  'radiomap.eu/', 'radiotimes.com/', 'rap-up.com/', 'rapgenius.com/',
	                  'rappler.com/', 'rateyourmusic.com/', 'rawstory.com/',
	                  'realclearinvestigations.com/', 'realclearpolitics.com/', 'reason.com/',
	                  'redbull.com/', 'reddit.com/', 'rediff.com/', 'redstate.com/',
	                  'refinery29.com/', 'reliefweb.int/', 'religionnews.com/',
	                  'republicworld.com/', 'reunion.com/', 'reuters.com/', 'rfa.org/',
	                  'rferl.org/', 'rfi.fr/', 'ria.ru/', 'riaa.com/', 'rian.com.ua/',
	                  'rian.ru/', 'riftherald.com/', 'rockpapershotgun.com/', 'rogueimc.org/',
	                  'rollcall.com/', 'rollingstone.com/', 'rottentomatoes.com/', 'royal.uk/',
	                  'routesonline.com/', 'rpgamer.com/', 'rpgfan.com/', 'rpgsite.net/',
	                  'rsssf.com/', 'rt.com/', 'rugbyleagueproject.org/', 'russianships.info/',
	                  'russiatoday.com/', 'sagehens.com/', 'saints.org.uk/', 'salon.com/',
	                  'sandiegouniontribune.com/', 'sbnation.com/', 'sbs.com.au/',
	                  'sciencebasedmedicine.org/', 'scienceblogs.com/', 'sciencedaily.com/',
	                  'scientificamerican.com/', 'scmp.com/', 'scotsman.com/', 'scotusblog.com/',
	                  'screenrant.com/', 'scribd.com/', 'scroll.in/', 'searchlightmagazine.com/',
	                  'seattletimes.com/', 'sec.gov/', 'senate.gov/', 'serverfault.com/',
	                  'sfgate.com/', 'shacknews.com/', 'sherdog.com/', 'shopify.com/',
	                  'showbuzzdaily.com/', 'shows.ctv.ca/', 'si.com/', 'sify.com/',
	                  'siliconera.com/', 'sina.com.cn/', 'sites.google.com/', 'sixthtone.com/',
	                  'skepdic.com/', 'skwawkbox.org/', 'skyrocket.de/', 'skyscraperpage.com/',
	                  'skysports.com/', 'slam.canoe.ca/', 'slate.com/', 'slate.fr/',
	                  'smh.com.au/', 'snl.no/', 'snopes.com/', 'socialblade.com/',
	                  'softpedia.com/', 'sohu.com/', 'solarsystem.nasa.gov/', 'sonemic.com/',
	                  'soundcloud.com/', 'sourcewatch.org/', 'space.com/', 'spacecom.mil/',
	                  'sparknotes.com/', 'spc.noaa.gov/', 'spectator.co.uk/', 'spectator.us/',
	                  'spiegel.de/', 'spin.com/', 'spirit-of-metal.com/', 'splcenter.org/',
	                  'sportingnews.com/', 'sports-reference.com/', 'sports.espn.go.com/',
	                  'sports.yahoo.com/', 'sportsbusinessjournal.com/', 'sportsnet.ca/',
	                  'sputnik-abkhazia.ru/', 'sputnik-georgia.com/', 'sputnik-georgia.ru/',
	                  'sputnik-ossetia.com/', 'sputnik-ossetia.ru/', 'sputnik-tj.com/',
	                  'sputnik.az/', 'sputnik.by/', 'sputnik.kg/', 'sputnik.kz/', 'sputnik.md/',
	                  'sputniknews-uz.com/', 'sputniknews.cn/', 'sputniknews.com/',
	                  'sputniknews.gr/', 'sputniknews.lt/', 'sputniknews.ru/',
	                  'sputniknewslv.com/', 'ssb.no/', 'ssd.jpl.nasa.gov/', 'stackexchange.com/',
	                  'stackoverflow.com/', 'standard.co.uk/', 'star-ch.jp/',
	                  'starsunfolded.com/', 'startribune.com/', 'startribune.newspapers.com/',
	                  'state.gov/', 'statista.com/', 'stats.espncricinfo.com/', 'stats.gov.cn/',
	                  'statscrew.com/', 'stltoday.com/', 'straitstimes.com/', 'stuff.co.nz/',
	                  'sun-sentinel.com/', 'sunnation.co.uk/', 'suntimes.com/', 'superuser.com/',
	                  'supremecourt.gov/', 'surgeongeneral.gov/', 'sverigetopplistan.se/',
	                  'swarajyamag.com/', 'swedishcharts.com/', 'syriahr.com/', 'takimag.com/',
	                  'tampabay.com/', 'taobao.com/', 'tass.com/', 'tass.ru/', 'tcm.com/',
	                  'teamusa.org/', 'techcrunch.com/', 'techpowerup.com/', 'techradar.com/',
	                  'telegeography.com/', 'telegraph.co.uk/', 'telegraphindia.com/',
	                  'telesurenglish.net/', 'telesurtv.net/', 'tennessean.com/',
	                  'texastribune.org/', 'the-magicbox.com/', 'the-sun.com/', 'theage.com.au/',
	                  'theamericanconservative.com/', 'theathletic.com/', 'theatlantic.com/',
	                  'theaustralian.com.au/', 'thebalance.com/', 'theblaze.com/',
	                  'thecanary.co/', 'thecipherbrief.com/', 'theconversation.com/',
	                  'thecrimson.com/', 'thecut.com/', 'thedailybeast.com/', 'thediplomat.com/',
	                  'theepochtimes.com/', 'thefederalist.com/', 'theflyingcourier.com/',
	                  'thefreelibrary.com/', 'thefutoncritic.com/', 'thegamesmachine.it/',
	                  'thegatewaypundit.com/', 'theglobeandmail.com/', 'thegrayzone.com/',
	                  'thegreenpapers.com/', 'theguardian.co.uk/', 'theguardian.com/',
	                  'thehill.com/', 'thehindu.com/', 'thehindubusinessline.com/',
	                  'thehistoryofwwe.com/', 'theintercept.com/', 'thejakartapost.com/',
	                  'thejc.com/', 'themarysue.com/', 'thenation.com/', 'thenational.ae/',
	                  'theneedledrop.com/', 'thenewamerican.com/', 'thenews.com.pk/',
	                  'thenewsminute.com/', 'thenextweb.com/', 'theonion.com/',
	                  'thepointsguy.com/', 'thepostmillennial.com/', 'theregister.co.uk/',
	                  'thescottishsun.co.uk/', 'thespruce.com/', 'thestar.com.my/',
	                  'thestar.com/', 'thestar.ie/', 'thesun.co.uk/', 'thesun.ie/',
	                  'thesun.mobi/', 'thesundaytimes.co.uk/', 'thetimes.co.uk/',
	                  'thetruthaboutguns.com/', 'theverge.com/', 'theweek.com/', 'thewrap.com/',
	                  'thinkprogress.org/', 'thisisinsider.com/', 'thisismoney.co.uk/',
	                  'thoughtco.com/', 'tianya.cn/', 'time.com/', 'timeshighereducation.com/',
	                  'timesofindia.com/', 'timesofindia.indiatimes.com/', 'timesofisrael.com/',
	                  'timesonline.co.uk/', 'tmall.com/', 'tmz.com/', 'tnimc.org/',
	                  'todayonline.com/', 'topuniversities.com/', 'toronto.com/',
	                  'torrentfreak.com/', 'toucharcade.com/', 'townhall.com/',
	                  'translate.google.com/', 'travelmail.co.uk/', 'tribune.com.pk/',
	                  'tribuneindia.com/', 'tripsavvy.com/', 'trove.nla.gov.au/',
	                  'trtworld.com/', 'tsn.ca/', 'tuoitre.vn/', 'turner.com/', 'tvguide.com/',
	                  'tvguidemagazine.com/', 'tvline.com/', 'tvtonight.com.au/',
	                  'tvtropes.org/', 'twitch.tv/', 'twitter.com/', 'uboat.net/', 'ucimc.org/',
	                  'uefa.com/', 'ukwhoswho.com/', 'ultratop.be/', 'un.org/', 'unicode.org/',
	                  'unoosa.org/', 'unz.com/', 'unz.org/', 'upcomer.com/', 'upi.com/',
	                  'upworthy.com/', 'urbandictionary.com/', 'usagym.org/', 'usatoday.com/',
	                  'uscourts.gov/', 'uselectionatlas.org/', 'usmagazine.com/', 'usnews.com/',
	                  'vanityfair.com/', 'variety.com/', 'varzesh3.com/', 'vatican.va/',
	                  'vdare.com/', 'venezuelanalysis.com/', 'venturebeat.com/', 'verywell.com/',
	                  'verywellfamily.com/', 'verywellhealth.com/', 'verywellmind.com/',
	                  'veteranstoday.com/', 'vg247.com/', 'vgchartz.com/', 'vh1.com/',
	                  'vice.com/', 'vicetv.com/', 'videogamer.com/', 'videogameschronicle.com/',
	                  'vimeo.com/', 'virtualwall.org/', 'visionofbritain.org.uk/',
	                  'vnexpress.net/', 'voanews.com/', 'vogue.com/', 'voiceofrussia.com/',
	                  'volcano.si.edu/', 'voltairenet.org/', 'votesmart.org/', 'vox.com/',
	                  'vulture.com/', 'wargamer.com/', 'washingtonexaminer.com/',
	                  'washingtonpost.com/', 'washingtontimes.com/', 'watch.impress.co.jp/',
	                  'weather2travel.com/', 'web.archive.org/', 'websites.sportstg.com/',
	                  'weeklystandard.com/', 'wegotthiscovered.com/', 'weibo.com/',
	                  'westernjournal.com/', 'whatculture.com/', 'whc.unesco.org/',
	                  'whitehouse.gov/', 'whitehousehistory.org/', 'who.int/', 'whosampled.com/',
	                  'whoswhoinamerica.com/', 'wikia.com/', 'wikia.org/', 'wikicities.com/',
	                  'wikidata.org/', 'wikileaks.org/', 'wikinews.org/', 'wikipedia.org/',
	                  'wired.co.uk/', 'wired.com/', 'wnd.com/', 'wordpress.com/',
	                  'worldfootball.net/', 'worldnetdaily.com/', 'worldometers.info/',
	                  'wrecksite.eu/', 'wrestling-titles.com/', 'wsj.com/', 'wsws.org/',
	                  'wtatennis.com/', 'wwe.com/', 'www.insider.com/', 'www.rte.ie/',
	                  'www12.statcan.gc.ca/', 'www2.census.gov/', 'xbiz.com/', 'xinhuanet.com/',
	                  'xxlmag.com/', 'xzqh.org/', 'yahoo.co.jp/', 'yahoo.com/', 'yandex.ru/',
	                  'ynszxc.net/', 'yourentertainmentnow.com/', 'youtube.com/',
	                  'yuzhnoye.com/', 'zap2it.com/', 'zdnet.com/', 'zeenews.india.com/',
	                  'zerohedge.com/', 'zhanqi.tv/', 'zoominfo.com/', 'hdr.undp.org/', '.nist.gov/',
	                  'ngdc.noaa.gov/', 'babel.hathitrust.org/', 'pcgames.de/', 'eurogamer.it/',
	                  'conceptcarz.com/', '.tvp.info/', 'archdioceseofbombay.org/');
                     // Just a list of ones that are obvious.  Add ones that time-out as we find them
                     // bbm.ca is short enough that we add /bbm.ca/ and .bbm.ca/ since we don't want to grab too many sites

const NON_JOURNAL_DOIS = array('10.5531/db.vz.0001'); // lowercase exact matches
const NON_JOURNALS = array('Amphibian Species of the World', 'an Online Reference', 'An Online Reference',
			   'Boston Almanac and Guide1', 'Includes:reports from Commissioners, Inspectors and Others'); // Case-sensitive sub-string
const ARE_MAGAZINES = array('the new yorker', 'the new republic', 'new republic', 'expedition magazine', 'wired', 'wired uk',
                           'computer gaming world', 'edge (magazine)', 'game informer', 'pc gamer uk',
                           'wired (magazine)', 'time', 'life', 'time (magazine)', 'life (magazine)', 'billboard',
                           'billboard (magazine)', 'rolling stone', 'mcv/develop', 'vanity fair',
                           'nintendo power', 'playthings', 'entertainment weekly', 'official xbox magazine',
                           'electronic gaming monthly', 'official u.s. playstation magazine',
                           'playstation: the official magazine', 'play and silicon mag', 'games radar', 'hyper',
                           'famitsu', 'gamepro', 'yachting world', 'kalki',
                           ); // lowercase axact matches
const ARE_MANY_THINGS = array('pc gamer', 'gamestar', 'rock paper shotgun', 'mcv', 'rock, paper, shotgun', 'edge',
                              'ballotpedia', 'npr', 'ballotpedia.org', 'npr.org', 'nih.gov', 'nih', 'eurogamer.it',
			      'conceptcarz', 'the royal family',
                              'national institutes of health', 'national institutes of health (nih)'); // lowercase axact matches.  These are things that are both websites and newspapers
const ARE_NEWSPAPERS = array('the economist', 'la times', 'toronto sun', 'washington post', 'the washington post',
			     'philippine daily inquirer', 'the irish times', 'wikinews', 'wikinews.org'); // lowercase axact matches
const NO_PUBLISHER_NEEDED = array('los angeles times', 'new york times magazine', 'the new york times',
                                   'new york times', 'huffington post', 'the daily telegraph', 'forbes.com',
                                   'forbes magazine'); // lowercase axact matches

const ENCYCLOPEDIA_WEB = array('plato.stanford.edu', 'britannica.com');

const GOOD_10_1093_DOIS = array( // March 2019 list
          'abbs', 'abm', 'abt', 'acn', 'adaptation', 'advances', 'ae', 'aepp', 'aesa', 'af', 'afraf',
          'ageing', 'ahr', 'ajae', 'ajcl', 'ajcn', 'ajcp', 'aje', 'ajh', 'ajhp', 'ajj', 'ajlh',
          'alcalc', 'aler', 'alh', 'alrr', 'amt', 'analysis', 'annhyg', 'annonc', 'antitrust', 'aob',
          'aobpla', 'applij', 'arbitration', 'aristotelian', 'aristoteliansupp', 'asj', 'asjopenforum', 'astrogeo', 'auk', 'beheco',
          'bfg', 'bib', 'bioinformatics', 'biolinnean', 'biolreprod', 'biomedgerontology', 'biomet', 'biomethods', 'bioscience', 'biostatistics',
          'bjaesthetics', 'bjc', 'bjps', 'bjsw', 'bmb', 'botlinnean', 'brain', 'btcint', 'bybil', 'camqtly',
          'carcin', 'cardiovascres', 'cb', 'ccc', 'cdj', 'cdn', 'ce', 'cercor', 'cesifo', 'chemse',
          'chinesejil', 'chromsci', 'cid', 'cjcl', 'cje', 'cjip', 'cjres', 'ckj', 'clp', 'cmlj',
          'comjnl', 'comnet', 'condor', 'conphys', 'cpe', 'criticalvalues', 'crj', 'crohnscolitis360', 'cs', 'ct',
          'cww', 'cybersecurity', 'cz', 'database', 'dh', 'dnaresearch', 'dote', 'dsh', 'ecco-jcc', 'ecco-jccs',
          'economicpolicy', 'ectj', 'edrv', 'ee', 'eep', 'ehjcimaging', 'ehjcr', 'ehjcvp', 'ehjqcco', 'ehr',
          'eic', 'ej', 'ejcts', 'ejil', 'ejo', 'eltj', 'em', 'emph', 'endo', 'english',
          'envhis', 'envihistrevi', 'epirev', 'erae', 'ereh', 'eshremonographs', 'esr', 'eurheartj', 'eurheartjsupp', 'europace',
          'eurpub', 'fampra', 'femsec', 'femsle', 'femspd', 'femsre', 'femsyr', 'fh', 'fmls', 'foreconshist',
          'forestry', 'forestscience', 'fpa', 'fqs', 'fs', 'fsb', 'gastro', 'gbe', 'geronj', 'gerontologist',
          'gh', 'gigascience', 'gji', 'globalsummitry', 'glycob', 'gsmnras', 'hcr', 'heapol', 'heapro', 'her',
          'hgs', 'hmg', 'hrlr', 'hropen', 'hsw', 'humrep', 'humupd', 'hwj', 'ia', 'ib',
          'ibdjournal', 'icb', 'icc', 'icesjms', 'icon', 'icsidreview', 'icvts', 'idpl', 'ije', 'ijl',
          'ijlct', 'ijlit', 'ijnp', 'ijpor', 'ijrl', 'ijtj', 'ilarjournal', 'ilj', 'imaiai', 'imajna',
          'imaman', 'imamat', 'imamci', 'imammb', 'imatrm', 'imrn', 'imrp', 'imrs', 'innovateage', 'insilicoplants',
          'integrablesystems', 'inthealth', 'intimm', 'intqhc', 'iob', 'ips', 'irap', 'isd', 'isle', 'isp',
          'isq', 'isr', 'itnow', 'iwc', 'jaar', 'jac', 'jae', 'jah', 'jamia', 'jamiaopen',
          'japr', 'jas', 'jat', 'jb', 'jbcr', 'jbi', 'jcag', 'jcb', 'jcem', 'jcle',
          'jcmc', 'jcr', 'jcs', 'jcsl', 'jdh', 'jdsde', 'jeclap', 'jee', 'jeea', 'jel',
          'jes', 'jfec', 'jfr', 'jge', 'jhc', 'jhered', 'jhmas', 'jhps', 'jhrp', 'jhs',
          'jicj', 'jid', 'jids', 'jiel', 'jigpal', 'jinsectscience', 'jiplp', 'jipm', 'jis', 'jjco',
          'jla', 'jlb', 'jleo', 'jmammal', 'jmcb', 'jme', 'jmicro', 'jmp', 'jmt', 'jn',
          'jnci', 'jncics', 'jncimono', 'jnen', 'joc', 'joeg', 'jof', 'jogss', 'jole', 'jos',
          'jpart', 'jpe', 'jpepsy', 'jpids', 'jpo', 'jpubhealth', 'jrls', 'jrr', 'jrs', 'jscr',
          'jsh', 'jss', 'jssam', 'jtm', 'jts', 'jue', 'jvc', 'jwelb', 'jxb', 'labmed',
          'lawfam', 'leobaeck', 'library', 'litimag', 'litthe', 'logcom', 'lpr', 'lril', 'maghis', 'mbe',
          'medlaw', 'melus', 'mend', 'migration', 'milmed', 'mind', 'mj', 'ml', 'mmy', 'mnras',
          'mnrasl', 'molehr', 'mollus', 'monist', 'mq', 'mspecies', 'mtp', 'mts', 'musictherapy', 'mutage',
          'nar', 'nass', 'nc', 'ndt', 'neuro-oncology', 'neurosurgery', 'njaf', 'nop', 'nq', 'nsr',
          'ntr', 'nutritionreviews', 'oaj', 'occmed', 'oep', 'ofid', 'ohr', 'ojlr', 'ojls', 'omcr',
          'ons', 'oq', 'oxrep', 'pa', 'painmedicine', 'pasj', 'past', 'pch', 'pcm', 'pcp',
          'peds', 'petrology', 'phe', 'philmat', 'plankt', 'policing', 'poq', 'ppar', 'ppmg', 'ppr',
          'pq', 'proceedingslinnean', 'ps', 'psychsocgerontology', 'ptep', 'ptj', 'ptp', 'ptps', 'publius', 'qje',
          'qjmam', 'qjmath', 'qjmed', 'raps', 'rb', 'rcfs', 'reep', 'res', 'restud', 'rev',
          'rfs', 'rheumap', 'rheumatology', 'rof', 'rpc', 'rpd', 'rsq', 'scan', 'schizophreniabulletin', 'screen',
          'ser', 'sf', 'shm', 'sjaf', 'sleep', 'slr', 'socpro', 'socrel', 'sp', 'spp',
          'sq', 'ssjj', 'sw', 'swr', 'swra', 'synbio', 'sysbio', 'tandt', 'tas', 'tbm',
          'tcbh', 'teamat', 'toxsci', 'transactionslinnean', 'transactionslinneanbot', 'transactionslinneanzoo', 'treephys', 'tropej', 'trstmh', 'tse',
          'ulr', 've', 'wber', 'wbro', 'whq', 'wjaf', 'workar', 'yel', 'yielaw', 'ywcct',
          'ywes', 'zoolinnean');


// List of things to not print links to, since they occur all the time
const AVOIDED_LINKS = array('', 'Digital_object_identifier', 'JSTOR', 'Website', 'International_Standard_Book_Number',
                            'Library_of_Congress_Control_Number', 'Handle_System', 'PubMed_Central', 'PubMed',
                            'PubMed_Identifier', 'Bibcode', 'International_Standard_Serial_Number', 'bioRxiv',
                            'CiteSeerX', 'Zentralblatt_MATH', 'Jahrbuch_über_die_Fortschritte_der_Mathematik',
                            'Mathematical_Reviews', 'Office_of_Scientific_and_Technical_Information',
                            'Request_for_Comments', 'Social_Science_Research_Network', 'Zentralblatt_MATH',
                            'Open_Library', 'ArXiv', 'OCLC', 'Cf.', 'Doi_(identifier)', 'PMC_(identifier)',
                            'PMID_(identifier)', 'ArXiv_(identifier)', 'Bibcode_(identifier)', 
                            'S2CID_(identifier)', 'ISBN_(identifier)', 'ISSN_(identifier)', 'OCLC_(identifier)',
                            'OSTI_(identifier)');


// Lower case, and periods converted to spaces
const JOURNAL_IS_BOOK_SERIES = array('methods of molecular biology' , 'methods mol biol',
                                     'methods of molecular biology (clifton, n j )',
                                     'methods in molecular biology',
                                     'methods in molecular biology (clifton, n j )',
                                     'advances in pharmacology (san diego, calif )',
                                     'advances in pharmacology', 'inorganic syntheses',
                                     'advances in enzymology and related areas of molecular biology',
                                     'studies in bilingualism', 'antibiotics and chemotherapy',
                                     'oceanic linguistics special publications',
                                     'progress in brain research');
