<?php

declare(strict_types=1);

const COMMON_MISTAKES = [ // Common mistakes that aren't picked up by the levenshtein approach.  And obvious ones to reduce levenshtein dependence
    'ASIN' => 'asin',
    'EISSN' => 'eissn',
    'HDL' => 'hdl',
    'ISBN13' => 'isbn',
    'isbn13' => 'isbn',
    'ISMN' => 'ismn',
    'ISSN' => 'issn',
    'JFM' => 'jfm',
    'JSTOR' => 'jstor',
    'LCCN' => 'lccn',
    'MR' => 'mr',
    'OCLC' => 'oclc',
    'OL' => 'ol',
    'OSTI' => 'osti',
    'PMC' => 'pmc',
    'pmcid' => 'pmc',
    'PMID' => 'pmid',
    'RFC' => 'rfc',
    'S2CID' => 's2cid',
    'SBN' => 'sbn',
    'SSRN' => 'ssrn',
    'ZBL' => 'zbl',
    'embargo' => 'pmc-embargo-date',
    'albumlink' => 'title-link',
    'titlelink' => 'title-link',
    'artist' => 'others',
    'bioRxiv' => 'biorxiv',
    'coauthor' => 'coauthors',
    'co-author' => 'coauthors',
    'co-authors' => 'coauthors',
    'dio' => 'doi',
    'director' => 'others',
    'editors' => 'editor',
    'display_authors' => 'display-authors',
    'displayauthors' => 'display-authors',
    'displayeditors' => 'display-editors',
    'doi_brokendate' => 'doi-broken-date',
    'doi_broken_date' => 'doi-broken-date',
    'doi_inactivedate'=> 'doi-broken-date',
    'doi-inactive-date' => 'doi-broken-date',
    'doi-broken' => 'doi-broken-date',
    'subjectlink' => 'subject-link',
    'transcripturl' => 'transcript-url',
    'ed' => 'editor',
    'ed2' => 'editor2',
    'ed3' => 'editor3',
    'ed4' => 'editor4',
    'ed5' => 'editor5',
    'ed6' => 'editor6',
    'ed7' => 'editor7',
    'ed8' => 'editor8',
    'ed9' => 'editor9',
    'ed10' => 'editor10',
    'editorlink' => 'editor-link',
    'editorlink1' => 'editor1-link',
    'editorlink2' => 'editor2-link',
    'editorlink3' => 'editor3-link',
    'editorlink4' => 'editor4-link',
    'editorlink5' => 'editor5-link',
    'editorlink6' => 'editor6-link',
    'editorlink7' => 'editor7-link',
    'editorlink8' => 'editor8-link',
    'editorlink9' => 'editor9-link',
    'editorlink10' => 'editor10-link',
    'editorlink11' => 'editor11-link',
    'editorlink12' => 'editor12-link',
    'editorlink13' => 'editor13-link',
    'editorlink14' => 'editor14-link',
    'editorlink15' => 'editor15-link',
    'editorlink16' => 'editor16-link',
    'editorlink17' => 'editor17-link',
    'editorlink18' => 'editor18-link',
    'editorlink19' => 'editor19-link',
    'editorlink20' => 'editor20-link',
    'editorlink21' => 'editor21-link',
    'editorlink22' => 'editor22-link',
    'editorlink23' => 'editor23-link',
    'editorlink24' => 'editor24-link',
    'editorlink25' => 'editor25-link',
    'editorlink26' => 'editor26-link',
    'editorlink27' => 'editor27-link',
    'editorlink28' => 'editor28-link',
    'editorlink29' => 'editor29-link',
    'editorlink30' => 'editor30-link',
    'editor1link' => 'editor1-link',
    'editor2link' => 'editor2-link',
    'editor3link' => 'editor3-link',
    'editor4link' => 'editor4-link',
    'editor5link' => 'editor5-link',
    'editor6link' => 'editor6-link',
    'editor7link' => 'editor7-link',
    'editor8link' => 'editor8-link',
    'editor9link' => 'editor9-link',
    'editor10link' => 'editor10-link',
    'editor11link' => 'editor11-link',
    'editor12link' => 'editor12-link',
    'editor13link' => 'editor13-link',
    'editor14link' => 'editor14-link',
    'editor15link' => 'editor15-link',
    'editor16link' => 'editor16-link',
    'editor17link' => 'editor17-link',
    'editor18link' => 'editor18-link',
    'editor19link' => 'editor19-link',
    'editor20link' => 'editor20-link',
    'editor21link' => 'editor21-link',
    'editor22link' => 'editor22-link',
    'editor23link' => 'editor23-link',
    'editor24link' => 'editor24-link',
    'editor25link' => 'editor25-link',
    'editor26link' => 'editor26-link',
    'editor27link' => 'editor27-link',
    'editor28link' => 'editor28-link',
    'editor29link' => 'editor29-link',
    'editor30link' => 'editor30-link',
    'editorn' => 'editor2',
    'editorn-link' => 'editor2-link',
    'editorn-last' => 'editor2-last',
    'editorn-first' => 'editor2-first',
    'interviewerlink' => 'interviewer-link',
    'interviewermask' => 'interviewer-mask',
    'firstn' => 'first2',
    'nocat' => 'no-tracking',
    'no-cat' => 'no-tracking',
    'notracking' => 'no-tracking',
    'ISBN' => 'isbn',
    'ibsn' => 'isbn',
    'ibsn2' => 'isbn',
    'lastn' => 'last2',
    'local' => 'location',
    'part' => 'issue',
    'no' => 'issue',
    'No' => 'issue',
    'No.' => 'issue',
    'notestitle' => 'chapter',
    'nurl' => 'url',
    'origmonth' => 'month',
    'p' => 'page',
    'p.' => 'page',
    'pmpmid' => 'pmid',
    'pp' => 'pages',
    'pp.' => 'pages',
    'publisherid' => 'id',
    'titleyear' => 'orig-year',
    'translators' => 'translator',
    'URL' => 'url',
    'vol' => 'volume',
    'Vol' => 'volume',
    'Vol.' => 'volume',
    'ARXIV' => 'arxiv',
    'cointerviewers' => 'others',
    'trans_chapter' => 'trans-chapter',
    'trans_title' => 'trans-title',
    'DOI' => 'doi',
    'publication' => 'work',
    'publicationplace' => 'publication-place',
    'publicationdate' => 'publication-date',
    'chapterurl' => 'chapter-url',
    'booktitle' => 'book-title',
    'conferenceurl' => 'conference-url',
    'timecaption' => 'time-caption',
    'contributionurl' => 'contribution-url',
    'laydate' => 'lay-date',
    'laysource' => 'lay-source',
    'layurl' => 'lay-url',
    'sectionurl' => 'section-url',
    'seriesno' => 'series-no',
    'nopp' => 'no-pp',
    'authorurl' => 'author-link',
    'titre' => 'title',
    'consulté' => 'access-date',
    'autho' => 'author',
    'accesdate' => 'access-date',
    'autore' => 'author',
    'autore2' => 'author2',
    'autore3' => 'author3',
    'autore4' => 'author4',
    'accessed' => 'access-date',
    'titolo' => 'title',
    'rivista' => 'magazine',
    'année' => 'year',
    'autor' => 'author',
    'autor1' => 'author1',
    'autor2' => 'author2',
    'autor3' => 'author3',
    'autor4' => 'author4',
    'titlu' => 'title',
    'accesso' => 'access-date',
    'agencia' => 'agency',
    'anno' => 'year',
    'annooriginale' => 'orig-year',
    'año' => 'year',
    'añooriginal' => 'orig-year',
    'cita' => 'quote',
    'citazione' => 'quote',
    'città' => 'location',
    'coautores' => 'coauthors',
    'coautori' => 'coauthors',
    'cognome' => 'last',
    'cognome1' => 'last1',
    'cognome2' => 'last2',
    'cognome3' => 'last3',
    'dataaccesso' => 'access-date',
    'dataarchivio' => 'archive-date',
    'editori' => 'editors',
    'editorial' => 'publisher',
    'edizione' => 'edition',
    'enlaceautor' => 'author-link',
    'enlaceautor1' => 'author-link1',
    'enlaceautor2' => 'author-link2',
    'enlaceautor3' => 'author-link3',
    'enlaceautor4' => 'author-link4',
    'enlaceroto' => 'url-status',
    'fecha' => 'date',
    'fechaacceso' => 'access-date',
    'fechaarchivo' => 'archive-date',
    'formato' => 'format',
    'giornale' => 'journal',
    'idioma' => 'language',
    'lingua' => 'language',
    'nombre' => 'first',
    'primero' => 'first',
    'nombre1' => 'first1',
    'primero1' => 'first1',
    'nombre2' => 'first2',
    'primero2' => 'first2',
    'nombre3' => 'first3',
    'primero3' => 'first3',
    'nome' => 'first',
    'nome1' => 'first1',
    'nome2' => 'first2',
    'nome3' => 'first3',
    'numero' => 'issue',
    'numéro' => 'issue',
    'obra' => 'work',
    'página' => 'page',
    'páginas' => 'pages',
    'pagina' => 'page',
    'pagine' => 'pages',
    'periodico' => 'magazine',
    'pubblicazione' => 'magazine',
    'publicación' => 'journal',
    'puntofinale' => 'postscript',
    'seria' => 'series',
    'serie' => 'series',
    'sitioweb' => 'website',
    'sito' => 'website',
    'site' => 'website',
    'tipo' => 'type',
    'título' => 'title',
    'ubicación' => 'location',
    'urlarchivio' => 'archive-url',
    'urlarchivo' => 'archive-url',
    'urlmorto' => 'url-status',
    'wkautore' => 'author-link',
    'wkautore1' => 'author-link1',
    'wkautore2' => 'author-link2',
    'wkautore3' => 'author-link3',
    'coauther' => 'coauthors',
    'city' => 'location',
    'link' => 'url',
    'home' => 'work',
    'homelanguage' => 'language',
    'episodelink' => 'episode-link',
    'mailinglist' => 'mailing-list',
    'mapurl' => 'map-url',
    'serieslink' => 'series-link',
    'başlık' => 'title',
    'språk' => 'language',
    'datum' => 'date',
    'arkivdatum' => 'archive-date',
    'arkivurl' => 'archive-url',
    'hämtdatum' => 'access-date',
    'tidning' => 'newspaper',
    'författare' => 'author',
    'rubrik' => 'title',
    'utgivare' => 'publisher',
    'tidskrift' => 'journal',
    'efternamn' => 'last',
    'år' => 'year',
    'jator' => 'jstor',
    'jastor' => 'jstor',
    'date-access' => 'access-date',
    'retrieved' => 'access-date',
    'titre ouvrage' => 'work',
    'ville' => 'location',
    'titre chapitre' => 'chapter',
    'format électronique' => 'format',
    'příjmení' => 'last1',
    'jméno' => 'first1',
    'příjmení1' => 'last1',
    'jméno1' => 'first1',
    'příjmení2' => 'last2',
    'jméno2' => 'first2',
    'příjmení3' => 'last3',
    'jméno3' => 'first3',
    'příjmení4' => 'last4',
    'jméno4' => 'first4',
    'vydavatel' => 'publisher',
    'místo' => 'location',
    'rok' => 'year',
    'strany' => 'page',
    'sarlavha' => 'title',
    'ism' => 'first',
    'familiya' => 'last',
    'sana' => 'date',
    'nashriyot' => 'publisher',
    'vebsayt' => 'website',
    'yil' => 'year',
    'muharrir' => 'editor',
    'muharrir-havola' => 'editor-link',
    'oy' => 'month',
    'sahifalar' => 'pages',
    'til' => 'language',
    'kirish sanasi' => 'access-date',
    'joylashuv' => 'location',
    'iqtibos' => 'quote',
    'langue' => 'language',
    'authors1' => 'author1',
    'editors1' => 'editor1',
    'editor1mask' => 'editor-mask1',
    'editormask1' => 'editor-mask1',
    'subjectlink1' => 'subject-link1',
    'weebsite' => 'website',
    'websites' => 'website',
    'url lưu trữ' => 'archive-url',
    'tựa đề' => 'title',
    'access date' => 'access-date',
    'tite' => 'title',
    'firs' => 'first',
    'urlstatus' => 'url-status',
    'acccessdate' => 'access-date',
    'access_date' => 'access-date',
    'pubisher' => 'publisher',
    'tiêu đề' => 'title',
    'ngày' => 'date',
    'ngày truy cập' => 'access-date',
    'nhà xuất bản' => 'publisher',
    'nơi xuất bản' => 'location',
    'websitre' => 'website',
    'ইউআরএল-অবস্থা' => 'url-status',
    'date of access' => 'access-date',
    'date of publication' => 'publication-date',
    'first name' => 'first',
    'last name' => 'last',
    'url of archive' => 'archive-url',
    'archive date' => 'archive-date',
    'issue date' => 'issue-date',
    'publication date' => 'publication-date',
    'archived ate' => 'archive-date',
    'websute' => 'website',
    'datr' => 'date',
    'trans-ttle' => 'trans-title',
    'date visited' => 'access-date',
    'ημερομηνία' => 'date',
    'видавець' => 'publisher',
    'дата' => 'date',
    'дата-доступу' => 'access-date',
    'мертвий-url' => 'deadurl',
    'назва' => 'author',
    'datum přístupu' => 'access-date',
    'jazyk' => 'language',
    'titul' => 'title',
    'datearchived' => 'achive-date',
    'urlarchive' => 'archive-url',
    'websitw' => 'website',
    'periodikum' => 'periodical',
    'chatper' => 'chapter',
    'url status' => 'url-status',
    'afirst1' => 'first1',
    'tác giả 1' => 'author1',
    'năm' => 'year',
    'tác giả' => 'author',
    'u rl-status' => 'url-status',
    'dat e' => 'date',
    'citação' => 'quote',
    'acessodat' => 'access-date',
    'issues' => 'issue',
    'issu' => 'issue',
    'نویسنده' => 'author',
    'original-date' => 'orig-date',
    'ссылка' => 'url',
    'jstor-accesss' => 'jstor-access',
    'irl' => 'url',
    'urn' => 'url',
    'websire' => 'website',
    'origdate' => 'orig-date',
    'datăaccesare' => 'access-date',
    'limbă' => 'language',
    'locaiton' => 'location',
    'ietf-kielikoodi' => 'language',
    'acceessdate' => 'access-date',
    'in url' => 'url',
    'auther' => 'author',
    'acess-date' => 'access-date',
    'datee' => 'date',
    'chatper-url' => 'chapter-url',
    'dare' => 'date',
    'langauge' => 'language',
    'archive url' => 'archive-url',
    'archive- url' => 'archive-url',
    'autho-link' => 'author-link',
    'dateaccess' => 'access-date',
    'dopi' => 'doi',
    'lats1' => 'last1',
    'lsnguage' => 'language',
    'lst' => 'last',
    'publishing' => 'publisher',
    'trans-tile' => 'trans-title',
    'vauthros' => 'vauthors',
    'webiste' => 'website',
    'websiet' => 'website',
    'retrieve' => 'access-date',
    'retrieval' => 'access-date',
    'acces-date' => 'access-date',
    'acccess-date' => 'access-date',
    'archive-rurl' => 'archive-url',
    'ccess-date' => 'access-date',
    'titles' => 'title',
    'author-maske' => 'author-mask',
    'accessd-ate' => 'access-date',
    'publishel' => 'publisher',
    'publiher' => 'publisher',
    '저자' => 'author',
    'text' => 'quote',
    'nume' => 'author',
    'prenume' => 'first',
    'other' => 'others',
    'wesbite' => 'website',
    'webite' => 'website',
    'aothers' => 'others',
    'deate' => 'date',
    'locationm' => 'location',
    'publsiher' => 'publisher',
    'pulisher' => 'publisher',
    'date accessed' => 'access-date',
    'jahrea' => 'year',
    'lasct' => 'last',
    'мовою' => 'language',
    'розміщення' => 'date',
    'url-архіву' => 'archive-url',
    'дата-архіву' => 'archive-date',
    'editoraу' => 'editor',
    'websitу' => 'website',
    'last 1у' => 'last1',
    'jounralу' => 'journal',
    'archvie-url' => 'archive-url',
    'ad1' => 'author1',
    'arşivtarihi' => 'archive-date',
    'dergi' => 'journal',
    'erişimtarihi' => 'access-date',
    'ölüurl' => 'deadurl',
    'sayfalar' => 'pages',
    'sayı' => 'number',
    'soyadı1' => 'last1',
    'yıl' => 'year',
    'arşivurl' => 'archive-url',
    'tittle' => 'title',
    'titley' => 'title',
    'first-' => 'first',
    'achive-url' => 'archive-url',
    'archive_date' => 'archive-date',
    'archive_url' => 'archive-url',
    'place of publication' => 'publication-place',
    'year of publication' => 'publication-date',
    'access' => 'access-date',
    'linguage' => 'language',
    'extrait' => 'quote',
    'arhcive-date' => 'archive-date',
    'webste' => 'website',
    'pagina\'s' => 'pages',
    '제목' => 'title',
    '확인날짜' => 'access-date',
    'brisé le' => ' access-date',
    'worl' => ' work',
    'shapter' => 'chapter',
    'editor-firs1t' => 'editor-first',
    'pubilsher' => 'publisher',
    'archive-.url' => 'archive-url',
    'access-dat' => 'access-date',
    'access-daite' => 'access-date',
    'datearchivo' => 'archive-date',
    'surnames' => 'surname',
    'τίτλος' => 'title',
    'languege' => 'language',
    'publisherg' => 'publisher',
    'name' => 'author',
    'name1' => 'author1',
    'name2' => 'author2',
    'name3' => 'author3',
    'access- date' => 'access-date',
    'translit-title' => 'trans-title',
    'websitte' => 'website',
    '4rl' => 'url',
    'ur l' => 'url',
    'pubslisher' => 'publisher',
    'laguage' => 'language',
    'puplisher' => 'publisher',
    'access-as te' => 'access-date',
    'frst' => 'first',
    'archive-url a' => 'archive-url',
    'link to author' => 'author-link',
    'access-daet' => 'access-date',
    'werk' => 'work',
    'abruf' => 'access-date',
    'archive0date' => 'access-date',
    'eebsite' => 'website',
    'author-lin' => 'author-link',
    'arhiivimisurl' => 'archive-url',
    'acessodata' => 'access-date',
    'ournal' => 'journal',
    'frist' => 'first',
    'locatio' => 'location',
    'ort' => 'location',
    'pealkiri' => 'title',
    'vaadatud' => 'access-date',
    'url-olek' => 'url-status',
    'پیوند بایگانی' => 'archive-url',
    'نام' => 'first',
    'نام خانوادگی' => 'last',
    'вебсайт' => 'website',
    'siteweb' => 'website',
    'datefile' => 'date',
    'data archive' => 'archive-date',
    'editore' => 'editor',
    'urlfile' => 'archive-url',
    'fiorst4' => 'first4',
    'alst4' => 'last4',
    'las t' => 'last',
    'firsst' => 'first',
    'langugage' => 'language',
    'firast1' => 'first1',
    'volumeas' => 'volume',
    'publishr' => 'publisher',
    'webstie' => 'website',
    'titule' => 'title',
    'titulo' => 'title',
    'accessyear' => 'access-date',
    'publishers' => 'publisher',
    'trans-titl' => 'trans-title',
    'last 1' => 'last1',
    'nimike' => 'title',
    'accessddate' => 'access-date',
    'tarih' => 'date',
    'yayıncı' => 'publisher',
    'çalışma' => 'title',
    'first name2' => 'first2',
    'last name2' => 'last2',
    'first name1' => 'first1',
    'last name1' => 'last1',
    'aurl' => 'url',
    'год' => 'year',
    'doi-accesss' => 'doi-access',
    'arhiivimisaeg' => 'archive-date',
    'edition-' => 'edition',
    'url-archive' => 'archive-url',
    'lasts' => 'last',
    'access-datee' => 'access-date',
    'url-staus' => 'url-status',
    'translated-title' => 'trans-title',
    ';ast1' => 'last1',
    'accerssdate' => 'access-date',
    'authored' => 'authors',
    'fist1' => 'first1',
    'locato in' => 'location',
    'piublisher' => 'publisher',
    'publihser' => 'publisher',
    'url-access-date' => 'access-date',
    'datepublished' => 'date',
    'автор-посилання' => 'author-link',
    'автор-посилання1' => 'author-link1',
    'автор-посилання2' => 'author-link2',
    'автор-посилання3' => 'author-link3',
    'автор-посилання4' => 'author-link4',
    'журнал' => 'magazine',
    'ім\'я' => 'first',
    'ім\'я1' => 'first1',
    'ім\'я2' => 'first2',
    'ім\'я3' => 'first3',
    'ім\'я4' => 'first4',
    'прізвище' => 'last',
    'прізвище1' => 'last1',
    'прізвище2' => 'last2',
    'прізвище3' => 'last3',
    'прізвище4' => 'last4',
    'рік' => 'year',
    'сторінки' => 'pages',
    'websiter' => 'website',
    'çalıwebsite' => 'website',
    'deaadurl' => 'deadurl',
    'аrchiveurl' => 'archive-url',
    'cognom' => 'last',
    'consulta' => 'access-date',
    'nom' => 'first',
    'publicació' => 'work',
    'pàgines' => 'pages',
    'تاريخ أرشيف' => 'archive-date',
    'مسار' => 'url',
    'مسار أرشيف' => 'archive-url',
    'path' => 'url',
    'titl' => 'title',
    'archive path' => 'archive-url',
    'wesite' => 'website',
    'en ligne le acc' =>  'date',
    'pg' => 'page',
    'publusher' => 'publisher',
    'accesss-datet' => 'access-date',
    'acessdate' => 'access-date',
    'archive-seekurl' => 'archive-url',
    'accecssdate' => 'access-date',
    'accesadate' => 'access-date',
    'access-daye' => 'access-date',
    'accessdtae' => 'access-date',
    'datte' => 'date',
    'editorfirst' => 'editor-first',
    'publiser' => 'publisher',
    'published-date' => 'publication-date',
    'translòator-first' => 'translator-first',
    'urkl' => 'url',
    'urstatus' => 'url-status',
    'works' => 'work',
    'archive-dat' => 'archive-date',
    'زبان' => 'language',
    'archive-link' => 'archive-url',
    'deadlink' => 'deadurl',
    'access  date' => 'access-date',
    'access–date' => 'access-date',
    'accesss-date' => 'access-date',
    'archive-  date' => 'archive-date',
    'aurhor' => 'author',
    'aythor' => 'author',
    'coautors' => 'coauthors',
    'ebsite' => 'website',
    'firt' => 'first',
    'firt1' => 'first1',
    'journa' => 'journal',
    'languag' => 'language',
    'lastr' => 'last',
    'magazibe' => 'magazine',
    'magazins' => 'magazine',
    'mpid' => 'pmid',
    'publisjjer' => 'publisher',
    'tilte' => 'title',
    'url- status' => 'url-status',
    'wia' => 'via',
    'apellidos' => 'last',
    'apellidos1' => 'last1',
    'apellidos2' => 'last2',
    'apellidos3' => 'last3',
    'apellidos4' => 'last4',
    'apellidos5' => 'last5',
    'apellidos6' => 'last6',
    'apellidos7' => 'last7',
    'apellidos8' => 'last8',
    'apellidos9' => 'last9',
    'apellidos10' => 'last10',
    'apellido' => 'last',
    'apellido1' => 'last1',
    'apellido2' => 'last2',
    'apellido3' => 'last3',
    'apellido4' => 'last4',
    'apellido5' => 'last5',
    'apellido6' => 'last6',
    'apellido7' => 'last7',
    'apellido8' => 'last8',
    'apellido9' => 'last9',
    'apellido10' => 'last10',
    'check date' => 'access-date',
    'día' => 'date',
    'éditeur' => 'editor',
    'by' => 'author',
    'first author' => 'author1',
    'pristupdatum' => 'access-date',
    'title>' => 'title',
    'access day' => 'access-date',
    'access-sate' => 'access-date',
    'accetss-date' => 'access-date',
    'archiverul' => 'archive-url',
    'archives-url' => 'archive-url',
    'chapter title' => 'chapter',
    'dats' => 'date',
    'dlanguage' => 'language',
    'edition-date' => 'date',
    'firts1' => 'first1',
    'jounral' => 'journal',
    'last[[' => 'last',
    'lornguage' => 'language',
    'origina-year' => 'orig-year',
    'purl' => 'url',
    'titel' => 'title',
    'títle' => 'title',
    'url;' => 'url',
    'w ebsite' => 'website',
    'weork' => 'work',
    'accessdaste' => 'accessdate',
    'accessed on' => 'access-date',
    'archivedat' => 'archivedate',
    'archivedte' => 'archivedate',
    'dated' => 'date',
    'itle' => 'title',
    'juornal' => 'journal',
    'puisher' => 'publisher',
    'saccessdate' => 'accessdate',
    'trancslate-title' => 'trans-article',
    'web site' => 'website',
    'accessedate' => 'access-date',
    'archive-urk' => 'archive-url',
    'arhive-date' => 'archive-date',
    'author_first' => 'author-first',
    'author_last' => 'author-last',
    'colume' => 'volume',
    'date-accessed' => 'access-date',
    'dste' => 'date',
    'editor_first' => 'editor-first',
    'editor_last' => 'editor-last',
    'farst1' => 'first1',
    'gtitle' => 'title',
    'nespaper' => 'newspaper',
    'newspapers' => 'newspaper',
    'oublisher' => 'publisher',
    'publicher' => 'publisher',
    'tiitle' => 'title',
    'url-sttaus' => 'url-status',
    'wbesite' => 'website',
    'wbsite' => 'website',
    'websie' => 'website',
    'website l' => 'website',
    'wrok' => 'work',
    'years' => 'year',
    'data dostępu' => 'access-date',
    'date-retrieved' => 'access-date',
    'hämtår' => 'year',
    'hämtmånad' => 'month',
    'izdavač' => 'publisher',
    'автор' => 'author',
    'том' => 'volume',
    'lanuage' => 'language',
    'trabns-title' => 'trans-title',
    'access.date' => 'access-date',
    'ast1' => 'last1',
    'orig_date' => 'orig-date',
    'woek' => 'work',
    'wevsite' => 'website',
    'ed77ition' => 'edition',
    'pagse' => 'page',
    'accfess-date' => 'access-date',
    'dae' => 'date',
    'swebsite' => 'website',
    'ye ar' => 'year',
    'authorlionk' => 'authorlink',
    'lastname' => 'last',
    'firstname' => 'first',
    'last-name' => 'last',
    'first-name' => 'first',
    'publishee' => 'publisher',
    'web url' => 'url',
    'datum vydání' => 'date',
    'заглавие' => 'title',
    'fisrt1' => 'first1',
    'archive-qurl' => 'archive-url',
    'daze' => 'date',
    'odkaz na autora' => 'author-link',
    'אתר' => 'website',
    'כותרת' => 'title',
    'תאריך' => 'date',
    'accesssdate' => 'access-date',
    'firts' => 'first',
    'pub;isher' => 'publisher',
    'transtitle' => 'trans-title',
    'websote' => 'website',
    'daye' => 'date',
    'contribution url' => 'contribution-url',
    'archive- date' => 'archive-date',
    'lagnuage' => 'language',
    'আর্কাইভের-url' => 'archive-url',
    'আর্কাইভের-তারিখ' => 'archive-date',
    'সংগ্রহের-তারিখ' => 'access-date',
    'língua' => 'language',
    'author 1' => 'author1',
    'publisehr' => 'publisher',
    'archve-url' => 'archive-url',
    'archive-ulr' => ' archive-url',
    'author 2' => 'author2',
    'journals' => 'journal',
    'sprache' => 'language',
    'ngày tháng' => 'date',
    'url-stauts' => 'url-status',
    'aithor' => 'author',
    'họ' => 'last',
    'họ 1' => 'last1',
    'họ 2' => 'last2',
    'họ 3' => 'last3',
    'họ 4' => 'last4',
    'họ 5' => 'last5',
    'họ 6' => 'last6',
    'tên' => 'first',
    'tên 1' => 'first1',
    'tên 2' => 'first2',
    'tên 3' => 'first3',
    'tên 4' => 'first4',
    'tên 5' => 'first5',
    'tên 6' => 'first6',
    'locations' => 'location',
    'locstion' => 'location',
    'zugriff' => 'access-date',
    'odkaz na titul' => 'title-link',
    'vydanie' => 'edition',
    'url-stats' => 'url-status',
    'first 1' => 'first1',
    'ifirst' => 'first',
    'trans-tite' => 'trans-title',
    'publish' => 'publisher',
    'last-author' => 'last',
    'last-author1' => 'last1',
    'last-author2' => 'last2',
    'last-author3' => 'last3',
    'last-author4' => 'last4',
    'last-author5' => 'last5',
    'last-author6' => 'last6',
    'first-author' => 'first',
    'first-author1' => 'first1',
    'first-author2' => 'first2',
    'first-author3' => 'first3',
    'first-author4' => 'first4',
    'first-author5' => 'first5',
    'first-author6' => 'first6',
    'acrhiveurl' => 'archive-url',
    'archive-daye' => 'archive-date',
    'archive-rl' => 'archive-url',
    'laest' => 'last',
    'punlisher' => 'publisher',
    'websinte' => 'website',
    'aauthor1-link' => 'author1-link',
    'wprk' => 'work',
    'title-lik' => 'title-link',
    'archívurl' => 'archiveurl',
    'tltle' => 'title',
    'archívdátum' => 'archive-date',
    'elérés' => 'access-date',
    'kiadó' => 'publisher',
    'labng' => 'lang',
    'l<nguage' => 'language',
    'urel' => 'url',
    'archiveadate' => 'archive-date',
    'abizena1' => 'last1',
    'argitaletxea' => 'publisher',
    'egile1-lotura' => 'author1-link',
    'izena1' => 'first1',
    'izenburua' => 'title',
    'urtea' => 'year',
    'year_published' => 'year',
    'publish-date' => 'date',
    'accessd-date' => 'access-date',
    'author -link' => 'author-link',
    'editor-others' => 'editor-given',
    'first 2' => 'first2',
    'languafe' => 'language',
    'lsst2' => 'last2',
    'url-status-' => 'url-status',
    'chapter-title' => 'chapter',
    'jornual' => 'journal',
    'autorlink' => 'authorlink',
    'visiteddate' => 'access-date',
    'datw' => 'date',
    'authour' => 'author',
    'urk' => 'url',
    'firat' => 'first',
    'viay' => 'via',
    'languange' => 'language',
    'translate' => 'translator',
    'url-stastus' => 'url-status',
    'accessadte' => 'accessdate',
    'replaced série' => 'series',
    'ocls' => 'oclc',
    'langusge' => 'language',
    'accessidate' => 'access-date',
    'archive -url' => 'archive-url',
    'publisherc' => 'publisher',
    'arccess-date' => 'access-date',
    'plast' => 'last',
    'access -date' => 'access-date',
    'totle' => 'title',
    'luku' => 'number',
    'سال' => 'year',
    'আইএসবিএন' => 'isbn',
    'تاریخ بازبینی' => 'access-date',
    'সংস্করণ' => 'edition',
    'পাতাসমূহ' => 'pages',
    'seriestitle' => 'series',
    'chapte-url' => 'chapter-url',
    'display-author' => 'display-authors',
    'pmdi' => 'pmid',
    'dayyte' => 'date',
    'forst' => 'first',
    'ladt' => 'last',
    'publishe' => 'publisher',
    'langyage' => 'language',
    'paage' => 'page',
    'oyblisher' => 'publisher',
    'lasat' => 'last',
    'sate' => 'date',
    'accessdat' => 'accessdate',
    'firt2' => 'first2',
    'jouranl' => 'journal',
    'auhtor3' => 'author3',
    'pulbisher' => 'publisher',
    '보존url' => 'archive-url',
    '보존날짜' => 'archive-date',
    '언어' => 'language',
    '날짜' => 'date',
    'väljaandja' => 'publisher',
    'väljaanne' => 'work',
    'γλώσσα' => 'language',
    'consulté le' => 'access-date',
    'kasutatud' => 'access-date',
    'urlarquivo' => 'archive-url',
    'urlmorta' => 'deadurl',
    'پیوند' => 'url',
    'v authors' => 'vauthors',
    'atchive-date' => 'archive-date',
    'vauthoes' => 'vauthors',
    'dtae' => 'date',
    'last 2' => 'last2',
    'volumen' => 'volume',
    'webaite' => 'website',
    'editorlast' => 'editor-last',
    'tarns-title' => 'trans-title',
    'authro2-link' => 'author2-link',
    'firs1' => 'first1',
    'axccessdate' => 'accessdate',
    'handle' => 'hdl',
    'oriyear-' => 'origyear',
    'arquivodata' => 'archivedate',
    'arquivourl' => 'archiveurl',
    'xhapter' => 'chapter',
    'publicado' => 'publisher',
    'accessadate' => 'access-date',
    'publisjer' => 'publisher',
    'author_link' => 'author-link',
    'pkace' => 'place',
    'fisrt' => 'first',
    'langugae' => 'language',
    'newpaper' => 'newspaper',
    'arkiv-dato' => 'archivedate',
    'arkiv-url' => 'archiveurl',
    'lastname1' => 'last1',
    'lastname2' => 'last2',
    'lastname3' => 'last3',
    'lastname4' => 'last4',
    'lastname5' => 'last5',
    'lastname6' => 'last6',
    'lastname7' => 'last7',
    'lastname8' => 'last8',
    'lastname9' => 'last9',
    'encylopedia' => 'encyclopedia',
    'auhtor' => 'author',
    'urll' => 'url',
    'firts3' => 'first3',
    'chaoter' => 'chapter',
    'uyrl' => 'url',
]; // Lots of stuff that just existed

const COMMON_MISTAKES_TOOL = [
    'accessdate' => 'access-date',
    'archivedate' => 'archive-date',
    'archiveurl' => 'archive-url',
    'authorlink' => 'author-link',
    'origyear' => 'orig-date',
    'airdate' => 'air-date',
];

    // Find these with this on all the various types https://en.wikipedia.org/w/index.php?title=Special:WhatLinksHere/Template:Citation&hidelinks=1&hidetrans=1
const TEMPLATE_CONVERSIONS = [
    ['cite', 'citation'],
    ['Cite', 'Citation'],
    ['citebook', 'cite book'],
    ['Citebook', 'Cite book'],
    ['cit book', 'cite book'],
    ['Cit book', 'Cite book'],
    ['cite ebook', 'cite book'],
    ['Cite ebook', 'Cite book'],
    ['cite books', 'cite book'],
    ['Cite books', 'Cite book'],
    ['book reference', 'cite book'],
    ['Book reference', 'Cite book'],
    ['web reference', 'cite web'],
    ['Web reference', 'Cite web'],
    ['Conference reference', 'Cite conference'],
    ['conference reference', 'cite conference'],
    ['citejournal', 'cite journal'],
    ['Citejournal', 'Cite journal'],
    ['citeweb', 'cite web'],
    ['Citeweb', 'Cite web'],
    ['cite-web', 'cite web'],
    ['Cite-web', 'Cite web'],
    ['cit web', 'cite web'],
    ['Cit web', 'Cite web'],
    ['cit journal', 'cite journal'],
    ['Cit journal', 'Cite journal'],
    ['cit news', 'cite news'],
    ['Cit news', 'Cite news'],
    ['cite url', 'cite web'],
    ['Cite url', 'Cite web'],
    ['web cite', 'cite web'],
    ['Web cite', 'Cite web'],
    ['book cite', 'cite book'],
    ['Book cite', 'Cite book'],
    ['cite-book', 'cite book'],
    ['Cite-book', 'Cite book'],
    ['citenews', 'cite news'],
    ['Citenews', 'Cite news'],
    ['cite-news', 'cite news'],
    ['Cite-news', 'Cite news'],
    ['citepaper', 'cite paper'],
    ['Citepaper', 'Cite paper'],
    ['cite chapter', 'cite book'],
    ['Cite chapter', 'Cite book'],
    ['citation journal', 'cite journal'],
    ['Citation journal', 'Cite journal'],
    ['cite new', 'cite news'],
    ['Cite new', 'Cite news'],
    ['cite newspaper', 'cite news'],
    ['Cite newspaper', 'Cite news'],
    ['cite Web', 'cite web'],
    ['Cite Web', 'Cite web'],
    ['cite media', 'cite AV media'],
    ['Cite media', 'Cite AV media'],
    ['cite av media', 'cite AV media'],
    ['Cite av media', 'Cite AV media'],
    ['cite Journal', 'cite journal'],
    ['Cite Journal', 'Cite journal'],
    ['cite Book', 'cite book'],
    ['Cite Book', 'Cite book'],
    ['cite News', 'cite news'],
    ['Cite News', 'Cite news'],
    ['cite citation', 'citation'],
    ['Cite citation', 'Citation'],
    ['Cite n', 'Cite news'],
    ['cite n', 'cite news'],
    ['Citation news', 'Cite news'],
    ['citation news', 'cite news'],
    ['C news', 'Cite news'],
    ['c news', 'cite news'],
    ['Cute news', 'Cite news'],
    ['cute news', 'cite news'],
    ['Cite news2', 'Cite news'],
    ['cite news2', 'cite news'],
    ['Citar notícia', 'Cite news'],
    ['citar notícia', 'cite news'],
    ['뉴스 인용', 'Cite news'],
    ['Cite study', 'Citation'],
    ['cite study', 'citation'],
    ['Vcite2 journal', 'Cite journal'],
    ['vcite2 journal', 'cite journal'],
    ['Web link', 'Cite web'],
    ['web link', 'cite web'],
    ['Citweb', 'Cite web'],
    ['citweb', 'cite web'],
    ['Citat web', 'Cite web'],
    ['citat web', 'cite web'],
    ['Cite we', 'Cite web'],
    ['cite we', 'cite web'],
    ['Cite w', 'Cite web'],
    ['cite w', 'cite web'],
    ['Cite wb', 'Cite web'],
    ['cite wb', 'cite web'],
    ['Cite web.', 'Cite web'],
    ['cite web.', 'cite web'],
    ['Cw', 'Cite web'],
    ['cw', 'cite web'],
    ['C web', 'Cite web'],
    ['c web', 'cite web'],
    ['Cita web', 'Cite web'],
    ['cita web', 'cite web'],
    ['Cite webpage', 'Cite web'],
    ['cite webpage', 'cite web'],
    ['Weblink', 'Cite web'],
    ['weblink', 'cite web'],
    ['Cite blog', 'Cite web'],
    ['cite blog', 'cite web'],
    ['Web citation', 'Cite web'],
    ['web citation', 'cite web'],
    ['Cite website', 'Cite web'],
    ['cite website', 'cite web'],
    ['Cite page', 'Cite book'],
    ['cite page', 'cite book'],
    ['Cite publication', 'Cite book'],
    ['cite publication', 'cite book'],
    ['Citeencyclopedia', 'Cite encyclopedia'],
    ['citeencyclopedia', 'cite encyclopedia'],
    ['Encyclopedia', 'Cite encyclopedia'],
    ['encyclopedia', 'cite encyclopedia'],
//    ['Cite contribution', 'Cite encyclopedia'],
//    ['cite contribution', 'cite encyclopedia'],
    ['Cita pubblicazione', 'Cite journal'],
    ['cita pubblicazione', 'cite journal'],
    ['Citace elektronické monografie', 'Cite web'],
    ['citace elektronické monografie', 'cite web'],
    ['Chú thích web', 'Cite web'],
    ['Chú thích báo', 'Cite news'],
    ['chú thích web', 'cite web'],
    ['chú thích báo', 'cite news'],
    ['tidskriftsref', 'cite journal'],
    ['Tidskriftsref', 'Cite journal'],
    ['Tidningsref', 'Cite news'],
    ['tidningsref', 'cite news'],
    ['GroveOnline', 'Cite Grove'],
    ['Groveonline', 'Cite Grove'],
    ['groveOnline', 'Cite Grove'],
    ['groveonline', 'Cite Grove'],
    ['NewGrove1980', 'Cite NewGrove1980'],
    ['newGrove1980', 'Cite NewGrove1980'],
    ['citar livro', 'cite book'],
    ['Citar livro', 'Cite book'],
    ['Citace monografie', 'cite book'],
    ['citace monografie', 'Cite book'],
    ['Bokref', 'cite book'],
    ['bokref', 'Cite book'],
    ['Cite press', 'Cite press release'],
    ['cite press', 'cite press release'],
    ['cite media', 'cite AV media'],
    ['Cite media', 'Cite AV media'],
    ['cite audio', 'cite AV media'],
    ['Cite audio', 'Cite AV media'],
    ['vcite video', 'cite AV media'],
    ['Vcite video', 'Cite AV media'],
    ['cite music video', 'cite AV media'],
    ['Cite music video', 'Cite AV media'],
    ['cite visual', 'cite AV media'],
    ['Cite visual', 'Cite AV media'],
    ['cite cd', 'cite AV media'],
    ['Cite cd', 'Cite AV media'],
    ['citevideo', 'cite AV media'],
    ['Citevideo', 'Cite AV media'],
    ['cite AV Media', 'cite AV media'],
    ['Cite AV Media', 'Cite AV media'],
    ['cite song', 'cite AV media'],
    ['Cite song', 'Cite AV media'],
    ['cite AVMedia', 'cite AV media'],
    ['Cite AVMedia', 'Cite AV media'],
    ['cita víde', 'cite AV media'],
    ['Cita víde', 'Cite AV media'],
    ['cite Youtube', 'cite AV media'],
    ['Cite Youtube', 'Cite AV media'],
    ['cite AV', 'cite AV media'],
    ['Cite AV', 'Cite AV media'],
    ['cite YouTube', 'cite AV media'],
    ['Cite YouTube', 'Cite AV media'],
    ['cite documentary', 'cite AV media'],
    ['Cite documentary', 'Cite AV media'],
    ['cite film', 'cite AV media'],
    ['Cite film', 'Cite AV media'],
    ['cite movie', 'cite AV media'],
    ['Cite movie', 'Cite AV media'],
    ['cite dvd', 'cite AV media'],
    ['Cite dvd', 'Cite AV media'],
    ['cite DVD', 'cite AV media'],
    ['Cite DVD', 'Cite AV media'],
    ['cite image', 'cite AV media'],
    ['Cite image', 'Cite AV media'],
    ['cite radio', 'cite AV media'],
    ['Cite radio', 'Cite AV media'],
    ['cite movie', 'cite AV media'],
    ['Cite movie', 'Cite AV media'],
    ['Vcite press release', 'Cite press release'],
    ['vcite press release', 'cite press release'],
    ['Cite media release', 'Cite press release'],
    ['cite media release', 'cite press release'],
    ['Cite press-release', 'Cite press release'],
    ['cite press-release', 'cite press release'],
    ['Cite pr', 'Cite press release'],
    ['cite pr', 'cite press release'],
    ['Cite news release', 'Cite press release'],
    ['cite news release', 'cite press release'],
    ['Cite Press release', 'Cite press release'],
    ['cite Press release', 'cite press release'],
    ['Cite press release.', 'Cite press release'],
    ['cite press release.', 'cite press release'],
    ['Cite pressrelease', 'Cite press release'],
    ['cite pressrelease', 'cite press release'],
    ['Cite standard', 'Cite tech report'],
    ['cite standard', 'cite tech report'],
    ['Cite technical report', 'Cite tech report'],
    ['cite technical report', 'cite tech report'],
    ['Cite techreport', 'Cite tech report'],
    ['cite techreport', 'cite tech report'],
    ['Techrep reference', 'Cite tech report'],
    ['techrep reference', 'cite tech report'],
    ['Cite abstract', 'Cite journal'],
    ['cite abstract', 'cite journal'],
    ['Cytuj_pismo', 'Cite journal'],
    ['cytuj_pismo', 'cite journal'],
    ['Citace periodika', 'Cite journal'],
    ['citace periodika', 'cite journal'],
    ['Cite dissertation', 'Cite thesis'],
    ['cite dissertation', 'cite thesis'],
    ['Citar tese', 'Cite thesis'],
    ['citar tese', 'cite thesis'],
    ['Cite ssrn', 'Cite SSRN'],
    ['cite ssrn', 'cite SSRN'],
    ['Cite plaque', 'Cite sign'],
    ['cite plaque', 'cite sign'],
    ['Cite usenet', 'Cite newsgroup'],
    ['cite usenet', 'cite newsgroup'],
    ['Cite Usenet', 'Cite newsgroup'],
    ['cite Usenet', 'cite newsgroup'],
    ['Navedi novice', 'Cite news'],
    ['navedi novice', 'cite news'],
    ['Cite maps', 'Cite map'],
    ['cite maps', 'cite map'],
    ['Cite biorxiv', 'Cite bioRxiv'],
    ['cite biorxiv', 'cite bioRxiv'],
    ['Cite list', 'Cite mailing list'],
    ['cite list', 'cite mailing list'],
    ['Cite mailinglist', 'Cite mailing list'],
    ['cite mailinglist', 'cite mailing list'],
    ['Cite ArXiv', 'Cite arXiv'],
    ['cite ArXiv', 'cite arXiv'],
    ['Cite arxiv', 'Cite arXiv'],
    ['cite arxiv', 'cite arXiv'],
    ['Cite av media notes', 'Cite AV media notes'],
    ['cite av media notes', 'cite AV media notes'],
    ['Cite DVD-notes', 'Cite AV media notes'],
    ['cite DVD-notes', 'cite AV media notes'],
    ['Cite album notes', 'Cite AV media notes'],
    ['cite album notes', 'cite AV media notes'],
    ['Cite album-notes', 'Cite AV media notes'],
    ['cite album-notes', 'cite AV media notes'],
    ['Liner notes', 'Cite AV media notes'],
    ['liner notes', 'cite AV media notes'],
    ['Cite liner notes', 'Cite AV media notes'],
    ['cite liner notes', 'cite AV media notes'],
    ['Vcite album-notes', 'Cite AV media notes'],
    ['vcite album-notes', 'cite AV media notes'],
    ['Cite music release notes', 'Cite AV media notes'],
    ['cite music release notes', 'cite AV media notes'],
    ['Cite dvd-notes', 'Cite AV media notes'],
    ['cite dvd-notes', 'cite AV media notes'],
    ['Cite DVD notes', 'Cite AV media notes'],
    ['cite DVD notes', 'cite AV media notes'],
    ['Cite citeseerx', 'Cite CiteSeerX'],
    ['cite citeseerx', 'cite CiteSeerX'],
    ['Cite citeseer', 'Cite CiteSeerX'],
    ['cite citeseer', 'cite CiteSeerX'],
    ['Cite CiteSeer', 'Cite CiteSeerX'],
    ['cite CiteSeer', 'cite CiteSeerX'],
    ['Cite proceedings', 'Cite conference'],
    ['cite proceedings', 'cite conference'],
    ['Cite presentation', 'Cite conference'],
    ['cite presentation', 'cite conference'],
    ['Cite mag', 'Cite magazine'],
    ['cite mag', 'cite magazine'],
    ['Cite magazine article', 'Cite magazine'],
    ['cite magazine article', 'cite magazine'],
    ['Cite Magazine', 'Cite magazine'],
    ['cite Magazine', 'cite magazine'],
    ['Cite show', 'Cite episode'],
    ['cite show', 'cite episode'],
    ['Vcite episode', 'Cite episode'],
    ['vcite episode', 'cite episode'],
    ['Vancite episode', 'Cite episode'],
    ['vancite episode', 'cite episode'],
    ['Cite Episode', 'Cite episode'],
    ['cite Episode', 'cite episode'],
    ['Cite encyclopædia', 'Cite encyclopedia'],
    ['cite encyclopædia', 'cite encyclopedia'],
    ['Proquest', 'ProQuest'],
    ['proquest', 'ProQuest'],
    ['Pq', 'ProQuest'],
    ['pq', 'ProQuest'],
    ['DOI', 'doi'],
    ['Doi', 'doi'],
    ['Deadurl', 'Dead link'],
    ['deadurl', 'dead link'],
    ['Citeseerx', 'CiteSeerX'],
    ['citeseerx', 'CiteSeerX'],
    ['GALE', 'Gale'],
    ['Ebsco', 'EBSCOhost'],
    ['Ebscohost', 'EBSCOhost'],
    ['EBSCO', 'EBSCOhost'],
    ['ebsco', 'EBSCOhost'],
    ['ebscohost', 'EBSCOhost'],
    ['eBSCO', 'EBSCOhost'],
    ['Ncid', 'NCID'],
    ['ncid', 'NCID'],
    ['BHLpage', 'BHL page'],
    ['Internet archive', 'Internet Archive'],
    ['internet archive', 'Internet Archive'],
    ['youtube', 'YouTube'],
    ['Youtube', 'YouTube'],
    ['pmc', 'PMC'],
    ['pmid', 'PMID'],
    ['jstor', 'JSTOR'],
    ['lccn', 'LCCN'],
    ['Pmc', 'PMC'],
    ['Pmid', 'PMID'],
    ['Jstor', 'JSTOR'],
    ['Lccn', 'LCCN'],
    ['urn', 'URN'],
    ['Urn', 'URN'],
    ['ISSN search link', 'ISSN link'],
    ['ISSNT', 'ISSN link'],
    ['issn search', 'ISSN link'],
    ['ISSN pair', 'ISSN link'],
    ['paywall', 'subscription required'],
    ['Paywall', 'Subscription required'],
    ['Required subscription', 'Subscription required'],
    ['Subscriptionrequired', 'Subscription required'],
    ['Subscription needed', 'Subscription required'],
    ['Pay', 'Subscription required'],
    ['Restricted access', 'Subscription required'],
    ['Paywalled', 'Subscription required'],
    ['Subscription-required', 'Subscription required'],
    ['Requires subscription', 'Subscription required'],
    ['Premium access', 'Subscription required'],
    ['Premium content', 'Subscription required'],
    ['Locked content', 'Subscription required'],
    ['Subscription only', 'Subscription required'],
    ['Subscribers only', 'Subscription required'],
    ['Subreq', 'Subscription required'],
    ['Subscription', 'Subscription required'],
    ['required subscription', 'subscription required'],
    ['subscriptionrequired', 'subscription required'],
    ['subscription needed', 'subscription required'],
    ['pay', 'subscription required'],
    ['restricted access', 'subscription required'],
    ['paywalled', 'subscription required'],
    ['subscription-required', 'subscription required'],
    ['requires subscription', 'subscription required'],
    ['premium access', 'subscription required'],
    ['premium content', 'subscription required'],
    ['locked content', 'subscription required'],
    ['subscription only', 'subscription required'],
    ['subscribers only', 'subscription required'],
    ['subreq', 'subscription required'],
    ['subscription', 'subscription required'],
    ['registration', 'registration required'],
    ['Registration', 'Registration required'],
    ['reg', 'registration required'],
    ['Reg', 'Registration required'],
    ['regreq', 'registration required'],
    ['Regreq', 'Registration required'],
    ['registration-required', 'registration required'],
    ['Registration-required', 'Registration required'],
    ['registration needed', 'registration required'],
    ['Registration needed', 'Registration required'],
    ['cite article', 'cite news'],
    ['Cite article', 'Cite news'],
];
