<?php

declare(strict_types=1);

const COMMON_MISTAKES = [ // Common mistakes that aren't picked up by the levenshtein approach.  And obvious ones to reduce levenshtein dependence
    '_isbn' => 'isbn',
    '–citeseerx' => 'citeseerx',
    '—publisher' => 'publisher',
    ';ast1' => 'last1',
    '4rl' => 'url',
    'a frccess-date' => 'access-date',
    'aauthor1-link' => 'author1-link',
    'abizena1' => 'last1',
    'abruf' => 'access-date',
    'accces-date' => 'access-date',
    'acccesdate' => 'access-date',
    'acccess-date' => 'access-date',
    'acccessdate' => 'access-date',
    'acceaadate' => 'access-date',
    'accecssdate' => 'access-date',
    'acceessdate' => 'access-date',
    'accerssdate' => 'access-date',
    'acces date' => 'access-date',
    'acces-date' => 'access-date',
    'acces-sdate' => 'access-date',
    'accesadate' => 'access-date',
    'accesdante' => 'access-date',
    'accesdate' => 'access-date',
    'accesjs-date' => 'access-date',
    'access  date' => 'access-date',
    'access -date' => 'access-date',
    'access date' => 'access-date',
    'access day' => 'access-date',
    'access_date' => 'access-date',
    'access- date' => 'access-date',
    'access- дата' => 'access-date',
    'access-1date' => 'access-date',
    'access-9date' => 'access-date',
    'access-adate' => 'access-date',
    'access-as te' => 'access-date',
    'access-ate' => 'access-date',
    'access-crip' => 'access-date',
    'access-daet' => 'access-date',
    'access-daite' => 'access-date',
    'access-dat' => 'access-date',
    'access-date-' => 'access-date',
    'access-datee' => 'access-date',
    'access-datr' => 'access-date',
    'access-daye' => 'access-date',
    'access-dtae' => 'access-date',
    'access-sate' => 'access-date',
    'access-url' => 'url-access',
    'access–date' => 'access-date',
    'access.date' => 'access-date',
    'access' => 'access-date',
    'access≥-date' => 'access-date',
    'access0date' => 'access-date',
    'accessadate' => 'access-date',
    'accessadte' => 'access-date',
    'accessd-ate' => 'access-date',
    'accessd-date' => 'access-date',
    'accessdaate' => 'access-date',
    'accessdare' => 'access-date',
    'accessdaste' => 'access-date',
    'accessdat' => 'access-date',
    'accessdatae' => 'access-date',
    'accessdatet' => 'access-date',
    'accessdatr' => 'access-date',
    'accessddate' => 'access-date',
    'accessdtae' => 'access-date',
    'accesse-date' => 'access-date',
    'accessed date' => 'access-date',
    'accessed on' => 'access-date',
    'accessed-date' => 'access-date',
    'accessed' => 'access-date',
    'accessedate' => 'access-date',
    'accesseddate' => 'access-date',
    'accessidate' => 'access-date',
    'accesso-date' => 'access-date',
    'accesso' => 'access-date',
    'accesss-date' => 'access-date',
    'accesss-datet' => 'access-date',
    'accesssdate' => 'access-date',
    'accessurl-datestatus' => 'access-date',
    'accessyear' => 'access-date',
    'accetss-date' => 'access-date',
    'accewss-date' => 'access-date',
    'accfess-date' => 'access-date',
    'acecssdate' => 'access-date',
    'acesdate' => 'access-date',
    'acess-daate' => 'access-date',
    'acess-date' => 'access-date',
    'acessdate' => 'access-date',
    'acessodat' => 'access-date',
    'acessodata' => 'access-date',
    'acesss-date' => 'access-date',
    'achive-url' => 'archive-url',
    'achivedate' => 'archive-date',
    'acrhiveurl' => 'archive-url',
    'acsess date' => 'access-date',
    'acsess-date' => 'access-date',
    'ad1' => 'author1',
    'aeccess-date' => 'access-date',
    'aessdate' => 'access-date',
    'afirst1' => 'first1',
    'agencia' => 'agency',
    'aithor' => 'author',
    'aktualizace' => 'access-date',
    'albumlink' => 'title-link',
    'alst4' => 'last4',
    'anguage' => 'language',
    'année réimpression' => 'date',
    'année' => 'date',
    'anno' => 'date',
    'annooriginale' => 'orig-year',
    'año-original' => 'orig-year',
    'ano' => 'date',
    'año' => 'date',
    'añooriginal' => 'orig-year',
    'ansiklopedi' => 'encyclopedia',
    'aothers' => 'others',
    'apelidos' => 'last',
    'apellido' => 'last',
    'apellido1' => 'last1',
    'apellido10' => 'last10',
    'apellido2' => 'last2',
    'apellido3' => 'last3',
    'apellido4' => 'last4',
    'apellido5' => 'last5',
    'apellido6' => 'last6',
    'apellido7' => 'last7',
    'apellido8' => 'last8',
    'apellido9' => 'last9',
    'apellidos' => 'last',
    'apellidos1' => 'last1',
    'apellidos10' => 'last10',
    'apellidos2' => 'last2',
    'apellidos3' => 'last3',
    'apellidos4' => 'last4',
    'apellidos5' => 'last5',
    'apellidos6' => 'last6',
    'apellidos7' => 'last7',
    'apellidos8' => 'last8',
    'apellidos9' => 'last9',
    'år' => 'date',
    'arccess-date' => 'access-date',
    'arcguve-date' => 'archive-date',
    'archiefdatum' => 'archive-date',
    'archiefurl' => 'archive-url',
    'archifurl' => 'archive-url',
    'archiv-date' => 'archive-date',
    'archiv-url' => 'archive-url',
    'archivce-date' => 'archive-date',
    'archívdátum' => 'archive-date',
    'archive -date' => 'archive-date',
    'archive -url' => 'archive-url',
    'archive date' => 'archive-date',
    'archive path' => 'archive-url',
    'archive url' => 'archive-url',
    'archive_date' => 'archive-date',
    'archive_url' => 'archive-url',
    'archive-  date' => 'archive-date',
    'archive-    date' => 'archive-date',
    'archive- date' => 'archive-date',
    'archive- url' => 'archive-url',
    'archive-.url' => 'archive-url',
    'archive-da te' => 'archive-date',
    'archive-dat' => 'archive-date',
    'archive-daye' => 'archive-date',
    'archive-link' => 'archive-url',
    'archive-qurl' => 'archive-url',
    'archive-rl' => 'archive-url',
    'archive-rurl' => 'archive-url',
    'archive-seekurl' => 'archive-url',
    'archive-the url' => 'archive-url',
    'archive-ulr' => 'archive-url',
    'archive-ur' => 'archive-url',
    'archive-urk' => 'archive-url',
    'archive-url a' => 'archive-url',
    'archive-طate' => 'archive-date',
    'archive0date' => 'access-date',
    'archiveadate' => 'archive-date',
    'archived ate' => 'archive-date',
    'archived-date' => 'archive-date',
    'archivedat' => 'archive-date',
    'archivedata' => 'archive-date',
    'archivedte' => 'archive-date',
    'archivel-url' => 'archive-url',
    'archivelink' => 'archive-url',
    'archiverul' => 'archive-url',
    'archives-url' => 'archive-url',
    'archivurl' => 'archive-url',
    'archívurl' => 'archive-url',
    'archove-date' => 'archive-date',
    'archve-date' => 'archive-date',
    'archve-url' => 'archive-url',
    'archvie-date' => 'archive-date',
    'archvie-url' => 'archive-url',
    'arčive-date' => 'archive-date',
    'arcive-url' => 'archive-url',
    'arčive-url' => 'archive-url',
    'argitaletxea' => 'publisher',
    'arhcive-date' => 'archive-date',
    'arhiivimisaeg' => 'archive-date',
    'arhiivimisurl' => 'archive-url',
    'arhive-date' => 'archive-date',
    'arhiviranjedatum' => 'archive-date',
    'arhiviranjeurl' => 'archive-url',
    'arkiv-dato' => 'archive-date',
    'arkiv-url' => 'archive-url',
    'arkivdatum' => 'archive-date',
    'arkivurl' => 'archive-url',
    'arquivodata' => 'archive-date',
    'arquivourl' => 'archive-url',
    'arşivtarihi' => 'archive-date',
    'arşivurl' => 'archive-url',
    'artist' => 'others',
    'ARXIV' => 'arxiv',
    'ASIN' => 'asin',
    'ast1' => 'last1',
    'atchive-date' => 'archive-date',
    'ate' => 'date',
    'auhor' => 'author',
    'auhthor2' => 'author2',
    'auhtor' => 'author',
    'auhtor3' => 'author3',
    'aurhor' => 'author',
    'aurl' => 'url',
    'auteur1' => 'author1',
    'auteur2' => 'author2',
    'auteur3' => 'author3',
    'auteur4' => 'author4',
    'auteur5' => 'author5',
    'auteur6' => 'author6',
    'auteurslink' => 'author-link',
    'auther' => 'author',
    'autho-link' => 'author-link',
    'autho' => 'author',
    'autho1' => 'author1',
    'autho2' => 'author2',
    'autho3' => 'author3',
    'autho4' => 'author4',
    'autho5' => 'author5',
    'autho6' => 'author6',
    'autho7' => 'author7',
    'author -link' => 'author-link',
    'author 1' => 'author1',
    'author 2' => 'author2',
    'author link' => 'author-link',
    'author_first' => 'author-first',
    'author_last' => 'author-last',
    'author_link' => 'author-link',
    'author-1' => 'author1',
    'author-2' => 'author2',
    'author-3' => 'author3',
    'author-4' => 'author4',
    'author-likn3' => 'author-link3',
    'author-lin' => 'author-link',
    'author-maske' => 'author-mask',
    'authore' => 'author',
    'authored' => 'authors',
    'authorlionk' => 'author-link',
    'authors1' => 'author1',
    'authorurl' => 'author-link',
    'authour' => 'author',
    'authro1-link' => 'author1-link',
    'authro2-link' => 'author2-link',
    'autor' => 'author',
    'autor1' => 'author1',
    'autor2' => 'author2',
    'autor3' => 'author3',
    'autor4' => 'author4',
    'autore' => 'author',
    'autore2' => 'author2',
    'autore3' => 'author3',
    'autore4' => 'author4',
    'autorlink' => 'author-link',
    'axccessdate' => 'access-date',
    'axriv' => 'arxiv',
    'aythor' => 'author',
    'başlık' => 'title',
    'besøksdato' => 'access-date',
    'bibcod' => 'bibcode',
    'bioRxiv' => 'biorxiv',
    'bolume' => 'volume',
    'book title' => 'book-title',
    'booktitle' => 'book-title',
    'brisé le' => 'access-date',
    'by' => 'author',
    'çalışma' => 'title',
    'çalıwebsite' => 'website',
    'capítulo' => 'chapter',
    'cate' => 'date',
    'ccess-date' => 'access-date',
    'chaopter' => 'chapter',
    'chaoter' => 'chapter',
    'chaper' => 'chapter',
    'chapte-url' => 'chapter-url',
    'chapter title' => 'chapter',
    'chapter-title' => 'chapter',
    'chaptertitle' => 'chapter',
    'chapterurl' => 'chapter-url',
    'chater' => 'chapter',
    'chatper-url' => 'chapter-url',
    'chatper' => 'chapter',
    'check date' => 'access-date',
    'cilt' => 'volume',
    'cita' => 'quote',
    'citação' => 'quote',
    'citazione' => 'quote',
    'città' => 'location',
    'city' => 'location',
    'co-author' => 'coauthors',
    'co-authors' => 'coauthors',
    'coauther' => 'coauthors',
    'coauthor' => 'coauthors',
    'coautores' => 'coauthors',
    'coautori' => 'coauthors',
    'coautors' => 'coauthors',
    'cognom' => 'last',
    'cognome' => 'last',
    'cognome1' => 'last1',
    'cognome2' => 'last2',
    'cognome3' => 'last3',
    'cointerviewers' => 'others',
    'colume' => 'volume',
    'conferenceurl' => 'conference-url',
    'consulta' => 'access-date',
    'consulté le' => 'access-date',
    'consulté' => 'access-date',
    'consulted on' => 'access-date',
    'contribution url' => 'contribution-url',
    'contributionurl' => 'contribution-url',
    'curatore' => 'author',
    'dae' => 'date',
    'dare' => 'date',
    'dat e' => 'date',
    'data archive' => 'archive-date',
    'data dostępu' => 'access-date',
    'data-acceso' => 'access-date',
    'data-arquivo' => 'archive-date',
    'data-publicación' => 'date',
    'datăaccesare' => 'access-date',
    'dataaccesso' => 'access-date',
    'dataarchivio' => 'archive-date',
    'datae' => 'date',
    'date access' => 'access-date',
    'date accessed' => 'access-date',
    'date date' => 'date',
    'date of access' => 'access-date',
    'date of publication' => 'publication-date',
    'date retrieved' => 'access-date',
    'date visited' => 'access-date',
    'date_archive' => 'archive-date',
    'date-access' => 'access-date',
    'date-accessed' => 'access-date',
    'date-published' => 'publication-date',
    'date-retrieved' => 'access-date',
    'dateaccess' => 'access-date',
    'datearchive' => 'archive-date',
    'datearchived' => 'archive-date',
    'datearchivo' => 'archive-date',
    'dated' => 'date',
    'datee' => 'date',
    'datefile' => 'date',
    'datepublished' => 'date',
    'dato' => 'date',
    'datr' => 'date',
    'dats' => 'date',
    'datte' => 'date',
    'datue' => 'date',
    'datum archivace' => 'archive-date',
    'datum přístupu' => 'access-date',
    'datum vydání' => 'date',
    'datum' => 'date',
    'datw' => 'date',
    'daye' => 'date',
    'dayyte' => 'date',
    'daze' => 'date',
    'deaadurl' => 'deadurl',
    'dead-link' => 'deadurl',
    'deadlink' => 'deadurl',
    'deađurl' => 'deadurl',
    'dealink' => 'deadurl',
    'deate' => 'date',
    'dergi' => 'journal',
    'día' => 'date',
    'dictionar' => 'dictionary',
    'dil' => 'lang',
    'dio' => 'doi',
    'director' => 'others',
    'display_authors' => 'display-authors',
    'display-author' => 'display-authors',
    'displayauthors' => 'display-authors',
    'displayeditors' => 'display-editors',
    'dition' => 'edition',
    'dlanguage' => 'language',
    'doi_broken_date' => 'doi-broken-date',
    'doi_brokendate' => 'doi-broken-date',
    'doi_inactivedate'=> 'doi-broken-date',
    'doi-acces' => 'doi-access',
    'doi-accesss' => 'doi-access',
    'doi-acess' => 'doi-access',
    'doi-broken' => 'doi-broken-date',
    'doi-inactive-date' => 'doi-broken-date',
    'DOI' => 'doi',
    'dopi' => 'doi',
    'dste' => 'date',
    'dtae' => 'date',
    'dte' => 'date',
    'ebsite' => 'website',
    'ed' => 'editor',
    'ed10' => 'editor10',
    'ed2' => 'editor2',
    'ed3' => 'editor3',
    'ed4' => 'editor4',
    'ed5' => 'editor5',
    'ed6' => 'editor6',
    'ed7' => 'editor7',
    'ed77ition' => 'edition',
    'ed8' => 'editor8',
    'ed9' => 'editor9',
    'edição' => 'edition',
    'éditeur' => 'editor',
    'ediție' => 'edition',
    'edition-' => 'edition',
    'edition-date' => 'date',
    'edito' => 'editor1',
    'edito1' => 'editor1',
    'edito1r' => 'editor1',
    'edito2' => 'editor2',
    'editor_first' => 'editor-first',
    'editor_last' => 'editor-last',
    'editor- last' => 'editor-last',
    'editor-firs1t' => 'editor-first',
    'editor-first-1' => 'editor-first1',
    'editor-first-2' => 'editor-first2',
    'editor-last-1' => 'editor-last1',
    'editor-last-2' => 'editor-last2',
    'editor-nome' => 'editor-first1',
    'editor-nome1' => 'editor-first1',
    'editor-nome2' => 'editor-first2',
    'editor-others' => 'editor-given',
    'editor-sobrenome' => 'editor-last1',
    'editor-sobrenome1' => 'editor-last1',
    'editor-sobrenome2' => 'editor-last2',
    'editor1-first1' => 'editor1-first',
    'editor1-laast' => 'editor1-last',
    'editor10link' => 'editor10-link',
    'editor11link' => 'editor11-link',
    'editor12link' => 'editor12-link',
    'editor13link' => 'editor13-link',
    'editor14link' => 'editor14-link',
    'editor15link' => 'editor15-link',
    'editor16link' => 'editor16-link',
    'editor17link' => 'editor17-link',
    'editor18link' => 'editor18-link',
    'editor19link' => 'editor19-link',
    'editor1link' => 'editor1-link',
    'editor1mask' => 'editor-mask1',
    'editor2-first2' => 'editor2-first',
    'editor2-last2' => 'editor2-last',
    'editor20link' => 'editor20-link',
    'editor21link' => 'editor21-link',
    'editor22link' => 'editor22-link',
    'editor23link' => 'editor23-link',
    'editor24link' => 'editor24-link',
    'editor25link' => 'editor25-link',
    'editor26link' => 'editor26-link',
    'editor27link' => 'editor27-link',
    'editor28link' => 'editor28-link',
    'editor29link' => 'editor29-link',
    'editor2link' => 'editor2-link',
    'editor30link' => 'editor30-link',
    'editor3link' => 'editor3-link',
    'editor4link' => 'editor4-link',
    'editor5link' => 'editor5-link',
    'editor6link' => 'editor6-link',
    'editor7link' => 'editor7-link',
    'editor8link' => 'editor8-link',
    'editor9link' => 'editor9-link',
    'editora' => 'editor1',
    'editoraу' => 'editor',
    'editore' => 'editor',
    'editorfirst' => 'editor-first',
    'editori' => 'editor',
    'editorial' => 'publisher',
    'editorlast' => 'editor-last',
    'editorlink' => 'editor-link',
    'editorlink1' => 'editor1-link',
    'editorlink10' => 'editor10-link',
    'editorlink11' => 'editor11-link',
    'editorlink12' => 'editor12-link',
    'editorlink13' => 'editor13-link',
    'editorlink14' => 'editor14-link',
    'editorlink15' => 'editor15-link',
    'editorlink16' => 'editor16-link',
    'editorlink17' => 'editor17-link',
    'editorlink18' => 'editor18-link',
    'editorlink19' => 'editor19-link',
    'editorlink2' => 'editor2-link',
    'editorlink20' => 'editor20-link',
    'editorlink21' => 'editor21-link',
    'editorlink22' => 'editor22-link',
    'editorlink23' => 'editor23-link',
    'editorlink24' => 'editor24-link',
    'editorlink25' => 'editor25-link',
    'editorlink26' => 'editor26-link',
    'editorlink27' => 'editor27-link',
    'editorlink28' => 'editor28-link',
    'editorlink29' => 'editor29-link',
    'editorlink3' => 'editor3-link',
    'editorlink30' => 'editor30-link',
    'editorlink4' => 'editor4-link',
    'editorlink5' => 'editor5-link',
    'editorlink6' => 'editor6-link',
    'editorlink7' => 'editor7-link',
    'editorlink8' => 'editor8-link',
    'editorlink9' => 'editor9-link',
    'editormask1' => 'editor-mask1',
    'editorn-first' => 'editor2-first',
    'editorn-last' => 'editor2-last',
    'editorn-link' => 'editor2-link',
    'editorn' => 'editor2',
    'editors' => 'editor',
    'editors1' => 'editor1',
    'edizione' => 'edition',
    'eebsite' => 'website',
    'efternamn' => 'last',
    'egile1-lotura' => 'author1-link',
    'EISSN' => 'eissn',
    'elérés' => 'access-date',
    'embargo' => 'pmc-embargo-date',
    'en ligne le acc' =>  'date',
    'encyclopædia' => 'encyclopaedia',
    'encylopedia' => 'encyclopedia',
    'encypoledia' => 'encyclopedia',
    'enlaceautor' => 'author-link',
    'enlaceautor1' => 'author-link1',
    'enlaceautor2' => 'author-link2',
    'enlaceautor3' => 'author-link3',
    'enlaceautor4' => 'author-link4',
    'enlaceroto' => 'url-status',
    'enyclopedia' => 'encyclopedia',
    'episodelink' => 'episode-link',
    'erişimtarihi' => 'access-date',
    'etternavn' => 'last',
    'euthor3' => 'author3',
    'extrait' => 'quote',
    'familiya' => 'last',
    'farst1' => 'first1',
    'fecha' => 'date',
    'fechaacceso' => 'access-date',
    'fechaarchivo' => 'archive-date',
    'file format' => 'format',
    'fiorst4' => 'first4',
    'firast1' => 'first1',
    'firat' => 'first',
    'firest' => 'first',
    'firs' => 'first',
    'firs1' => 'first1',
    'firsst' => 'first',
    'firsst1' => 'first1',
    'firsst2' => 'first2',
    'first 1' => 'first1',
    'first 2' => 'first2',
    'first author' => 'author1',
    'first name' => 'first',
    'first name1' => 'first1',
    'first name2' => 'first2',
    'first-' => 'first',
    'first-1' => 'first1',
    'first-author' => 'first',
    'first-author1' => 'first1',
    'first-author2' => 'first2',
    'first-author3' => 'first3',
    'first-author4' => 'first4',
    'first-author5' => 'first5',
    'first-author6' => 'first6',
    'first-name' => 'first',
    'firstn' => 'first2',
    'firstname' => 'first',
    'firstname1' => 'first1',
    'firstname2' => 'first2',
    'firstname3' => 'first3',
    'firstname4' => 'first4',
    'firstname5' => 'first5',
    'firstname6' => 'first6',
    'firstname7' => 'first7',
    'firstname8' => 'first8',
    'firstname9' => 'first9',
    'firsts' => 'first',
    'firsy' => 'first',
    'firt' => 'first',
    'firt1' => 'first1',
    'firt2' => 'first2',
    'firts' => 'first',
    'firts1' => 'first1',
    'firts2' => 'first2',
    'firts3' => 'first3',
    'fisrt' => 'first',
    'fisrt1' => 'first1',
    'fist' => 'first',
    'fist1' => 'first1',
    'författare' => 'author',
    'format électronique' => 'format',
    'formato' => 'format',
    'fornavn' => 'first',
    'forst' => 'first',
    'frist' => 'first',
    'frst' => 'first',
    'giornale' => 'journal',
    'gtitle' => 'title',
    'hämtår' => 'date',
    'hämtdatum' => 'access-date',
    'hämtmånad' => 'month',
    'handle' => 'hdl',
    'HDL' => 'hdl',
    'họ 1' => 'last1',
    'họ 2' => 'last2',
    'họ 3' => 'last3',
    'họ 4' => 'last4',
    'họ 5' => 'last5',
    'họ 6' => 'last6',
    'họ' => 'last',
    'home' => 'work',
    'homelanguage' => 'language',
    'iarchive-url' => 'archive-url',
    'ibsn' => 'isbn',
    'ibsn2' => 'isbn',
    'idioma' => 'language',
    'ietf-kielikoodi' => 'language',
    'ifirst' => 'first',
    'in url' => 'url',
    'interviewerlink' => 'interviewer-link',
    'interviewermask' => 'interviewer-mask',
    'iqtibos' => 'quote',
    'irl' => 'url',
    'isbn-10' => 'isbn',
    'isbn-13' => 'isbn',
    'ISBN' => 'isbn',
    'ISBN10' => 'isbn',
    'isbn10' => 'isbn',
    'ISBN13' => 'isbn',
    'isbn13' => 'isbn',
    'ism' => 'first',
    'ISMN' => 'ismn',
    'ISSN' => 'issn',
    'isssue' => 'issue',
    'issu' => 'issue',
    'issue date' => 'issue-date',
    'issuee' => 'issue',
    'issues' => 'issue',
    'isue' => 'issue',
    'isuue' => 'issue',
    'itle' => 'title',
    'ittle' => 'title',
    'izdavač' => 'publisher',
    'izena1' => 'first1',
    'izenburua' => 'title',
    'jahrea' => 'date',
    'jastor' => 'jstor',
    'jator' => 'jstor',
    'jazyk' => 'language',
    'język' => 'language',
    'JFM' => 'jfm',
    'jméno' => 'first1',
    'jméno1' => 'first1',
    'jméno2' => 'first2',
    'jméno3' => 'first3',
    'jméno4' => 'first4',
    'jornual' => 'journal',
    'jorunal' => 'journal',
    'jounral' => 'journal',
    'jounralу' => 'journal',
    'jour–nal' => 'journal',
    'jouranl' => 'journal',
    'journa' => 'journal',
    'journals' => 'journal',
    'joutnal' => 'journal',
    'joylashuv' => 'location',
    'jsotr' => 'jstor',
    'jstor-accesss' => 'jstor-access',
    'JSTOR' => 'jstor',
    'juornal' => 'journal',
    'jurnal' => 'journal',
    'kast3' => 'last3',
    'kasutatud' => 'access-date',
    'kiadó' => 'publisher',
    'kirish sanasi' => 'access-date',
    'kpublisher' => 'publisher',
    'l ocation' => 'location',
    'l<nguage' => 'language',
    'laat' => 'last',
    'labng' => 'lang',
    'laccess date' => 'access-date',
    'ladt' => 'last',
    'laest' => 'last',
    'lagnuage' => 'language',
    'laguage' => 'language',
    'lan' => 'lang',
    'langauge' => 'language',
    'langguage' => 'language',
    'langu' => 'lang',
    'langua' => 'language',
    'languafe' => 'language',
    'languag' => 'language',
    'languagen mi' => 'language',
    'languages' => 'language',
    'languange' => 'language',
    'langue' => 'language',
    'languege' => 'language',
    'langugae' => 'language',
    'langugage' => 'language',
    'languge' => 'language',
    'langusge' => 'language',
    'langyage' => 'language',
    'lannguage' => 'language',
    'lanuage' => 'language',
    'lanugage' => 'language',
    'las t' => 'last',
    'lasat' => 'last',
    'lasct' => 'last',
    'lasst1' => 'last1',
    'lasst2' => 'last2',
    'last 1' => 'last1',
    'last 1у' => 'last1',
    'last 2' => 'last2',
    'last 3' => 'last3',
    'last name' => 'last',
    'last name1' => 'last1',
    'last name2' => 'last2',
    'last-1' => 'last1',
    'last-author' => 'last',
    'last-author1' => 'last1',
    'last-author2' => 'last2',
    'last-author3' => 'last3',
    'last-author4' => 'last4',
    'last-author5' => 'last5',
    'last-author6' => 'last6',
    'last-name' => 'last',
    'last[[' => 'last',
    'laste' => 'last',
    'lastn' => 'last2',
    'lastname' => 'last',
    'lastname1' => 'last1',
    'lastname2' => 'last2',
    'lastname3' => 'last3',
    'lastname4' => 'last4',
    'lastname5' => 'last5',
    'lastname6' => 'last6',
    'lastname7' => 'last7',
    'lastname8' => 'last8',
    'lastname9' => 'last9',
    'lastr' => 'last',
    'lasts' => 'last',
    'lat' => 'last',
    'lat1' => 'last1',
    'lats1' => 'last1',
    'laydate' => 'lay-date',
    'laysource' => 'lay-source',
    'layurl' => 'lay-url',
    'LCCN' => 'lccn',
    'lien auteur' => 'author-link',
    'lien auteur1' => 'author1-link',
    'lien auteur2' => 'author2-link',
    'lien auteur3' => 'author3-link',
    'lien auteur4' => 'author4-link',
    'lien auteur5' => 'author5-link',
    'lien auteur6' => 'author6-link',
    'lien auteur7' => 'author7-link',
    'lien auteur8' => 'author8-link',
    'lien auteur9' => 'author9-link',
    'lieu' => 'location',
    'limbă' => 'language',
    'lingua' => 'language',
    'língua' => 'language',
    'linguage' => 'language',
    'link to author' => 'author-link',
    'link' => 'url',
    'lire en ligne' => 'url',
    'lisans' => 'degree',
    'llanguage' => 'language',
    'lng' => 'lang',
    'locaiton' => 'location',
    'local' => 'location',
    'locatio' => 'location',
    'locationm' => 'location',
    'locations' => 'location',
    'locato in' => 'location',
    'locstion' => 'location',
    'lofcation' => 'location',
    'lornguage' => 'language',
    'lsat' => 'last',
    'lsat2' => 'last2',
    'lsat3' => 'last3',
    'lsnguage' => 'language',
    'lsst2' => 'last2',
    'lst' => 'last',
    'lst1' => 'last1',
    'luku' => 'issue',
    'lxast' => 'last',
    'magazibe' => 'magazine',
    'magazinee' => 'magazine',
    'magazins' => 'magazine',
    'mailinglist' => 'mailing-list',
    'mapurl' => 'map-url',
    'medförfattare' => 'coauthors',
    'miejsce' => 'location',
    'místo' => 'location',
    'mohth' => 'month',
    'mpid' => 'pmid',
    'MR' => 'mr',
    'muharrir-havola' => 'editor-link',
    'muharrir' => 'editor',
    'năm' => 'date',
    'name' => 'author',
    'name1' => 'author1',
    'name2' => 'author2',
    'name3' => 'author3',
    'nashriyot' => 'publisher',
    'nedostupné' => 'deadurl',
    'nespaper' => 'newspaper',
    'newpaper' => 'newspaper',
    'newpspaer' => 'newspaper',
    'newspapers' => 'newspaper',
    'ngày lưu trữ' => 'archive-date',
    'ngày tháng' => 'date',
    'ngày truy cập' => 'access-date',
    'ngày' => 'date',
    'ngôn ngữ' => 'language',
    'nhà xuất bản' => 'publisher',
    'nimike' => 'title',
    'no-cat' => 'no-tracking',
    'No.' => 'issue',
    'No' => 'issue',
    'no' => 'issue',
    'nocat' => 'no-tracking',
    'nơi xuất bản' => 'location',
    'nơi' => 'location',
    'nom' => 'first',
    'nom1' => 'last1',
    'nom2' => 'last2',
    'nom3' => 'last3',
    'nom4' => 'last4',
    'nom5' => 'last5',
    'nom6' => 'last6',
    'nombre' => 'first',
    'nombre1' => 'first1',
    'nombre2' => 'first2',
    'nombre3' => 'first3',
    'nome' => 'first',
    'nome1' => 'first1',
    'nome2' => 'first2',
    'nome3' => 'first3',
    'nopp' => 'no-pp',
    'notestitle' => 'chapter',
    'notracking' => 'no-tracking',
    'număr' => 'issue',
    'nume' => 'author',
    'numero' => 'issue',
    'numéro' => 'issue',
    'número' => 'issue',
    'numver' => 'number',
    'nurl' => 'url',
    'obra' => 'work',
    'OCLC' => 'oclc',
    'ocls' => 'oclc',
    'odkaz na autora' => 'author-link',
    'odkaz na titul' => 'title-link',
    'OL' => 'ol',
    'ölüurl' => 'deadurl',
    'opublikowany' => 'website',
    'opublisher' => 'publisher',
    'orig_date' => 'orig-date',
    'origdate' => 'orig-date',
    'origina-year' => 'orig-year',
    'original-date' => 'orig-date',
    'origmonth' => 'month',
    'origyea' => 'orig-year',
    'origyear' => 'orig-date',
    'oriyear-' => 'orig-date',
    'ort' => 'location',
    'OSTI' => 'osti',
    'other' => 'others',
    'otitle' => 'title',
    'oublisher' => 'publisher',
    'ourl' => 'url',
    'ournal' => 'journal',
    'oy' => 'month',
    'oyblisher' => 'publisher',
    'p.' => 'page',
    'p' => 'page',
    'paage' => 'page',
    'paes' => 'pages',
    'page number' => 'page',
    'pagesl' => 'pages',
    'pagina' => 'page',
    'página' => 'page',
    'pagină' => 'pages',
    'pagina\'s' => 'pages',
    'páginas' => 'pages',
    'pagine' => 'pages',
    'pàgines' => 'pages',
    'pagrd' => 'pages',
    'pags' => 'page',
    'pagse' => 'page',
    'part' => 'issue',
    'pases' => 'pages',
    'pasge' => 'page',
    'passage' => 'pages',
    'path' => 'url',
    'páxina-web' => 'website',
    'pbulisher' => 'publisher',
    'pealkiri' => 'title',
    'periodico' => 'magazine',
    'periodikum' => 'periodical',
    'pg' => 'page',
    'pinlisher' => 'publisher',
    'piublisher' => 'publisher',
    'pkace' => 'place',
    'place of publication' => 'publication-place',
    'plast' => 'last',
    'PMC' => 'pmc',
    'pmcid' => 'pmc',
    'pmdi' => 'pmid',
    'PMID' => 'pmid',
    'pmpmid' => 'pmid',
    'pp.' => 'pages',
    'pp' => 'pages',
    'prénom1' => 'first1',
    'prénom2' => 'first2',
    'prénom3' => 'first3',
    'prénom4' => 'first4',
    'prénom5' => 'first5',
    'prénom6' => 'first6',
    'prenume' => 'first',
    'présentation en ligne' => 'url',
    'příjmení' => 'last1',
    'příjmení1' => 'last1',
    'příjmení2' => 'last2',
    'příjmení3' => 'last3',
    'příjmení4' => 'last4',
    'primeiro' => 'first1',
    'primeiro1' => 'first1',
    'primeiro10' => 'first10',
    'primeiro2' => 'first2',
    'primeiro3' => 'first3',
    'primeiro4' => 'first4',
    'primeiro5' => 'first5',
    'primeiro6' => 'first6',
    'primeiro7' => 'first7',
    'primeiro8' => 'first8',
    'primeiro9' => 'first8',
    'primero' => 'first',
    'primero1' => 'first1',
    'primero2' => 'first2',
    'primero3' => 'first3',
    'printer' => 'publisher',
    'pristupdatum' => 'access-date',
    'pub;isher' => 'publisher',
    'pubblicazione' => 'magazine',
    'pubblisher' => 'publisher',
    'pubilsher' => 'publisher',
    'pubisher' => 'publisher',
    'publicació' => 'work',
    'publicación' => 'journal',
    'publicado' => 'publisher',
    'publication date' => 'publication-date',
    'publication-year' => 'publication-date',
    'publication' => 'work',
    'publicationdate' => 'publication-date',
    'publicationplace' => 'publication-place',
    'publicator' => 'publisher',
    'publicher' => 'publisher',
    'publiher' => 'publisher',
    'publihser' => 'publisher',
    'publilsher' => 'publisher',
    'publioser' => 'publisher',
    'publisehr' => 'publisher',
    'publiser' => 'publisher',
    'publish-date' => 'date',
    'publish' => 'publisher',
    'publishe' => 'publisher',
    'published date' => 'publication-date',
    'published-date' => 'publication-date',
    'publishee' => 'publisher',
    'publishel' => 'publisher',
    'publisherc' => 'publisher',
    'publishere' => 'publisher',
    'publisherg' => 'publisher',
    'publisherid' => 'id',
    'publishers' => 'publisher',
    'publishier' => 'publisher',
    'publishing' => 'publisher',
    'publishr' => 'publisher',
    'publishuer' => 'publisher',
    'publisjer' => 'publisher',
    'publisjjer' => 'publisher',
    'publlisher' => 'publisher',
    'publosher' => 'publisher',
    'publsher' => 'publisher',
    'publsiher' => 'publisher',
    'publusher' => 'publisher',
    'pubslisher' => 'publisher',
    'puisher' => 'publisher',
    'pulbisher' => 'publisher',
    'pulisher' => 'publisher',
    'punlisher' => 'publisher',
    'puntofinale' => 'postscript',
    'puplisher' => 'publisher',
    'purl' => 'url',
    'puvlisher' => 'publisher',
    'qoute' => 'quote',
    'quot' => 'quote',
    'rchive-date' => 'archive-date',
    'rchive-url' => 'archive-url',
    'read online' => 'access-date',
    'replaced série' => 'series',
    'retrieval' => 'access-date',
    'retrieve' => 'access-date',
    'retrieved date' => 'access-date',
    'retrieved on' => 'access-date',
    'retrieved' => 'access-date',
    'RFC' => 'rfc',
    'rivista' => 'magazine',
    'rok' => 'date',
    'rozdział' => 'chapter',
    'rpubllisher' => 'publisher',
    'rtitle' => 'title',
    'rubrik' => 'title',
    'rul' => 'url',
    'S2CID' => 's2cid',
    'saccessdate' => 'access-date',
    'sahifalar' => 'pages',
    'sana' => 'date',
    'şanguage' => 'language',
    'sarlavha' => 'title',
    'sate' => 'date',
    'sayfalar' => 'pages',
    'sayı' => 'issue',
    'SBN' => 'sbn',
    'sccess-date' => 'access-date',
    'scritp-title' => 'script-title',
    'search date' => 'access-date',
    'sectionurl' => 'section-url',
    'seria' => 'series',
    'serie' => 'series',
    'serieslink' => 'series-link',
    'seriesno' => 'series-no',
    'seriestitle' => 'series',
    'shapter' => 'chapter',
    'site name' => 'website',
    'site web' => 'website',
    'site' => 'website',
    'siteweb' => 'website',
    'sitioweb' => 'website',
    'sito' => 'website',
    'sınıf' => 'class',
    'source-date' => 'date',
    'soyadı' => 'last',
    'soyadı1' => 'last1',
    'sprache' => 'language',
    'språk' => 'language',
    'SSRN' => 'ssrn',
    'strany' => 'page',
    'subjectlink' => 'subject-link',
    'subjectlink1' => 'subject-link1',
    'surnames' => 'surname',
    'suthor-link' => 'author-link',
    'swebsite' => 'website',
    't itle' => 'title',
    'tác giả 1' => 'author1',
    'tác giả 2' => 'author2',
    'tác giả 3' => 'author3',
    'tác giả' => 'author',
    'tarih' => 'date',
    'tarns-title' => 'trans-title',
    'tauthor2' => 'author2',
    'tear' => 'date',
    'tên 1' => 'first1',
    'tên 2' => 'first2',
    'tên 3' => 'first3',
    'tên 4' => 'first4',
    'tên 5' => 'first5',
    'tên 6' => 'first6',
    'tên' => 'first',
    'text' => 'quote',
    'tidning' => 'newspaper',
    'tidskrift' => 'journal',
    'tiêu đề' => 'title',
    'tiitle' => 'title',
    'til' => 'language',
    'tilte' => 'title',
    'timecaption' => 'time-caption',
    'tipo' => 'type',
    'tite' => 'title',
    'titel' => 'title',
    'titke' => 'title',
    'titl' => 'title',
    'title chapter' => 'chapter',
    'title-chapter' => 'chapter',
    'title-lik' => 'title-link',
    'title-url' => 'url',
    'títle' => 'title',
    'title>' => 'title',
    'titleer' => 'title',
    'titlelink' => 'title-link',
    'titlepublisher' => 'publisher',
    'titles' => 'title',
    'titleurl' => 'url',
    'titley' => 'title',
    'titleyear' => 'orig-year',
    'titlte' => 'title',
    'titlu' => 'title',
    'títol' => 'title',
    'titolo' => 'title',
    'titre chapitre' => 'chapter',
    'titre ouvrage' => 'work',
    'titre' => 'title',
    'tittel' => 'title',
    'tittle' => 'title',
    'titul' => 'title',
    'titule' => 'title',
    'titulo' => 'title',
    'título' => 'title',
    'titulotrad' => 'trans-title',
    'titле' => 'title',
    'tlast2' => 'last2',
    'tltle' => 'title',
    'totle' => 'title',
    'trabns-title' => 'trans-title',
    'traducteur' => 'translator',
    'traductor' => 'translator',
    'trancslate-title' => 'trans-article',
    'trans_chapter' => 'trans-chapter',
    'trans_title' => 'trans-title',
    'trans-script-title' => 'script-title',
    'trans-tile' => 'trans-title',
    'trans-tite' => 'trans-title',
    'trans-titl' => 'trans-title',
    'trans-titles' => 'trans-title',
    'trans-ttle' => 'trans-title',
    'transa-title' => 'trans-title',
    'transcripturl' => 'transcript-url',
    'translate-title'  => 'trans-title',
    'translate' => 'translator',
    'translated title' => 'trans-title',
    'translated-title' => 'trans-title',
    'translators' => 'translator',
    'translit-title' => 'trans-title',
    'translòator-first' => 'translator-first',
    'transtitle' => 'trans-title',
    'ttile' => 'title',
    'ttle' => 'title',
    'tựa đề' => 'title',
    'tytle' => 'title',
    'tytuł' => 'title',
    'u rl-status' => 'url-status',
    'ubicación' => 'location',
    'ưebsite' => 'website',
    'uel' => 'url',
    'ul-status' => 'url-status',
    'ulr' => 'url',
    'último' => 'last1',
    'último1' => 'last1',
    'último10' => 'last10',
    'último2' => 'last2',
    'último3' => 'last3',
    'último4' => 'last4',
    'último5' => 'last5',
    'último6' => 'last6',
    'último7' => 'last7',
    'último8' => 'last8',
    'último9' => 'last9',
    'ur l' => 'url',
    'urel' => 'url',
    'urk' => 'url',
    'urkl' => 'url',
    'url -status' => 'url-status',
    'url access date' => 'access-date',
    'url archivu' => 'archive-url',
    'url lưu trữ' => 'archive-url',
    'url of archive' => 'archive-url',
    'url status' => 'url-status',
    'url_archive' => 'archive-url',
    'url- access' => 'url-access',
    'url- status' => 'url-status',
    'url-access-date' => 'access-date',
    'url-archive' => 'archive-url',
    'url-arquivo' => 'archive-url',
    'url-morta' => 'url-status',
    'url-mstatus' => 'url-status',
    'url-olek' => 'url-status',
    'url-satus' => 'url-status',
    'url-staqtus' => 'url-status',
    'url-stastus' => 'url-status',
    'url-state' => 'url-status',
    'url-stats' => 'url-status',
    'url-statu' => 'url-status',
    'url-status-' => 'url-status',
    'url-statuss' => 'url-status',
    'url-staus' => 'url-status',
    'url-stauts' => 'url-status',
    'url-sttaus' => 'url-status',
    'url-tatus' => 'url-status',
    'url-архіву' => 'archive-url',
    'url;' => 'url',
    'URL' => 'url',
    'urlarchive' => 'archive-url',
    'urlarchivio' => 'archive-url',
    'urlarchivo' => 'archive-url',
    'urlarquivo' => 'archive-url',
    'urlfile' => 'archive-url',
    'urll' => 'url',
    'urlmorta' => 'deadurl',
    'urlmorto' => 'url-status',
    'urlmuerta' => 'url-status',
    'urlstatus' => 'url-status',
    'urn' => 'url',
    'urstatus' => 'url-status',
    'urtea' => 'date',
    'utgivare' => 'publisher',
    'uyrl' => 'url',
    'v authors' => 'vauthors',
    'vaadatud' => 'access-date',
    'väljaandja' => 'publisher',
    'väljaanne' => 'work',
    'vauthoes' => 'vauthors',
    'vauthros' => 'vauthors',
    'vebsayt' => 'website',
    'viay' => 'via',
    'ville' => 'location',
    'visit date' => 'access-date',
    'visiteddate' => 'access-date',
    'vlume' => 'volume',
    'Vol.' => 'volume',
    'Vol' => 'volume',
    'vol' => 'volume',
    'volumeas' => 'volume',
    'volumen' => 'volume',
    'volumes' => 'volume',
    'volumn' => 'volume',
    'vydanie' => 'edition',
    'vydavatel' => 'publisher',
    'w ebsite' => 'website',
    'wark' => 'work',
    'wbesite' => 'website',
    'wbsite' => 'website',
    'we site' => 'website',
    'web site' => 'website',
    'web url' => 'url',
    'webaite' => 'website',
    'webasite' => 'website',
    'webbsite' => 'website',
    'webcite' => 'website',
    'webebsite' => 'website',
    'webiste' => 'website',
    'webite' => 'website',
    'webse' => 'website',
    'websie' => 'website',
    'websiet' => 'website',
    'websife' => 'website',
    'websinte' => 'website',
    'websiote' => 'website',
    'websire' => 'website',
    'websit' => 'website',
    'website l' => 'website',
    'website name' => 'website',
    'website to' => 'website',
    'websiteh' => 'website',
    'websitel' => 'website',
    'websiten' => 'website',
    'websiter' => 'website',
    'websites' => 'website',
    'websitet' => 'website',
    'websitew' => 'website',
    'websitre' => 'website',
    'websitte' => 'website',
    'websitw' => 'website',
    'websitу' => 'website',
    'websote' => 'website',
    'webste' => 'website',
    'webstie' => 'website',
    'websute' => 'website',
    'wecite' => 'website',
    'weebsite' => 'website',
    'weork' => 'work',
    'werk' => 'work',
    'wesbite' => 'website',
    'wesite' => 'website',
    'wevsite' => 'website',
    'wia' => 'via',
    'wkautore' => 'author-link',
    'wkautore1' => 'author-link1',
    'wkautore2' => 'author-link2',
    'wkautore3' => 'author-link3',
    'woek' => 'work',
    'wok' => 'work',
    'wor' => 'work',
    'works' => 'work',
    'worl' => 'work',
    'wotk' => 'work',
    'wprk' => 'work',
    'writer' => 'author',
    'wrk' => 'work',
    'wrok' => 'work',
    'wslanguage' => 'language',
    'wwbsite' => 'website',
    'wwebsite' => 'website',
    'wydanie' => 'issue',
    'wydawca' => 'publisher',
    'xhapter' => 'chapter',
    'yayıncı' => 'publisher',
    'ye ar' => 'date',
    'yeae' => 'date',
    'year of publication' => 'publication-date',
    'year of release' => 'date',
    'year_published' => 'date',
    'year.' => 'date',
    'year1' => 'date',
    'years' => 'date',
    'yeat' => 'date',
    'yeay' => 'date',
    'yil' => 'date',
    'yıl' => 'date',
    'ZBL' => 'zbl',
    'zugriff' => 'access-date',
    'γλώσσα' => 'language',
    'ημερομηνία' => 'date',
    'τίτλος' => 'title',
    'аrchiveurl' => 'archive-url',
    'аuthor' => 'author',
    'автор-посилання' => 'author-link',
    'автор-посилання1' => 'author-link1',
    'автор-посилання2' => 'author-link2',
    'автор-посилання3' => 'author-link3',
    'автор-посилання4' => 'author-link4',
    'автор' => 'author',
    'архив дата' => 'archive-date',
    'архив' => 'archive-url',
    'архива-url' => 'archive-url',
    'веб-сайт' => 'website',
    'веб-страница' => 'website',
    'вебсайт' => 'website',
    'видавець' => 'publisher',
    'год' => 'date',
    'град' => 'location',
    'дата доступа' => 'access-date',
    'дата-архіву' => 'archive-date',
    'дата-доступу' => 'access-date',
    'дата' => 'date',
    'датум' => 'date',
    'доступ -date' => 'access-date',
    'журнал' => 'magazine',
    'заглавие' => 'title',
    'издавач' => 'publisher',
    'издание' => 'edition',
    'издатель' => 'publisher',
    'издательство' => 'publisher',
    'ім\'я' => 'first',
    'ім\'я1' => 'first1',
    'ім\'я2' => 'first2',
    'ім\'я3' => 'first3',
    'ім\'я4' => 'first4',
    'јазик' => 'language',
    'локација' => 'location',
    'мертвий-url' => 'deadurl',
    'место' => 'location',
    'мова' => 'language',
    'мовою' => 'language',
    'назва' => 'author',
    'наслов' => 'title',
    'номер' => 'issue',
    'поглавје' => 'chapter',
    'Приступљено' => 'access-date',
    'приступњено' => 'access-date',
    'прізвище' => 'last',
    'прізвище1' => 'last1',
    'прізвище2' => 'last2',
    'прізвище3' => 'last3',
    'прізвище4' => 'last4',
    'рік' => 'date',
    'розміщення' => 'date',
    'соавторы' => 'coauthors',
    'ссылка часть' => 'chapter-url',
    'ссылка' => 'url',
    'сторінки' => 'pages',
    'страниц' => 'page',
    'страници' => 'pages',
    'страницы' => 'pages',
    'том' => 'volume',
    'часть' => 'chapter',
    'язык' => 'language',
    'אתר' => 'website',
    'כותרת' => 'title',
    'תאריך' => 'date',
    'الأخير' => 'last1',
    'بەرواری دەستگەیشتن' => 'access-date',
    'پیوند بایگانی' => 'archive-url',
    'پیوند' => 'url',
    'تاريخ أرشيف' => 'archive-date',
    'تاريخ الوصول' => 'access-date',
    'تاريخ-الأرشيف' => 'archive-date',
    'تاريخ-الوصول' => 'access-date',
    'تاريخ' => 'date',
    'تاریخ بازبینی' => 'access-date',
    'تاریخ بازدید' => 'access-date',
    'تاریخ' => 'date',
    'حالة المسار' => 'url-status',
    'دوره' => 'volume',
    'زبان' => 'language',
    'زمان' => 'language',
    'ڕۆژنامە' => 'newspaper',
    'ژورنال' => 'journal',
    'سال' => 'date',
    'شماره' => 'issue',
    'صحيفة' => 'newspaper',
    'عنوان' => 'work',
    'کۆتا' => 'last',
    'لغة' => 'language',
    'مسار أرشيف' => 'archive-url',
    'مسار-الأرشيف' => 'archive-url',
    'مسار' => 'url',
    'موقع' => 'location',
    'نام خانوادگی' => 'last',
    'نام خانوادگی۱' => 'last1',
    'نام' => 'first',
    'نام۱' => 'first1',
    'نویسنده' => 'author',
    'یەکەم' => 'first',
    'আইএসবিএন' => 'isbn',
    'আর্কাইভের-url' => 'archive-url',
    'আর্কাইভের-তারিখ' => 'archive-date',
    'ইউআরএল-অবস্থা' => 'url-status',
    'পাতাসমূহ' => 'pages',
    'প্রকাশক' => 'publisher',
    'ভাষা' => 'language',
    'শেষাংশ' => 'last',
    'সংগ্রহের-date' => 'access-date',
    'সংগ্রহের-তারিখ' => 'access-date',
    'সংস্করণ' => 'edition',
    'സ്റ്റേ' => 'date',
    '날짜' => 'date',
    '보존url' => 'archive-url',
    '보존날짜' => 'archive-date',
    '성' => 'last',
    '언어' => 'language',
    '웹사이트' => 'website',
    '이름' => 'author',
    '저자' => 'author',
    '제목' => 'title',
    '출판사' => 'publisher',
    '확인날짜' => 'access-date',
];

const COMMON_MISTAKES_TOOL = [
    'accessdate' => 'access-date',
    'archivedate' => 'archive-date',
    'archiveurl' => 'archive-url',
    'authorlink' => 'author-link',
];

    // Find these with this on all the various types https://en.wikipedia.org/w/index.php?title=Special:WhatLinksHere/Template:Citation&hidelinks=1&hidetrans=1
const TEMPLATE_CONVERSIONS = [
    ['cite', 'citation'],
    ['Cite', 'Citation'],
    ['citebook', 'cite book'],
    ['Citebook', 'Cite book'],
    ['cit book', 'cite book'],
    ['Cit book', 'Cite book'],
    ['cite ebook', 'cite book'],
    ['Cite ebook', 'Cite book'],
    ['cite books', 'cite book'],
    ['Cite books', 'Cite book'],
    ['book reference', 'cite book'],
    ['Book reference', 'Cite book'],
    ['web reference', 'cite web'],
    ['Web reference', 'Cite web'],
    ['Conference reference', 'Cite conference'],
    ['conference reference', 'cite conference'],
    ['citejournal', 'cite journal'],
    ['Citejournal', 'Cite journal'],
    ['citeweb', 'cite web'],
    ['Citeweb', 'Cite web'],
    ['cite-web', 'cite web'],
    ['Cite-web', 'Cite web'],
    ['cit web', 'cite web'],
    ['Cit web', 'Cite web'],
    ['cit journal', 'cite journal'],
    ['Cit journal', 'Cite journal'],
    ['cit news', 'cite news'],
    ['Cit news', 'Cite news'],
    ['cite url', 'cite web'],
    ['Cite url', 'Cite web'],
    ['web cite', 'cite web'],
    ['Web cite', 'Cite web'],
    ['book cite', 'cite book'],
    ['Book cite', 'Cite book'],
    ['cite-book', 'cite book'],
    ['Cite-book', 'Cite book'],
    ['citenews', 'cite news'],
    ['Citenews', 'Cite news'],
    ['cite-news', 'cite news'],
    ['Cite-news', 'Cite news'],
    ['citepaper', 'cite paper'],
    ['Citepaper', 'Cite paper'],
    ['cite chapter', 'cite book'],
    ['Cite chapter', 'Cite book'],
    ['citation journal', 'cite journal'],
    ['Citation journal', 'Cite journal'],
    ['cite new', 'cite news'],
    ['Cite new', 'Cite news'],
    ['cite newspaper', 'cite news'],
    ['Cite newspaper', 'Cite news'],
    ['cite Web', 'cite web'],
    ['Cite Web', 'Cite web'],
    ['cite media', 'cite AV media'],
    ['Cite media', 'Cite AV media'],
    ['cite av media', 'cite AV media'],
    ['Cite av media', 'Cite AV media'],
    ['cite Journal', 'cite journal'],
    ['Cite Journal', 'Cite journal'],
    ['cite Book', 'cite book'],
    ['Cite Book', 'Cite book'],
    ['cite News', 'cite news'],
    ['Cite News', 'Cite news'],
    ['cite citation', 'citation'],
    ['Cite citation', 'Citation'],
    ['Cite n', 'Cite news'],
    ['cite n', 'cite news'],
    ['Citation news', 'Cite news'],
    ['citation news', 'cite news'],
    ['C news', 'Cite news'],
    ['c news', 'cite news'],
    ['Cute news', 'Cite news'],
    ['cute news', 'cite news'],
    ['Cite news2', 'Cite news'],
    ['cite news2', 'cite news'],
    ['Citar notícia', 'Cite news'],
    ['citar notícia', 'cite news'],
    ['뉴스 인용', 'Cite news'],
    ['Cite study', 'Citation'],
    ['cite study', 'citation'],
    ['Vcite2 journal', 'Cite journal'],
    ['vcite2 journal', 'cite journal'],
    ['Web link', 'Cite web'],
    ['web link', 'cite web'],
    ['Citweb', 'Cite web'],
    ['citweb', 'cite web'],
    ['Citat web', 'Cite web'],
    ['citat web', 'cite web'],
    ['Cite we', 'Cite web'],
    ['cite we', 'cite web'],
    ['Cite w', 'Cite web'],
    ['cite w', 'cite web'],
    ['Cite wb', 'Cite web'],
    ['cite wb', 'cite web'],
    ['Cite web.', 'Cite web'],
    ['cite web.', 'cite web'],
    ['Cw', 'Cite web'],
    ['cw', 'cite web'],
    ['C web', 'Cite web'],
    ['c web', 'cite web'],
    ['Cita web', 'Cite web'],
    ['cita web', 'cite web'],
    ['Cite webpage', 'Cite web'],
    ['cite webpage', 'cite web'],
    ['Weblink', 'Cite web'],
    ['weblink', 'cite web'],
    ['Cite blog', 'Cite web'],
    ['cite blog', 'cite web'],
    ['Web citation', 'Cite web'],
    ['web citation', 'cite web'],
    ['Cite website', 'Cite web'],
    ['cite website', 'cite web'],
    ['Cite page', 'Cite book'],
    ['cite page', 'cite book'],
    ['Cite publication', 'Cite book'],
    ['cite publication', 'cite book'],
    ['Citeencyclopedia', 'Cite encyclopedia'],
    ['citeencyclopedia', 'cite encyclopedia'],
    ['Encyclopedia', 'Cite encyclopedia'],
    ['encyclopedia', 'cite encyclopedia'],
//    ['Cite contribution', 'Cite encyclopedia'],
//    ['cite contribution', 'cite encyclopedia'],
    ['Cita pubblicazione', 'Cite journal'],
    ['cita pubblicazione', 'cite journal'],
    ['Citace elektronické monografie', 'Cite web'],
    ['citace elektronické monografie', 'cite web'],
    ['Chú thích web', 'Cite web'],
    ['Chú thích báo', 'Cite news'],
    ['chú thích web', 'cite web'],
    ['chú thích báo', 'cite news'],
    ['tidskriftsref', 'cite journal'],
    ['Tidskriftsref', 'Cite journal'],
    ['Tidningsref', 'Cite news'],
    ['tidningsref', 'cite news'],
    ['GroveOnline', 'Cite Grove'],
    ['Groveonline', 'Cite Grove'],
    ['groveOnline', 'Cite Grove'],
    ['groveonline', 'Cite Grove'],
    ['NewGrove1980', 'Cite NewGrove1980'],
    ['newGrove1980', 'Cite NewGrove1980'],
    ['citar livro', 'cite book'],
    ['Citar livro', 'Cite book'],
    ['Citace monografie', 'cite book'],
    ['citace monografie', 'Cite book'],
    ['Bokref', 'cite book'],
    ['bokref', 'Cite book'],
    ['Cite press', 'Cite press release'],
    ['cite press', 'cite press release'],
    ['cite media', 'cite AV media'],
    ['Cite media', 'Cite AV media'],
    ['cite audio', 'cite AV media'],
    ['Cite audio', 'Cite AV media'],
    ['vcite video', 'cite AV media'],
    ['Vcite video', 'Cite AV media'],
    ['cite music video', 'cite AV media'],
    ['Cite music video', 'Cite AV media'],
    ['cite visual', 'cite AV media'],
    ['Cite visual', 'Cite AV media'],
    ['cite cd', 'cite AV media'],
    ['Cite cd', 'Cite AV media'],
    ['citevideo', 'cite AV media'],
    ['Citevideo', 'Cite AV media'],
    ['cite AV Media', 'cite AV media'],
    ['Cite AV Media', 'Cite AV media'],
    ['cite song', 'cite AV media'],
    ['Cite song', 'Cite AV media'],
    ['cite AVMedia', 'cite AV media'],
    ['Cite AVMedia', 'Cite AV media'],
    ['cita víde', 'cite AV media'],
    ['Cita víde', 'Cite AV media'],
    ['cite Youtube', 'cite AV media'],
    ['Cite Youtube', 'Cite AV media'],
    ['cite AV', 'cite AV media'],
    ['Cite AV', 'Cite AV media'],
    ['cite YouTube', 'cite AV media'],
    ['Cite YouTube', 'Cite AV media'],
    ['cite documentary', 'cite AV media'],
    ['Cite documentary', 'Cite AV media'],
    ['cite film', 'cite AV media'],
    ['Cite film', 'Cite AV media'],
    ['cite movie', 'cite AV media'],
    ['Cite movie', 'Cite AV media'],
    ['cite dvd', 'cite AV media'],
    ['Cite dvd', 'Cite AV media'],
    ['cite DVD', 'cite AV media'],
    ['Cite DVD', 'Cite AV media'],
    ['cite image', 'cite AV media'],
    ['Cite image', 'Cite AV media'],
    ['cite radio', 'cite AV media'],
    ['Cite radio', 'Cite AV media'],
    ['cite movie', 'cite AV media'],
    ['Cite movie', 'Cite AV media'],
    ['Vcite press release', 'Cite press release'],
    ['vcite press release', 'cite press release'],
    ['Cite media release', 'Cite press release'],
    ['cite media release', 'cite press release'],
    ['Cite press-release', 'Cite press release'],
    ['cite press-release', 'cite press release'],
    ['Cite pr', 'Cite press release'],
    ['cite pr', 'cite press release'],
    ['Cite news release', 'Cite press release'],
    ['cite news release', 'cite press release'],
    ['Cite Press release', 'Cite press release'],
    ['cite Press release', 'cite press release'],
    ['Cite press release.', 'Cite press release'],
    ['cite press release.', 'cite press release'],
    ['Cite pressrelease', 'Cite press release'],
    ['cite pressrelease', 'cite press release'],
    ['Cite standard', 'Cite tech report'],
    ['cite standard', 'cite tech report'],
    ['Cite technical report', 'Cite tech report'],
    ['cite technical report', 'cite tech report'],
    ['Cite techreport', 'Cite tech report'],
    ['cite techreport', 'cite tech report'],
    ['Techrep reference', 'Cite tech report'],
    ['techrep reference', 'cite tech report'],
    ['Cite abstract', 'Cite journal'],
    ['cite abstract', 'cite journal'],
    ['Cytuj_pismo', 'Cite journal'],
    ['cytuj_pismo', 'cite journal'],
    ['Citace periodika', 'Cite journal'],
    ['citace periodika', 'cite journal'],
    ['Cite dissertation', 'Cite thesis'],
    ['cite dissertation', 'cite thesis'],
    ['Citar tese', 'Cite thesis'],
    ['citar tese', 'cite thesis'],
    ['Cite ssrn', 'Cite SSRN'],
    ['cite ssrn', 'cite SSRN'],
    ['Cite plaque', 'Cite sign'],
    ['cite plaque', 'cite sign'],
    ['Cite usenet', 'Cite newsgroup'],
    ['cite usenet', 'cite newsgroup'],
    ['Cite Usenet', 'Cite newsgroup'],
    ['cite Usenet', 'cite newsgroup'],
    ['Navedi novice', 'Cite news'],
    ['navedi novice', 'cite news'],
    ['Cite maps', 'Cite map'],
    ['cite maps', 'cite map'],
    ['Cite biorxiv', 'Cite bioRxiv'],
    ['cite biorxiv', 'cite bioRxiv'],
    ['Cite list', 'Cite mailing list'],
    ['cite list', 'cite mailing list'],
    ['Cite mailinglist', 'Cite mailing list'],
    ['cite mailinglist', 'cite mailing list'],
    ['Cite ArXiv', 'Cite arXiv'],
    ['cite ArXiv', 'cite arXiv'],
    ['Cite arxiv', 'Cite arXiv'],
    ['cite arxiv', 'cite arXiv'],
    ['Cite av media notes', 'Cite AV media notes'],
    ['cite av media notes', 'cite AV media notes'],
    ['Cite DVD-notes', 'Cite AV media notes'],
    ['cite DVD-notes', 'cite AV media notes'],
    ['Cite album notes', 'Cite AV media notes'],
    ['cite album notes', 'cite AV media notes'],
    ['Cite album-notes', 'Cite AV media notes'],
    ['cite album-notes', 'cite AV media notes'],
    ['Liner notes', 'Cite AV media notes'],
    ['liner notes', 'cite AV media notes'],
    ['Cite liner notes', 'Cite AV media notes'],
    ['cite liner notes', 'cite AV media notes'],
    ['Vcite album-notes', 'Cite AV media notes'],
    ['vcite album-notes', 'cite AV media notes'],
    ['Cite music release notes', 'Cite AV media notes'],
    ['cite music release notes', 'cite AV media notes'],
    ['Cite dvd-notes', 'Cite AV media notes'],
    ['cite dvd-notes', 'cite AV media notes'],
    ['Cite DVD notes', 'Cite AV media notes'],
    ['cite DVD notes', 'cite AV media notes'],
    ['Cite citeseerx', 'Cite CiteSeerX'],
    ['cite citeseerx', 'cite CiteSeerX'],
    ['Cite citeseer', 'Cite CiteSeerX'],
    ['cite citeseer', 'cite CiteSeerX'],
    ['Cite CiteSeer', 'Cite CiteSeerX'],
    ['cite CiteSeer', 'cite CiteSeerX'],
    ['Cite proceedings', 'Cite conference'],
    ['cite proceedings', 'cite conference'],
    ['Cite presentation', 'Cite conference'],
    ['cite presentation', 'cite conference'],
    ['Cite mag', 'Cite magazine'],
    ['cite mag', 'cite magazine'],
    ['Cite magazine article', 'Cite magazine'],
    ['cite magazine article', 'cite magazine'],
    ['Cite Magazine', 'Cite magazine'],
    ['cite Magazine', 'cite magazine'],
    ['Cite show', 'Cite episode'],
    ['cite show', 'cite episode'],
    ['Vcite episode', 'Cite episode'],
    ['vcite episode', 'cite episode'],
    ['Vancite episode', 'Cite episode'],
    ['vancite episode', 'cite episode'],
    ['Cite Episode', 'Cite episode'],
    ['cite Episode', 'cite episode'],
    ['Cite encyclopædia', 'Cite encyclopedia'],
    ['cite encyclopædia', 'cite encyclopedia'],
    ['Proquest', 'ProQuest'],
    ['proquest', 'ProQuest'],
    ['Pq', 'ProQuest'],
    ['pq', 'ProQuest'],
    ['PQ', 'ProQuest'],
    ['pQ', 'ProQuest'],
    ['DOI', 'doi'],
    ['Doi', 'doi'],
    ['Deadurl', 'Dead link'],
    ['deadurl', 'dead link'],
    ['Citeseerx', 'CiteSeerX'],
    ['citeseerx', 'CiteSeerX'],
    ['GALE', 'Gale'],
    ['Ebsco', 'EBSCOhost'],
    ['Ebscohost', 'EBSCOhost'],
    ['EBSCO', 'EBSCOhost'],
    ['ebsco', 'EBSCOhost'],
    ['ebscohost', 'EBSCOhost'],
    ['eBSCO', 'EBSCOhost'],
    ['Ncid', 'NCID'],
    ['ncid', 'NCID'],
    ['BHLpage', 'BHL page'],
    ['Internet archive', 'Internet Archive'],
    ['internet archive', 'Internet Archive'],
    ['youtube', 'YouTube'],
    ['Youtube', 'YouTube'],
    ['pmc', 'PMC'],
    ['pmid', 'PMID'],
    ['jstor', 'JSTOR'],
    ['lccn', 'LCCN'],
    ['Pmc', 'PMC'],
    ['Pmid', 'PMID'],
    ['Jstor', 'JSTOR'],
    ['Lccn', 'LCCN'],
    ['urn', 'URN'],
    ['Urn', 'URN'],
    ['ISSN search link', 'ISSN link'],
    ['ISSNT', 'ISSN link'],
    ['issn search', 'ISSN link'],
    ['ISSN pair', 'ISSN link'],
    ['paywall', 'subscription required'],
    ['Paywall', 'Subscription required'],
    ['Required subscription', 'Subscription required'],
    ['Subscriptionrequired', 'Subscription required'],
    ['Subscription needed', 'Subscription required'],
    ['Pay', 'Subscription required'],
    ['Restricted access', 'Subscription required'],
    ['Paywalled', 'Subscription required'],
    ['Subscription-required', 'Subscription required'],
    ['Requires subscription', 'Subscription required'],
    ['Premium access', 'Subscription required'],
    ['Premium content', 'Subscription required'],
    ['Locked content', 'Subscription required'],
    ['Subscription only', 'Subscription required'],
    ['Subscribers only', 'Subscription required'],
    ['Subreq', 'Subscription required'],
    ['Subscription', 'Subscription required'],
    ['required subscription', 'subscription required'],
    ['subscriptionrequired', 'subscription required'],
    ['subscription needed', 'subscription required'],
    ['pay', 'subscription required'],
    ['restricted access', 'subscription required'],
    ['paywalled', 'subscription required'],
    ['subscription-required', 'subscription required'],
    ['requires subscription', 'subscription required'],
    ['premium access', 'subscription required'],
    ['premium content', 'subscription required'],
    ['locked content', 'subscription required'],
    ['subscription only', 'subscription required'],
    ['subscribers only', 'subscription required'],
    ['subreq', 'subscription required'],
    ['subscription', 'subscription required'],
    ['registration', 'registration required'],
    ['Registration', 'Registration required'],
    ['reg', 'registration required'],
    ['Reg', 'Registration required'],
    ['regreq', 'registration required'],
    ['Regreq', 'Registration required'],
    ['registration-required', 'registration required'],
    ['Registration-required', 'Registration required'],
    ['registration needed', 'registration required'],
    ['Registration needed', 'Registration required'],
    ['cite article', 'cite news'],
    ['Cite article', 'Cite news'],
    ['Webarchiv', 'Webarchive'],
    ['webarchiv', 'webarchive'],
];
