<?php
declare(strict_types=1);
const TEMPLATES_WE_PROCESS = array('citation', 'cite arxiv', 'cite book', 'cite books', 'cite document', 
                             'cite encyclopaedia', 'cite encyclopedia', 'cite journal', 'cite web', 'cite work',
                             'cite paper', 'cite', 'citebook', 'citejournal', 'citeweb', 'cite url', 'citepaper', 'citation journal',
                             'cite publication', 'cite citeseerx', 'cite website', 'cite dictionary', 'cite chapter', 'web cite', 'book cite',
                             'book reference', 'cit web', 'cit book', 'cite-book', 'cite-web', 'cit journal', 'cit news',
                             'web reference', 'cite citation', 'cite contribution', 'cite ebook');
const TEMPLATES_WE_SLIGHTLY_PROCESS = array('cite news', 'cite newspaper', 'cite conference', 'cite article', 'citenews', 'cite new');
const TEMPLATES_WE_BARELY_PROCESS = array('cite thesis', 'cite press release', 'cite report', 'cite biorxiv');
const TEMPLATES_WE_RENAME  = array('cite arxiv', 'cite book', 'cite document', 'cite journal', 'cite web', 'cite work', 'cite article', 'cite paper', 'cite website');
const TEMPLATES_WE_CHAPTER_URL = array('new cambridge medieval history', 'setton-a history of the crusades', 'new cambridge medieval history',
                                       'the cambridge history of iran', 'the buwayhid dynasty in iraq', 'the cambridge history of egypt',
                                       'the history of al-tabari', 'the prophet and the age of the caliphates', 'cambridge ancient history',
                                       'the last centuries of byzantium, 1261–1453', 'the byzantine revival, 780–842', 
                                       'cite cambridge history of china', 'warfare, state and society in the byzantine world, 565–1204',
                                       'die provinzen des osmanischen reiches', 'runciman-a history of the crusades',
                                       'history of taron', 'the muslims of medieval italy', 'emperor michael palaeologus and the west',
                                       'arts of armenia', 'a history of palestine, 634–1099', 'baghdad during the abbasid caliphate',
                                       'baghdad during the abbasid caliphate', 'the cambridge history of china', 'cambridge history of iran',
                                       'essays on the latin orient', 'cambridge history of egypt');
const TEMPLATES_VCITE = array('vcite book', 'vcite conference', 'vcite journal', 'vcite news', 'vcite web');
const TEMPLATES_WE_HARV = array('cite iucn', 'cite odnb', 'cite dnb', 'dnb', 'dnbie', 'cite americana', 'cite eb1911', 'cite techreport',
                                'cite wikisource', 'ei2', 'encyclopaedia of islam, new edition', 'ei3', 'encyclopaedia of islam, three',
                                'cite catholic encyclopedia', 'cathency', 'cite ce1913', 'cite danfs', 'new american cyclopedia', 'cite power broker',
                                'cite central park history', 'schafer-more-classic', 'cite grove', 'eb1911', 'odnbweb', 'cite eb9', 'cite dcb',
                                'encyclopaedia islamica', 'goldberg-amtrak', 'hilton-amtrak', 'solomon-sp-passenger', 'wayner - car names, numbers, consists',
                                'wayner - car names, numbers, consists', 'cite lotep', 'cite lives of the eminent philosophers',
                                'cite av media notes', 'gilliland', 'cox-upper darby', 'oxford dictionary of late antiquity', 
                                'cite notitia parliamentaria', 'historyofparliament', 'lewis-shortline-1986',
                                'lewis-shortline-1991', 'cite podcast', 'oxford dictionary of late antiquity', 'duke-rdc',
                                'lynch-new haven passenger', 'schwieterman-leaves-eastern', 'amtrak by the numbers', 'cite amcyc',
                                'historic environment scotland', 'cite lotep', 'zimmermann-burlington', 'shaughnessy-dh', 'reynolds-bo',
                                'sanders-heartland', 'cite av media', 'murray-illinois central', 'schafer-streamliners',
                                'cite letter', 'cite dgrg', 'cite interview', 'cite dnbsupp', '1922 locomotive cyclopedia',
                                'foster-field guide', 'solomon-ge and emd', 'pinkepank diesel spotters guide 2',
                                'solomon-electro-motive', 'middleton-electrified-2nd', 'schafer-vintage diesel',
                                'solomon-american diesel', 'solomon-emd f-unit', 'solomon-emd locomotives',
                                'solomon-vintage diesel', 'solomon-north american locomotives', 'cite sep',
                                'wegman-illustrated', 'zimmermann-santa fe', 'glischinski-santa fe', 'disraeliref', 'cite map',
                                'taber-dlw-19th', 'taber-dlw-20th-1', 'book-hills-power from steam', 'cite danfs', 'cite liner notes',
                                'setton-a history of the crusades', "cite appletons'", 'cite dnb12', 'cite newsletter',
                                'the cambridge history of iran', 'drury historical guide 1985', 'cite dgrbm', 'cite nie',
                                'herr-ln', 'complete book of north american railroading', 'catholic', 'gilliland', 'cite eb1922', 
                                'cite audb', 'cite serial', 'solomon-csx', 'skeptoid', 'colledge', 'cite nuttall', 
                                'citar tese', 'sbdel', 'australian dictionary of biography', 'cyclopaedia 1728',
                                'dnb cite', 'rfk6.1 ', 'schafer-classic-railroads-1', 'springer', 'holland-classic',
                                'sanders-indiana', 'cite biblica', 'white - american railroad freight car', 
                                'hilton-interurban', 'middleton-interurban', 'butt-stations', 'solomon-modern diesel', 
                                'mcdonnell-locomotives-2nd', 'cite gotham', '1911', 'scribbins-400-2008', 'catholic encyclopedia', 
                                'cite video', 'ivey-marquette', 'michigan railroad commission', 'cite hidden waters nyc',
                                'williams-philadelphia', 'downey-chicago', 'hilton narrow gauge', 'kratville-ssl',
                                'cite dissertation', 'cite jewish encyclopedia', 'cudahy-hudson', 'williams-philadelphia',
                                'holton-reading-1', 'coates-reading', 'williams-philadelphia', 'cite afm', 'churella-prr-1',
                                'cudahy-hudson', 'cite bdcc', 'canadabio', 'gillham-waterloo-city', 'cite aia5', 'scribbins-hiawatha',
                                'solomon-masterpieces', 'cite episode', 'taber-dlw-20th-2', 'bbkl', 'burch electric traction',
                                'cite ssrn', 'lsi', 'linguistic survey of india', 'yenne-chiefs', 'schafer-classic-railroads-3',
                                'cite morningside', 'cite newspaper the times', 'kratville-ssl', 'cite cem', 'mactutor biography',
                                'clementsmcmahon-gsr locomotives', 'vennac', 'lynch-penn central', 'meints-companies',
                                'meints-lines', 'scribbins-remembered', 'burch electric traction', 'staufer-pennsy power ii', 
                                'volkmer-pennsy-electric', 'staufer-pennsy', 'cudahy-hudson', 'middleton-prr-under-wire', 
                                'bezilla-prr-electric-traction', 'dunbar-railroads', 'meints-companies', 'oxford dictionary of byzantium', 
                                'dlmf', 'mlcc', 'cite episode', 'dnb12', 'cite sbdel', 'nhle', 'london gazette', 'odb', 'maiken-night trains', 
                                'solomon-up', 'welsh-pullman', 'welsh-up', 'eminent scotsmen', 'cite dab', 'cite act', 'cite je1906', 
                                'lewis-shortline-1996', 'cite speech', 'holt-northwest', 'grant-railco', 'johnston-streamliner', 
                                'schafer-classic', 'welsh-broadway', 'feis', 'schafer-american passenger train', 'msw3 hystricognathi', 
                                'encyclopedia of north american railroads', 'dunn-comeng-5', 'cudahy-subways', 'cite dnbie',
                                'bonnett practical rail engineering', 'solomon-amtrak', 'cox-dixie', 'holton-reading-2', 'cite irishbio', 
                                'cite film', 'sowl', 'cite IETF', 'cite manhmaps', 'ndb', 'cite adb', 'cite ogn', 'dgrbm', 'greenlaw-via rail', 
                                'cite newsgroup', 'the history of al-tabari', 'cite newgenbio', 'white-passenger-1985', 
                                'saunders-merging lines', 'dorin-north western', 'cambridge history of iran', 'quick-stations', 'irs-el',
                                'cite bede he', 'cite court', 'google books', 'date', 'cite arnold hague convoy database',
                                'cite ahcd', 'me-ref', 'slomon-new york central', 'cite archive');

const ALL_URL_TYPES = array('url', 'article-url', 'chapter-url', 'chapterurl', 'conference-url', 'conferenceurl',
                  'contribution-url', 'contributionurl', 'entry-url', 'event-url', 'eventurl', 'lay-url',
                  'layurl', 'map-url', 'mapurl', 'section-url', 'sectionurl', 'transcript-url',
                  'transcripturl', 'URL');

const DATES_TO_CLEAN = array('air-date', 'airdate', 'archive-date', 'archivedate', 'date', 'pmc-embargo-date', 'publication-date', 'lay-date');

const AUTHOR_PARAMETERS = array(
    1  => array('surname'  , 'forename'  , 'initials'  , 'first'  , 'last'  , 'author', 
                'vauthors', 'authors', 'author-last', 'author-first',
                'surname1' , 'forename1' , 'initials1' , 'first1' , 'last1' , 'author1',  'author1-last',  'author-last1',  'author1-first',  'author-first1',
                'given', 'given1', 'author-given', 'author-given1', 'author1-given', 'author-surname1', 'author1-surname', 'author-surname'),
2=>array('surname2','forename2','initials2','first2','last2','author2','author2-last','author-last2','author2-first','author-first2','author-given2','author2-given','given2','author-surname2','author2-surname','coauthors','coauthor','others'),
3=>array('surname3','forename3','initials3','first3','last3','author3','author3-last','author-last3','author3-first','author-first3','author-given3','author3-given','given3','author-surname3','author3-surname'),
4=>array('surname4','forename4','initials4','first4','last4','author4','author4-last','author-last4','author4-first','author-first4','author-given4','author4-given','given4','author-surname4','author4-surname'),
5=>array('surname5','forename5','initials5','first5','last5','author5','author5-last','author-last5','author5-first','author-first5','author-given5','author5-given','given5','author-surname5','author5-surname'),
6=>array('surname6','forename6','initials6','first6','last6','author6','author6-last','author-last6','author6-first','author-first6','author-given6','author6-given','given6','author-surname6','author6-surname'),
7=>array('surname7','forename7','initials7','first7','last7','author7','author7-last','author-last7','author7-first','author-first7','author-given7','author7-given','given7','author-surname7','author7-surname'),
8=>array('surname8','forename8','initials8','first8','last8','author8','author8-last','author-last8','author8-first','author-first8','author-given8','author8-given','given8','author-surname8','author8-surname'),
9=>array('surname9','forename9','initials9','first9','last9','author9','author9-last','author-last9','author9-first','author-first9','author-given9','author9-given','given9','author-surname9','author9-surname'),
10=>array('surname10','forename10','initials10','first10','last10','author10','author10-last','author-last10','author10-first','author-first10','author-given10','author10-given','given10','author-surname10','author10-surname'),
11=>array('surname11','forename11','initials11','first11','last11','author11','author11-last','author-last11','author11-first','author-first11','author-given11','author11-given','given11','author-surname11','author11-surname'),
12=>array('surname12','forename12','initials12','first12','last12','author12','author12-last','author-last12','author12-first','author-first12','author-given12','author12-given','given12','author-surname12','author12-surname'),
13=>array('surname13','forename13','initials13','first13','last13','author13','author13-last','author-last13','author13-first','author-first13','author-given13','author13-given','given13','author-surname13','author13-surname'),
14=>array('surname14','forename14','initials14','first14','last14','author14','author14-last','author-last14','author14-first','author-first14','author-given14','author14-given','given14','author-surname14','author14-surname'),
15=>array('surname15','forename15','initials15','first15','last15','author15','author15-last','author-last15','author15-first','author-first15','author-given15','author15-given','given15','author-surname15','author15-surname'),
16=>array('surname16','forename16','initials16','first16','last16','author16','author16-last','author-last16','author16-first','author-first16','author-given16','author16-given','given16','author-surname16','author16-surname'),
17=>array('surname17','forename17','initials17','first17','last17','author17','author17-last','author-last17','author17-first','author-first17','author-given17','author17-given','given17','author-surname17','author17-surname'),
18=>array('surname18','forename18','initials18','first18','last18','author18','author18-last','author-last18','author18-first','author-first18','author-given18','author18-given','given18','author-surname18','author18-surname'),
19=>array('surname19','forename19','initials19','first19','last19','author19','author19-last','author-last19','author19-first','author-first19','author-given19','author19-given','given19','author-surname19','author19-surname'),
20=>array('surname20','forename20','initials20','first20','last20','author20','author20-last','author-last20','author20-first','author-first20','author-given20','author20-given','given20','author-surname20','author20-surname'),
21=>array('surname21','forename21','initials21','first21','last21','author21','author21-last','author-last21','author21-first','author-first21','author-given21','author21-given','given21','author-surname21','author21-surname'),
22=>array('surname22','forename22','initials22','first22','last22','author22','author22-last','author-last22','author22-first','author-first22','author-given22','author22-given','given22','author-surname22','author22-surname'),
23=>array('surname23','forename23','initials23','first23','last23','author23','author23-last','author-last23','author23-first','author-first23','author-given23','author23-given','given23','author-surname23','author23-surname'),
24=>array('surname24','forename24','initials24','first24','last24','author24','author24-last','author-last24','author24-first','author-first24','author-given24','author24-given','given24','author-surname24','author24-surname'),
25=>array('surname25','forename25','initials25','first25','last25','author25','author25-last','author-last25','author25-first','author-first25','author-given25','author25-given','given25','author-surname25','author25-surname'),
26=>array('surname26','forename26','initials26','first26','last26','author26','author26-last','author-last26','author26-first','author-first26','author-given26','author26-given','given26','author-surname26','author26-surname'),
27=>array('surname27','forename27','initials27','first27','last27','author27','author27-last','author-last27','author27-first','author-first27','author-given27','author27-given','given27','author-surname27','author27-surname'),
28=>array('surname28','forename28','initials28','first28','last28','author28','author28-last','author-last28','author28-first','author-first28','author-given28','author28-given','given28','author-surname28','author28-surname'),
29=>array('surname29','forename29','initials29','first29','last29','author29','author29-last','author-last29','author29-first','author-first29','author-given29','author29-given','given29','author-surname29','author29-surname'),
30=>array('surname30','forename30','initials30','first30','last30','author30','author30-last','author-last30','author30-first','author-first30','author-given30','author30-given','given30','author-surname30','author30-surname'),
31=>array('surname31','forename31','initials31','first31','last31','author31','author31-last','author-last31','author31-first','author-first31','author-given31','author31-given','given31','author-surname31','author31-surname'),
32=>array('surname32','forename32','initials32','first32','last32','author32','author32-last','author-last32','author32-first','author-first32','author-given32','author32-given','given32','author-surname32','author32-surname'),
33=>array('surname33','forename33','initials33','first33','last33','author33','author33-last','author-last33','author33-first','author-first33','author-given33','author33-given','given33','author-surname33','author33-surname'),
34=>array('surname34','forename34','initials34','first34','last34','author34','author34-last','author-last34','author34-first','author-first34','author-given34','author34-given','given34','author-surname34','author34-surname'),
35=>array('surname35','forename35','initials35','first35','last35','author35','author35-last','author-last35','author35-first','author-first35','author-given35','author35-given','given35','author-surname35','author35-surname'),
36=>array('surname36','forename36','initials36','first36','last36','author36','author36-last','author-last36','author36-first','author-first36','author-given36','author36-given','given36','author-surname36','author36-surname'),
37=>array('surname37','forename37','initials37','first37','last37','author37','author37-last','author-last37','author37-first','author-first37','author-given37','author37-given','given37','author-surname37','author37-surname'),
38=>array('surname38','forename38','initials38','first38','last38','author38','author38-last','author-last38','author38-first','author-first38','author-given38','author38-given','given38','author-surname38','author38-surname'),
39=>array('surname39','forename39','initials39','first39','last39','author39','author39-last','author-last39','author39-first','author-first39','author-given39','author39-given','given39','author-surname39','author39-surname'),
40=>array('surname40','forename40','initials40','first40','last40','author40','author40-last','author-last40','author40-first','author-first40','author-given40','author40-given','given40','author-surname40','author40-surname'),
41=>array('surname41','forename41','initials41','first41','last41','author41','author41-last','author-last41','author41-first','author-first41','author-given41','author41-given','given41','author-surname41','author41-surname'),
42=>array('surname42','forename42','initials42','first42','last42','author42','author42-last','author-last42','author42-first','author-first42','author-given42','author42-given','given42','author-surname42','author42-surname'),
43=>array('surname43','forename43','initials43','first43','last43','author43','author43-last','author-last43','author43-first','author-first43','author-given43','author43-given','given43','author-surname43','author43-surname'),
44=>array('surname44','forename44','initials44','first44','last44','author44','author44-last','author-last44','author44-first','author-first44','author-given44','author44-given','given44','author-surname44','author44-surname'),
45=>array('surname45','forename45','initials45','first45','last45','author45','author45-last','author-last45','author45-first','author-first45','author-given45','author45-given','given45','author-surname45','author45-surname'),
46=>array('surname46','forename46','initials46','first46','last46','author46','author46-last','author-last46','author46-first','author-first46','author-given46','author46-given','given46','author-surname46','author46-surname'),
47=>array('surname47','forename47','initials47','first47','last47','author47','author47-last','author-last47','author47-first','author-first47','author-given47','author47-given','given47','author-surname47','author47-surname'),
48=>array('surname48','forename48','initials48','first48','last48','author48','author48-last','author-last48','author48-first','author-first48','author-given48','author48-given','given48','author-surname48','author48-surname'),
49=>array('surname49','forename49','initials49','first49','last49','author49','author49-last','author-last49','author49-first','author-first49','author-given49','author49-given','given49','author-surname49','author49-surname'),
50=>array('surname50','forename50','initials50','first50','last50','author50','author50-last','author-last50','author50-first','author-first50','author-given50','author50-given','given50','author-surname50','author50-surname'),
51=>array('surname51','forename51','initials51','first51','last51','author51','author51-last','author-last51','author51-first','author-first51','author-given51','author51-given','given51','author-surname51','author51-surname'),
52=>array('surname52','forename52','initials52','first52','last52','author52','author52-last','author-last52','author52-first','author-first52','author-given52','author52-given','given52','author-surname52','author52-surname'),
53=>array('surname53','forename53','initials53','first53','last53','author53','author53-last','author-last53','author53-first','author-first53','author-given53','author53-given','given53','author-surname53','author53-surname'),
54=>array('surname54','forename54','initials54','first54','last54','author54','author54-last','author-last54','author54-first','author-first54','author-given54','author54-given','given54','author-surname54','author54-surname'),
55=>array('surname55','forename55','initials55','first55','last55','author55','author55-last','author-last55','author55-first','author-first55','author-given55','author55-given','given55','author-surname55','author55-surname'),
56=>array('surname56','forename56','initials56','first56','last56','author56','author56-last','author-last56','author56-first','author-first56','author-given56','author56-given','given56','author-surname56','author56-surname'),
57=>array('surname57','forename57','initials57','first57','last57','author57','author57-last','author-last57','author57-first','author-first57','author-given57','author57-given','given57','author-surname57','author57-surname'),
58=>array('surname58','forename58','initials58','first58','last58','author58','author58-last','author-last58','author58-first','author-first58','author-given58','author58-given','given58','author-surname58','author58-surname'),
59=>array('surname59','forename59','initials59','first59','last59','author59','author59-last','author-last59','author59-first','author-first59','author-given59','author59-given','given59','author-surname59','author59-surname'),
60=>array('surname60','forename60','initials60','first60','last60','author60','author60-last','author-last60','author60-first','author-first60','author-given60','author60-given','given60','author-surname60','author60-surname'),
61=>array('surname61','forename61','initials61','first61','last61','author61','author61-last','author-last61','author61-first','author-first61','author-given61','author61-given','given61','author-surname61','author61-surname'),
62=>array('surname62','forename62','initials62','first62','last62','author62','author62-last','author-last62','author62-first','author-first62','author-given62','author62-given','given62','author-surname62','author62-surname'),
63=>array('surname63','forename63','initials63','first63','last63','author63','author63-last','author-last63','author63-first','author-first63','author-given63','author63-given','given63','author-surname63','author63-surname'),
64=>array('surname64','forename64','initials64','first64','last64','author64','author64-last','author-last64','author64-first','author-first64','author-given64','author64-given','given64','author-surname64','author64-surname'),
65=>array('surname65','forename65','initials65','first65','last65','author65','author65-last','author-last65','author65-first','author-first65','author-given65','author65-given','given65','author-surname65','author65-surname'),
66=>array('surname66','forename66','initials66','first66','last66','author66','author66-last','author-last66','author66-first','author-first66','author-given66','author66-given','given66','author-surname66','author66-surname'),
67=>array('surname67','forename67','initials67','first67','last67','author67','author67-last','author-last67','author67-first','author-first67','author-given67','author67-given','given67','author-surname67','author67-surname'),
68=>array('surname68','forename68','initials68','first68','last68','author68','author68-last','author-last68','author68-first','author-first68','author-given68','author68-given','given68','author-surname68','author68-surname'),
69=>array('surname69','forename69','initials69','first69','last69','author69','author69-last','author-last69','author69-first','author-first69','author-given69','author69-given','given69','author-surname69','author69-surname'),
70=>array('surname70','forename70','initials70','first70','last70','author70','author70-last','author-last70','author70-first','author-first70','author-given70','author70-given','given70','author-surname70','author70-surname'),
71=>array('surname71','forename71','initials71','first71','last71','author71','author71-last','author-last71','author71-first','author-first71','author-given71','author71-given','given71','author-surname71','author71-surname'),
72=>array('surname72','forename72','initials72','first72','last72','author72','author72-last','author-last72','author72-first','author-first72','author-given72','author72-given','given72','author-surname72','author72-surname'),
73=>array('surname73','forename73','initials73','first73','last73','author73','author73-last','author-last73','author73-first','author-first73','author-given73','author73-given','given73','author-surname73','author73-surname'),
74=>array('surname74','forename74','initials74','first74','last74','author74','author74-last','author-last74','author74-first','author-first74','author-given74','author74-given','given74','author-surname74','author74-surname'),
75=>array('surname75','forename75','initials75','first75','last75','author75','author75-last','author-last75','author75-first','author-first75','author-given75','author75-given','given75','author-surname75','author75-surname'),
76=>array('surname76','forename76','initials76','first76','last76','author76','author76-last','author-last76','author76-first','author-first76','author-given76','author76-given','given76','author-surname76','author76-surname'),
77=>array('surname77','forename77','initials77','first77','last77','author77','author77-last','author-last77','author77-first','author-first77','author-given77','author77-given','given77','author-surname77','author77-surname'),
78=>array('surname78','forename78','initials78','first78','last78','author78','author78-last','author-last78','author78-first','author-first78','author-given78','author78-given','given78','author-surname78','author78-surname'),
79=>array('surname79','forename79','initials79','first79','last79','author79','author79-last','author-last79','author79-first','author-first79','author-given79','author79-given','given79','author-surname79','author79-surname'),
80=>array('surname80','forename80','initials80','first80','last80','author80','author80-last','author-last80','author80-first','author-first80','author-given80','author80-given','given80','author-surname80','author80-surname'),
81=>array('surname81','forename81','initials81','first81','last81','author81','author81-last','author-last81','author81-first','author-first81','author-given81','author81-given','given81','author-surname81','author81-surname'),
82=>array('surname82','forename82','initials82','first82','last82','author82','author82-last','author-last82','author82-first','author-first82','author-given82','author82-given','given82','author-surname82','author82-surname'),
83=>array('surname83','forename83','initials83','first83','last83','author83','author83-last','author-last83','author83-first','author-first83','author-given83','author83-given','given83','author-surname83','author83-surname'),
84=>array('surname84','forename84','initials84','first84','last84','author84','author84-last','author-last84','author84-first','author-first84','author-given84','author84-given','given84','author-surname84','author84-surname'),
85=>array('surname85','forename85','initials85','first85','last85','author85','author85-last','author-last85','author85-first','author-first85','author-given85','author85-given','given85','author-surname85','author85-surname'),
86=>array('surname86','forename86','initials86','first86','last86','author86','author86-last','author-last86','author86-first','author-first86','author-given86','author86-given','given86','author-surname86','author86-surname'),
87=>array('surname87','forename87','initials87','first87','last87','author87','author87-last','author-last87','author87-first','author-first87','author-given87','author87-given','given87','author-surname87','author87-surname'),
88=>array('surname88','forename88','initials88','first88','last88','author88','author88-last','author-last88','author88-first','author-first88','author-given88','author88-given','given88','author-surname88','author88-surname'),
89=>array('surname89','forename89','initials89','first89','last89','author89','author89-last','author-last89','author89-first','author-first89','author-given89','author89-given','given89','author-surname89','author89-surname'),
90=>array('surname90','forename90','initials90','first90','last90','author90','author90-last','author-last90','author90-first','author-first90','author-given90','author90-given','given90','author-surname90','author90-surname'),
91=>array('surname91','forename91','initials91','first91','last91','author91','author91-last','author-last91','author91-first','author-first91','author-given91','author91-given','given91','author-surname91','author91-surname'),
92=>array('surname92','forename92','initials92','first92','last92','author92','author92-last','author-last92','author92-first','author-first92','author-given92','author92-given','given92','author-surname92','author92-surname'),
93=>array('surname93','forename93','initials93','first93','last93','author93','author93-last','author-last93','author93-first','author-first93','author-given93','author93-given','given93','author-surname93','author93-surname'),
94=>array('surname94','forename94','initials94','first94','last94','author94','author94-last','author-last94','author94-first','author-first94','author-given94','author94-given','given94','author-surname94','author94-surname'),
95=>array('surname95','forename95','initials95','first95','last95','author95','author95-last','author-last95','author95-first','author-first95','author-given95','author95-given','given95','author-surname95','author95-surname'),
96=>array('surname96','forename96','initials96','first96','last96','author96','author96-last','author-last96','author96-first','author-first96','author-given96','author96-given','given96','author-surname96','author96-surname'),
97=>array('surname97','forename97','initials97','first97','last97','author97','author97-last','author-last97','author97-first','author-first97','author-given97','author97-given','given97','author-surname97','author97-surname'),
98=>array('surname98','forename98','initials98','first98','last98','author98','author98-last','author-last98','author98-first','author-first98','author-given98','author98-given','given98','author-surname98','author98-surname'),
99=>array('surname99','forename99','initials99','first99','last99','author99','author99-last','author-last99','author99-first','author-first99','author-given99','author99-given','given99','author-surname99','author99-surname')
);
const FLATTENED_AUTHOR_PARAMETERS = array('surname', 'forename', 'initials', 'others',
    'first', 'last', 'author', 'authors', 'vauthors', 'author-last', 'author-first',
    'given', 'given1', 'author-given', 'author-given1', 'author1-given', 'author-surname1', 'author1-surname', 'author-surname',
    'surname1' , 'forename1' , 'initials1' , 'first1' , 'last1' , 'author1' , 'author1-last',  'author-last1',  'author1-first',  'author-first1',
'surname2','forename2','initials2','first2','last2','author2','author2-last','author-last2','author2-first','author-first2','author-given2','author2-given','given2','author-surname2','author2-surname','coauthors','coauthor',
'surname3','forename3','initials3','first3','last3','author3','author3-last','author-last3','author3-first','author-first3','author-given3','author3-given','given3','author-surname3','author3-surname',
'surname4','forename4','initials4','first4','last4','author4','author4-last','author-last4','author4-first','author-first4','author-given4','author4-given','given4','author-surname4','author4-surname',
'surname5','forename5','initials5','first5','last5','author5','author5-last','author-last5','author5-first','author-first5','author-given5','author5-given','given5','author-surname5','author5-surname',
'surname6','forename6','initials6','first6','last6','author6','author6-last','author-last6','author6-first','author-first6','author-given6','author6-given','given6','author-surname6','author6-surname',
'surname7','forename7','initials7','first7','last7','author7','author7-last','author-last7','author7-first','author-first7','author-given7','author7-given','given7','author-surname7','author7-surname',
'surname8','forename8','initials8','first8','last8','author8','author8-last','author-last8','author8-first','author-first8','author-given8','author8-given','given8','author-surname8','author8-surname',
'surname9','forename9','initials9','first9','last9','author9','author9-last','author-last9','author9-first','author-first9','author-given9','author9-given','given9','author-surname9','author9-surname',
'surname10','forename10','initials10','first10','last10','author10','author10-last','author-last10','author10-first','author-first10','author-given10','author10-given','given10','author-surname10','author10-surname',
'surname11','forename11','initials11','first11','last11','author11','author11-last','author-last11','author11-first','author-first11','author-given11','author11-given','given11','author-surname11','author11-surname',
'surname12','forename12','initials12','first12','last12','author12','author12-last','author-last12','author12-first','author-first12','author-given12','author12-given','given12','author-surname12','author12-surname',
'surname13','forename13','initials13','first13','last13','author13','author13-last','author-last13','author13-first','author-first13','author-given13','author13-given','given13','author-surname13','author13-surname',
'surname14','forename14','initials14','first14','last14','author14','author14-last','author-last14','author14-first','author-first14','author-given14','author14-given','given14','author-surname14','author14-surname',
'surname15','forename15','initials15','first15','last15','author15','author15-last','author-last15','author15-first','author-first15','author-given15','author15-given','given15','author-surname15','author15-surname',
'surname16','forename16','initials16','first16','last16','author16','author16-last','author-last16','author16-first','author-first16','author-given16','author16-given','given16','author-surname16','author16-surname',
'surname17','forename17','initials17','first17','last17','author17','author17-last','author-last17','author17-first','author-first17','author-given17','author17-given','given17','author-surname17','author17-surname',
'surname18','forename18','initials18','first18','last18','author18','author18-last','author-last18','author18-first','author-first18','author-given18','author18-given','given18','author-surname18','author18-surname',
'surname19','forename19','initials19','first19','last19','author19','author19-last','author-last19','author19-first','author-first19','author-given19','author19-given','given19','author-surname19','author19-surname',
'surname20','forename20','initials20','first20','last20','author20','author20-last','author-last20','author20-first','author-first20','author-given20','author20-given','given20','author-surname20','author20-surname',
'surname21','forename21','initials21','first21','last21','author21','author21-last','author-last21','author21-first','author-first21','author-given21','author21-given','given21','author-surname21','author21-surname',
'surname22','forename22','initials22','first22','last22','author22','author22-last','author-last22','author22-first','author-first22','author-given22','author22-given','given22','author-surname22','author22-surname',
'surname23','forename23','initials23','first23','last23','author23','author23-last','author-last23','author23-first','author-first23','author-given23','author23-given','given23','author-surname23','author23-surname',
'surname24','forename24','initials24','first24','last24','author24','author24-last','author-last24','author24-first','author-first24','author-given24','author24-given','given24','author-surname24','author24-surname',
'surname25','forename25','initials25','first25','last25','author25','author25-last','author-last25','author25-first','author-first25','author-given25','author25-given','given25','author-surname25','author25-surname',
'surname26','forename26','initials26','first26','last26','author26','author26-last','author-last26','author26-first','author-first26','author-given26','author26-given','given26','author-surname26','author26-surname',
'surname27','forename27','initials27','first27','last27','author27','author27-last','author-last27','author27-first','author-first27','author-given27','author27-given','given27','author-surname27','author27-surname',
'surname28','forename28','initials28','first28','last28','author28','author28-last','author-last28','author28-first','author-first28','author-given28','author28-given','given28','author-surname28','author28-surname',
'surname29','forename29','initials29','first29','last29','author29','author29-last','author-last29','author29-first','author-first29','author-given29','author29-given','given29','author-surname29','author29-surname',
'surname30','forename30','initials30','first30','last30','author30','author30-last','author-last30','author30-first','author-first30','author-given30','author30-given','given30','author-surname30','author30-surname',
'surname31','forename31','initials31','first31','last31','author31','author31-last','author-last31','author31-first','author-first31','author-given31','author31-given','given31','author-surname31','author31-surname',
'surname32','forename32','initials32','first32','last32','author32','author32-last','author-last32','author32-first','author-first32','author-given32','author32-given','given32','author-surname32','author32-surname',
'surname33','forename33','initials33','first33','last33','author33','author33-last','author-last33','author33-first','author-first33','author-given33','author33-given','given33','author-surname33','author33-surname',
'surname34','forename34','initials34','first34','last34','author34','author34-last','author-last34','author34-first','author-first34','author-given34','author34-given','given34','author-surname34','author34-surname',
'surname35','forename35','initials35','first35','last35','author35','author35-last','author-last35','author35-first','author-first35','author-given35','author35-given','given35','author-surname35','author35-surname',
'surname36','forename36','initials36','first36','last36','author36','author36-last','author-last36','author36-first','author-first36','author-given36','author36-given','given36','author-surname36','author36-surname',
'surname37','forename37','initials37','first37','last37','author37','author37-last','author-last37','author37-first','author-first37','author-given37','author37-given','given37','author-surname37','author37-surname',
'surname38','forename38','initials38','first38','last38','author38','author38-last','author-last38','author38-first','author-first38','author-given38','author38-given','given38','author-surname38','author38-surname',
'surname39','forename39','initials39','first39','last39','author39','author39-last','author-last39','author39-first','author-first39','author-given39','author39-given','given39','author-surname39','author39-surname',
'surname40','forename40','initials40','first40','last40','author40','author40-last','author-last40','author40-first','author-first40','author-given40','author40-given','given40','author-surname40','author40-surname',
'surname41','forename41','initials41','first41','last41','author41','author41-last','author-last41','author41-first','author-first41','author-given41','author41-given','given41','author-surname41','author41-surname',
'surname42','forename42','initials42','first42','last42','author42','author42-last','author-last42','author42-first','author-first42','author-given42','author42-given','given42','author-surname42','author42-surname',
'surname43','forename43','initials43','first43','last43','author43','author43-last','author-last43','author43-first','author-first43','author-given43','author43-given','given43','author-surname43','author43-surname',
'surname44','forename44','initials44','first44','last44','author44','author44-last','author-last44','author44-first','author-first44','author-given44','author44-given','given44','author-surname44','author44-surname',
'surname45','forename45','initials45','first45','last45','author45','author45-last','author-last45','author45-first','author-first45','author-given45','author45-given','given45','author-surname45','author45-surname',
'surname46','forename46','initials46','first46','last46','author46','author46-last','author-last46','author46-first','author-first46','author-given46','author46-given','given46','author-surname46','author46-surname',
'surname47','forename47','initials47','first47','last47','author47','author47-last','author-last47','author47-first','author-first47','author-given47','author47-given','given47','author-surname47','author47-surname',
'surname48','forename48','initials48','first48','last48','author48','author48-last','author-last48','author48-first','author-first48','author-given48','author48-given','given48','author-surname48','author48-surname',
'surname49','forename49','initials49','first49','last49','author49','author49-last','author-last49','author49-first','author-first49','author-given49','author49-given','given49','author-surname49','author49-surname',
'surname50','forename50','initials50','first50','last50','author50','author50-last','author-last50','author50-first','author-first50','author-given50','author50-given','given50','author-surname50','author50-surname',
'surname51','forename51','initials51','first51','last51','author51','author51-last','author-last51','author51-first','author-first51','author-given51','author51-given','given51','author-surname51','author51-surname',
'surname52','forename52','initials52','first52','last52','author52','author52-last','author-last52','author52-first','author-first52','author-given52','author52-given','given52','author-surname52','author52-surname',
'surname53','forename53','initials53','first53','last53','author53','author53-last','author-last53','author53-first','author-first53','author-given53','author53-given','given53','author-surname53','author53-surname',
'surname54','forename54','initials54','first54','last54','author54','author54-last','author-last54','author54-first','author-first54','author-given54','author54-given','given54','author-surname54','author54-surname',
'surname55','forename55','initials55','first55','last55','author55','author55-last','author-last55','author55-first','author-first55','author-given55','author55-given','given55','author-surname55','author55-surname',
'surname56','forename56','initials56','first56','last56','author56','author56-last','author-last56','author56-first','author-first56','author-given56','author56-given','given56','author-surname56','author56-surname',
'surname57','forename57','initials57','first57','last57','author57','author57-last','author-last57','author57-first','author-first57','author-given57','author57-given','given57','author-surname57','author57-surname',
'surname58','forename58','initials58','first58','last58','author58','author58-last','author-last58','author58-first','author-first58','author-given58','author58-given','given58','author-surname58','author58-surname',
'surname59','forename59','initials59','first59','last59','author59','author59-last','author-last59','author59-first','author-first59','author-given59','author59-given','given59','author-surname59','author59-surname',
'surname60','forename60','initials60','first60','last60','author60','author60-last','author-last60','author60-first','author-first60','author-given60','author60-given','given60','author-surname60','author60-surname',
'surname61','forename61','initials61','first61','last61','author61','author61-last','author-last61','author61-first','author-first61','author-given61','author61-given','given61','author-surname61','author61-surname',
'surname62','forename62','initials62','first62','last62','author62','author62-last','author-last62','author62-first','author-first62','author-given62','author62-given','given62','author-surname62','author62-surname',
'surname63','forename63','initials63','first63','last63','author63','author63-last','author-last63','author63-first','author-first63','author-given63','author63-given','given63','author-surname63','author63-surname',
'surname64','forename64','initials64','first64','last64','author64','author64-last','author-last64','author64-first','author-first64','author-given64','author64-given','given64','author-surname64','author64-surname',
'surname65','forename65','initials65','first65','last65','author65','author65-last','author-last65','author65-first','author-first65','author-given65','author65-given','given65','author-surname65','author65-surname',
'surname66','forename66','initials66','first66','last66','author66','author66-last','author-last66','author66-first','author-first66','author-given66','author66-given','given66','author-surname66','author66-surname',
'surname67','forename67','initials67','first67','last67','author67','author67-last','author-last67','author67-first','author-first67','author-given67','author67-given','given67','author-surname67','author67-surname',
'surname68','forename68','initials68','first68','last68','author68','author68-last','author-last68','author68-first','author-first68','author-given68','author68-given','given68','author-surname68','author68-surname',
'surname69','forename69','initials69','first69','last69','author69','author69-last','author-last69','author69-first','author-first69','author-given69','author69-given','given69','author-surname69','author69-surname',
'surname70','forename70','initials70','first70','last70','author70','author70-last','author-last70','author70-first','author-first70','author-given70','author70-given','given70','author-surname70','author70-surname',
'surname71','forename71','initials71','first71','last71','author71','author71-last','author-last71','author71-first','author-first71','author-given71','author71-given','given71','author-surname71','author71-surname',
'surname72','forename72','initials72','first72','last72','author72','author72-last','author-last72','author72-first','author-first72','author-given72','author72-given','given72','author-surname72','author72-surname',
'surname73','forename73','initials73','first73','last73','author73','author73-last','author-last73','author73-first','author-first73','author-given73','author73-given','given73','author-surname73','author73-surname',
'surname74','forename74','initials74','first74','last74','author74','author74-last','author-last74','author74-first','author-first74','author-given74','author74-given','given74','author-surname74','author74-surname',
'surname75','forename75','initials75','first75','last75','author75','author75-last','author-last75','author75-first','author-first75','author-given75','author75-given','given75','author-surname75','author75-surname',
'surname76','forename76','initials76','first76','last76','author76','author76-last','author-last76','author76-first','author-first76','author-given76','author76-given','given76','author-surname76','author76-surname',
'surname77','forename77','initials77','first77','last77','author77','author77-last','author-last77','author77-first','author-first77','author-given77','author77-given','given77','author-surname77','author77-surname',
'surname78','forename78','initials78','first78','last78','author78','author78-last','author-last78','author78-first','author-first78','author-given78','author78-given','given78','author-surname78','author78-surname',
'surname79','forename79','initials79','first79','last79','author79','author79-last','author-last79','author79-first','author-first79','author-given79','author79-given','given79','author-surname79','author79-surname',
'surname80','forename80','initials80','first80','last80','author80','author80-last','author-last80','author80-first','author-first80','author-given80','author80-given','given80','author-surname80','author80-surname',
'surname81','forename81','initials81','first81','last81','author81','author81-last','author-last81','author81-first','author-first81','author-given81','author81-given','given81','author-surname81','author81-surname',
'surname82','forename82','initials82','first82','last82','author82','author82-last','author-last82','author82-first','author-first82','author-given82','author82-given','given82','author-surname82','author82-surname',
'surname83','forename83','initials83','first83','last83','author83','author83-last','author-last83','author83-first','author-first83','author-given83','author83-given','given83','author-surname83','author83-surname',
'surname84','forename84','initials84','first84','last84','author84','author84-last','author-last84','author84-first','author-first84','author-given84','author84-given','given84','author-surname84','author84-surname',
'surname85','forename85','initials85','first85','last85','author85','author85-last','author-last85','author85-first','author-first85','author-given85','author85-given','given85','author-surname85','author85-surname',
'surname86','forename86','initials86','first86','last86','author86','author86-last','author-last86','author86-first','author-first86','author-given86','author86-given','given86','author-surname86','author86-surname',
'surname87','forename87','initials87','first87','last87','author87','author87-last','author-last87','author87-first','author-first87','author-given87','author87-given','given87','author-surname87','author87-surname',
'surname88','forename88','initials88','first88','last88','author88','author88-last','author-last88','author88-first','author-first88','author-given88','author88-given','given88','author-surname88','author88-surname',
'surname89','forename89','initials89','first89','last89','author89','author89-last','author-last89','author89-first','author-first89','author-given89','author89-given','given89','author-surname89','author89-surname',
'surname90','forename90','initials90','first90','last90','author90','author90-last','author-last90','author90-first','author-first90','author-given90','author90-given','given90','author-surname90','author90-surname',
'surname91','forename91','initials91','first91','last91','author91','author91-last','author-last91','author91-first','author-first91','author-given91','author91-given','given91','author-surname91','author91-surname',
'surname92','forename92','initials92','first92','last92','author92','author92-last','author-last92','author92-first','author-first92','author-given92','author92-given','given92','author-surname92','author92-surname',
'surname93','forename93','initials93','first93','last93','author93','author93-last','author-last93','author93-first','author-first93','author-given93','author93-given','given93','author-surname93','author93-surname',
'surname94','forename94','initials94','first94','last94','author94','author94-last','author-last94','author94-first','author-first94','author-given94','author94-given','given94','author-surname94','author94-surname',
'surname95','forename95','initials95','first95','last95','author95','author95-last','author-last95','author95-first','author-first95','author-given95','author95-given','given95','author-surname95','author95-surname',
'surname96','forename96','initials96','first96','last96','author96','author96-last','author-last96','author96-first','author-first96','author-given96','author96-given','given96','author-surname96','author96-surname',
'surname97','forename97','initials97','first97','last97','author97','author97-last','author-last97','author97-first','author-first97','author-given97','author97-given','given97','author-surname97','author97-surname',
'surname98','forename98','initials98','first98','last98','author98','author98-last','author-last98','author98-first','author-first98','author-given98','author98-given','given98','author-surname98','author98-surname',
'surname99','forename99','initials99','first99','last99','author99','author99-last','author-last99','author99-first','author-first99','author-given99','author99-given','given99','author-surname99','author99-surname'
);

const LOTS_OF_EDITORS = array('editor', 'editor-last', 'veditor', 'editor-surname', 'editor-given', 'editor-mask', 'editor-link',
'editor1', 'editor1-first', 'editor1-given', 'editor1-last', 'editor1-link', 'editor1-mask', 'editor1-surname', 'editor-first1', 'editor-given1', 'editor-last1', 'editor-link1', 'editor-mask1', 'editor-surname1',
'editor2', 'editor2-first', 'editor2-given', 'editor2-last', 'editor2-link', 'editor2-mask', 'editor2-surname', 'editor-first2', 'editor-given2', 'editor-last2', 'editor-link2', 'editor-mask2', 'editor-surname2',
'editor3', 'editor3-first', 'editor3-given', 'editor3-last', 'editor3-link', 'editor3-mask', 'editor3-surname', 'editor-first3', 'editor-given3', 'editor-last3', 'editor-link3', 'editor-mask3', 'editor-surname3',
'editor4', 'editor4-first', 'editor4-given', 'editor4-last', 'editor4-link', 'editor4-mask', 'editor4-surname', 'editor-first4', 'editor-given4', 'editor-last4', 'editor-link4', 'editor-mask4', 'editor-surname4',
'editor5', 'editor5-first', 'editor5-given', 'editor5-last', 'editor5-link', 'editor5-mask', 'editor5-surname', 'editor-first5', 'editor-given5', 'editor-last5', 'editor-link5', 'editor-mask5', 'editor-surname5',
'editor6', 'editor6-first', 'editor6-given', 'editor6-last', 'editor6-link', 'editor6-mask', 'editor6-surname', 'editor-first6', 'editor-given6', 'editor-last6', 'editor-link6', 'editor-mask6', 'editor-surname6',
'editor7', 'editor7-first', 'editor7-given', 'editor7-last', 'editor7-link', 'editor7-mask', 'editor7-surname', 'editor-first7', 'editor-given7', 'editor-last7', 'editor-link7', 'editor-mask7', 'editor-surname7',
'editor8', 'editor8-first', 'editor8-given', 'editor8-last', 'editor8-link', 'editor8-mask', 'editor8-surname', 'editor-first8', 'editor-given8', 'editor-last8', 'editor-link8', 'editor-mask8', 'editor-surname8',
'editor9', 'editor9-first', 'editor9-given', 'editor9-last', 'editor9-link', 'editor9-mask', 'editor9-surname', 'editor-first9', 'editor-given9', 'editor-last9', 'editor-link9', 'editor-mask9', 'editor-surname9',
'editor10', 'editor10-first', 'editor10-given', 'editor10-last', 'editor10-link', 'editor10-mask', 'editor10-surname', 'editor-first10', 'editor-given10', 'editor-last10', 'editor-link10', 'editor-mask10', 'editor-surname10',
'editor11', 'editor11-first', 'editor11-given', 'editor11-last', 'editor11-link', 'editor11-mask', 'editor11-surname', 'editor-first11', 'editor-given11', 'editor-last11', 'editor-link11', 'editor-mask11', 'editor-surname11',
'editor12', 'editor12-first', 'editor12-given', 'editor12-last', 'editor12-link', 'editor12-mask', 'editor12-surname', 'editor-first12', 'editor-given12', 'editor-last12', 'editor-link12', 'editor-mask12', 'editor-surname12',
'editor13', 'editor13-first', 'editor13-given', 'editor13-last', 'editor13-link', 'editor13-mask', 'editor13-surname', 'editor-first13', 'editor-given13', 'editor-last13', 'editor-link13', 'editor-mask13', 'editor-surname13',
'editor14', 'editor14-first', 'editor14-given', 'editor14-last', 'editor14-link', 'editor14-mask', 'editor14-surname', 'editor-first14', 'editor-given14', 'editor-last14', 'editor-link14', 'editor-mask14', 'editor-surname14',
'editor15', 'editor15-first', 'editor15-given', 'editor15-last', 'editor15-link', 'editor15-mask', 'editor15-surname', 'editor-first15', 'editor-given15', 'editor-last15', 'editor-link15', 'editor-mask15', 'editor-surname15',
'editor16', 'editor16-first', 'editor16-given', 'editor16-last', 'editor16-link', 'editor16-mask', 'editor16-surname', 'editor-first16', 'editor-given16', 'editor-last16', 'editor-link16', 'editor-mask16', 'editor-surname16',
'editor17', 'editor17-first', 'editor17-given', 'editor17-last', 'editor17-link', 'editor17-mask', 'editor17-surname', 'editor-first17', 'editor-given17', 'editor-last17', 'editor-link17', 'editor-mask17', 'editor-surname17',
'editor18', 'editor18-first', 'editor18-given', 'editor18-last', 'editor18-link', 'editor18-mask', 'editor18-surname', 'editor-first18', 'editor-given18', 'editor-last18', 'editor-link18', 'editor-mask18', 'editor-surname18',
'editor19', 'editor19-first', 'editor19-given', 'editor19-last', 'editor19-link', 'editor19-mask', 'editor19-surname', 'editor-first19', 'editor-given19', 'editor-last19', 'editor-link19', 'editor-mask19', 'editor-surname19',
'editor20', 'editor20-first', 'editor20-given', 'editor20-last', 'editor20-link', 'editor20-mask', 'editor20-surname', 'editor-first20', 'editor-given20', 'editor-last20', 'editor-link20', 'editor-mask20', 'editor-surname20',
'editor21', 'editor21-first', 'editor21-given', 'editor21-last', 'editor21-link', 'editor21-mask', 'editor21-surname', 'editor-first21', 'editor-given21', 'editor-last21', 'editor-link21', 'editor-mask21', 'editor-surname21',
'editor22', 'editor22-first', 'editor22-given', 'editor22-last', 'editor22-link', 'editor22-mask', 'editor22-surname', 'editor-first22', 'editor-given22', 'editor-last22', 'editor-link22', 'editor-mask22', 'editor-surname22',
'editor23', 'editor23-first', 'editor23-given', 'editor23-last', 'editor23-link', 'editor23-mask', 'editor23-surname', 'editor-first23', 'editor-given23', 'editor-last23', 'editor-link23', 'editor-mask23', 'editor-surname23',
'editor24', 'editor24-first', 'editor24-given', 'editor24-last', 'editor24-link', 'editor24-mask', 'editor24-surname', 'editor-first24', 'editor-given24', 'editor-last24', 'editor-link24', 'editor-mask24', 'editor-surname24',
'editor25', 'editor25-first', 'editor25-given', 'editor25-last', 'editor25-link', 'editor25-mask', 'editor25-surname', 'editor-first25', 'editor-given25', 'editor-last25', 'editor-link25', 'editor-mask25', 'editor-surname25',
'editor26', 'editor26-first', 'editor26-given', 'editor26-last', 'editor26-link', 'editor26-mask', 'editor26-surname', 'editor-first26', 'editor-given26', 'editor-last26', 'editor-link26', 'editor-mask26', 'editor-surname26',
'editor27', 'editor27-first', 'editor27-given', 'editor27-last', 'editor27-link', 'editor27-mask', 'editor27-surname', 'editor-first27', 'editor-given27', 'editor-last27', 'editor-link27', 'editor-mask27', 'editor-surname27',
'editor28', 'editor28-first', 'editor28-given', 'editor28-last', 'editor28-link', 'editor28-mask', 'editor28-surname', 'editor-first28', 'editor-given28', 'editor-last28', 'editor-link28', 'editor-mask28', 'editor-surname28',
'editor29', 'editor29-first', 'editor29-given', 'editor29-last', 'editor29-link', 'editor29-mask', 'editor29-surname', 'editor-first29', 'editor-given29', 'editor-last29', 'editor-link29', 'editor-mask29', 'editor-surname29',
'editor30', 'editor30-first', 'editor30-given', 'editor30-last', 'editor30-link', 'editor30-mask', 'editor30-surname', 'editor-first30', 'editor-given30', 'editor-last30', 'editor-link30', 'editor-mask30', 'editor-surname30',
'editor31', 'editor31-first', 'editor31-given', 'editor31-last', 'editor31-link', 'editor31-mask', 'editor31-surname', 'editor-first31', 'editor-given31', 'editor-last31', 'editor-link31', 'editor-mask31', 'editor-surname31',
'editor32', 'editor32-first', 'editor32-given', 'editor32-last', 'editor32-link', 'editor32-mask', 'editor32-surname', 'editor-first32', 'editor-given32', 'editor-last32', 'editor-link32', 'editor-mask32', 'editor-surname32',
'editor33', 'editor33-first', 'editor33-given', 'editor33-last', 'editor33-link', 'editor33-mask', 'editor33-surname', 'editor-first33', 'editor-given33', 'editor-last33', 'editor-link33', 'editor-mask33', 'editor-surname33',
'editor34', 'editor34-first', 'editor34-given', 'editor34-last', 'editor34-link', 'editor34-mask', 'editor34-surname', 'editor-first34', 'editor-given34', 'editor-last34', 'editor-link34', 'editor-mask34', 'editor-surname34',
'editor35', 'editor35-first', 'editor35-given', 'editor35-last', 'editor35-link', 'editor35-mask', 'editor35-surname', 'editor-first35', 'editor-given35', 'editor-last35', 'editor-link35', 'editor-mask35', 'editor-surname35',
'editor36', 'editor36-first', 'editor36-given', 'editor36-last', 'editor36-link', 'editor36-mask', 'editor36-surname', 'editor-first36', 'editor-given36', 'editor-last36', 'editor-link36', 'editor-mask36', 'editor-surname36',
'editor37', 'editor37-first', 'editor37-given', 'editor37-last', 'editor37-link', 'editor37-mask', 'editor37-surname', 'editor-first37', 'editor-given37', 'editor-last37', 'editor-link37', 'editor-mask37', 'editor-surname37',
'editor38', 'editor38-first', 'editor38-given', 'editor38-last', 'editor38-link', 'editor38-mask', 'editor38-surname', 'editor-first38', 'editor-given38', 'editor-last38', 'editor-link38', 'editor-mask38', 'editor-surname38',
'editor39', 'editor39-first', 'editor39-given', 'editor39-last', 'editor39-link', 'editor39-mask', 'editor39-surname', 'editor-first39', 'editor-given39', 'editor-last39', 'editor-link39', 'editor-mask39', 'editor-surname39',
'editor40', 'editor40-first', 'editor40-given', 'editor40-last', 'editor40-link', 'editor40-mask', 'editor40-surname', 'editor-first40', 'editor-given40', 'editor-last40', 'editor-link40', 'editor-mask40', 'editor-surname40',
'editor41', 'editor41-first', 'editor41-given', 'editor41-last', 'editor41-link', 'editor41-mask', 'editor41-surname', 'editor-first41', 'editor-given41', 'editor-last41', 'editor-link41', 'editor-mask41', 'editor-surname41',
'editor42', 'editor42-first', 'editor42-given', 'editor42-last', 'editor42-link', 'editor42-mask', 'editor42-surname', 'editor-first42', 'editor-given42', 'editor-last42', 'editor-link42', 'editor-mask42', 'editor-surname42',
'editor43', 'editor43-first', 'editor43-given', 'editor43-last', 'editor43-link', 'editor43-mask', 'editor43-surname', 'editor-first43', 'editor-given43', 'editor-last43', 'editor-link43', 'editor-mask43', 'editor-surname43',
'editor44', 'editor44-first', 'editor44-given', 'editor44-last', 'editor44-link', 'editor44-mask', 'editor44-surname', 'editor-first44', 'editor-given44', 'editor-last44', 'editor-link44', 'editor-mask44', 'editor-surname44',
'editor45', 'editor45-first', 'editor45-given', 'editor45-last', 'editor45-link', 'editor45-mask', 'editor45-surname', 'editor-first45', 'editor-given45', 'editor-last45', 'editor-link45', 'editor-mask45', 'editor-surname45',
'editor46', 'editor46-first', 'editor46-given', 'editor46-last', 'editor46-link', 'editor46-mask', 'editor46-surname', 'editor-first46', 'editor-given46', 'editor-last46', 'editor-link46', 'editor-mask46', 'editor-surname46',
'editor47', 'editor47-first', 'editor47-given', 'editor47-last', 'editor47-link', 'editor47-mask', 'editor47-surname', 'editor-first47', 'editor-given47', 'editor-last47', 'editor-link47', 'editor-mask47', 'editor-surname47',
'editor48', 'editor48-first', 'editor48-given', 'editor48-last', 'editor48-link', 'editor48-mask', 'editor48-surname', 'editor-first48', 'editor-given48', 'editor-last48', 'editor-link48', 'editor-mask48', 'editor-surname48',
'editor49', 'editor49-first', 'editor49-given', 'editor49-last', 'editor49-link', 'editor49-mask', 'editor49-surname', 'editor-first49', 'editor-given49', 'editor-last49', 'editor-link49', 'editor-mask49', 'editor-surname49',
'editor50', 'editor50-first', 'editor50-given', 'editor50-last', 'editor50-link', 'editor50-mask', 'editor50-surname', 'editor-first50', 'editor-given50', 'editor-last50', 'editor-link50', 'editor-mask50', 'editor-surname50',
'editor51', 'editor51-first', 'editor51-given', 'editor51-last', 'editor51-link', 'editor51-mask', 'editor51-surname', 'editor-first51', 'editor-given51', 'editor-last51', 'editor-link51', 'editor-mask51', 'editor-surname51',
'editor52', 'editor52-first', 'editor52-given', 'editor52-last', 'editor52-link', 'editor52-mask', 'editor52-surname', 'editor-first52', 'editor-given52', 'editor-last52', 'editor-link52', 'editor-mask52', 'editor-surname52',
'editor53', 'editor53-first', 'editor53-given', 'editor53-last', 'editor53-link', 'editor53-mask', 'editor53-surname', 'editor-first53', 'editor-given53', 'editor-last53', 'editor-link53', 'editor-mask53', 'editor-surname53',
'editor54', 'editor54-first', 'editor54-given', 'editor54-last', 'editor54-link', 'editor54-mask', 'editor54-surname', 'editor-first54', 'editor-given54', 'editor-last54', 'editor-link54', 'editor-mask54', 'editor-surname54',
'editor55', 'editor55-first', 'editor55-given', 'editor55-last', 'editor55-link', 'editor55-mask', 'editor55-surname', 'editor-first55', 'editor-given55', 'editor-last55', 'editor-link55', 'editor-mask55', 'editor-surname55',
'editor56', 'editor56-first', 'editor56-given', 'editor56-last', 'editor56-link', 'editor56-mask', 'editor56-surname', 'editor-first56', 'editor-given56', 'editor-last56', 'editor-link56', 'editor-mask56', 'editor-surname56',
'editor57', 'editor57-first', 'editor57-given', 'editor57-last', 'editor57-link', 'editor57-mask', 'editor57-surname', 'editor-first57', 'editor-given57', 'editor-last57', 'editor-link57', 'editor-mask57', 'editor-surname57',
'editor58', 'editor58-first', 'editor58-given', 'editor58-last', 'editor58-link', 'editor58-mask', 'editor58-surname', 'editor-first58', 'editor-given58', 'editor-last58', 'editor-link58', 'editor-mask58', 'editor-surname58',
'editor59', 'editor59-first', 'editor59-given', 'editor59-last', 'editor59-link', 'editor59-mask', 'editor59-surname', 'editor-first59', 'editor-given59', 'editor-last59', 'editor-link59', 'editor-mask59', 'editor-surname59',
'editor60', 'editor60-first', 'editor60-given', 'editor60-last', 'editor60-link', 'editor60-mask', 'editor60-surname', 'editor-first60', 'editor-given60', 'editor-last60', 'editor-link60', 'editor-mask60', 'editor-surname60',
'editor61', 'editor61-first', 'editor61-given', 'editor61-last', 'editor61-link', 'editor61-mask', 'editor61-surname', 'editor-first61', 'editor-given61', 'editor-last61', 'editor-link61', 'editor-mask61', 'editor-surname61',
'editor62', 'editor62-first', 'editor62-given', 'editor62-last', 'editor62-link', 'editor62-mask', 'editor62-surname', 'editor-first62', 'editor-given62', 'editor-last62', 'editor-link62', 'editor-mask62', 'editor-surname62',
'editor63', 'editor63-first', 'editor63-given', 'editor63-last', 'editor63-link', 'editor63-mask', 'editor63-surname', 'editor-first63', 'editor-given63', 'editor-last63', 'editor-link63', 'editor-mask63', 'editor-surname63',
'editor64', 'editor64-first', 'editor64-given', 'editor64-last', 'editor64-link', 'editor64-mask', 'editor64-surname', 'editor-first64', 'editor-given64', 'editor-last64', 'editor-link64', 'editor-mask64', 'editor-surname64',
'editor65', 'editor65-first', 'editor65-given', 'editor65-last', 'editor65-link', 'editor65-mask', 'editor65-surname', 'editor-first65', 'editor-given65', 'editor-last65', 'editor-link65', 'editor-mask65', 'editor-surname65',
'editor66', 'editor66-first', 'editor66-given', 'editor66-last', 'editor66-link', 'editor66-mask', 'editor66-surname', 'editor-first66', 'editor-given66', 'editor-last66', 'editor-link66', 'editor-mask66', 'editor-surname66',
'editor67', 'editor67-first', 'editor67-given', 'editor67-last', 'editor67-link', 'editor67-mask', 'editor67-surname', 'editor-first67', 'editor-given67', 'editor-last67', 'editor-link67', 'editor-mask67', 'editor-surname67',
'editor68', 'editor68-first', 'editor68-given', 'editor68-last', 'editor68-link', 'editor68-mask', 'editor68-surname', 'editor-first68', 'editor-given68', 'editor-last68', 'editor-link68', 'editor-mask68', 'editor-surname68',
'editor69', 'editor69-first', 'editor69-given', 'editor69-last', 'editor69-link', 'editor69-mask', 'editor69-surname', 'editor-first69', 'editor-given69', 'editor-last69', 'editor-link69', 'editor-mask69', 'editor-surname69',
'editor70', 'editor70-first', 'editor70-given', 'editor70-last', 'editor70-link', 'editor70-mask', 'editor70-surname', 'editor-first70', 'editor-given70', 'editor-last70', 'editor-link70', 'editor-mask70', 'editor-surname70',
'editor71', 'editor71-first', 'editor71-given', 'editor71-last', 'editor71-link', 'editor71-mask', 'editor71-surname', 'editor-first71', 'editor-given71', 'editor-last71', 'editor-link71', 'editor-mask71', 'editor-surname71',
'editor72', 'editor72-first', 'editor72-given', 'editor72-last', 'editor72-link', 'editor72-mask', 'editor72-surname', 'editor-first72', 'editor-given72', 'editor-last72', 'editor-link72', 'editor-mask72', 'editor-surname72',
'editor73', 'editor73-first', 'editor73-given', 'editor73-last', 'editor73-link', 'editor73-mask', 'editor73-surname', 'editor-first73', 'editor-given73', 'editor-last73', 'editor-link73', 'editor-mask73', 'editor-surname73',
'editor74', 'editor74-first', 'editor74-given', 'editor74-last', 'editor74-link', 'editor74-mask', 'editor74-surname', 'editor-first74', 'editor-given74', 'editor-last74', 'editor-link74', 'editor-mask74', 'editor-surname74',
'editor75', 'editor75-first', 'editor75-given', 'editor75-last', 'editor75-link', 'editor75-mask', 'editor75-surname', 'editor-first75', 'editor-given75', 'editor-last75', 'editor-link75', 'editor-mask75', 'editor-surname75',
'editor76', 'editor76-first', 'editor76-given', 'editor76-last', 'editor76-link', 'editor76-mask', 'editor76-surname', 'editor-first76', 'editor-given76', 'editor-last76', 'editor-link76', 'editor-mask76', 'editor-surname76',
'editor77', 'editor77-first', 'editor77-given', 'editor77-last', 'editor77-link', 'editor77-mask', 'editor77-surname', 'editor-first77', 'editor-given77', 'editor-last77', 'editor-link77', 'editor-mask77', 'editor-surname77',
'editor78', 'editor78-first', 'editor78-given', 'editor78-last', 'editor78-link', 'editor78-mask', 'editor78-surname', 'editor-first78', 'editor-given78', 'editor-last78', 'editor-link78', 'editor-mask78', 'editor-surname78',
'editor79', 'editor79-first', 'editor79-given', 'editor79-last', 'editor79-link', 'editor79-mask', 'editor79-surname', 'editor-first79', 'editor-given79', 'editor-last79', 'editor-link79', 'editor-mask79', 'editor-surname79',
'editor80', 'editor80-first', 'editor80-given', 'editor80-last', 'editor80-link', 'editor80-mask', 'editor80-surname', 'editor-first80', 'editor-given80', 'editor-last80', 'editor-link80', 'editor-mask80', 'editor-surname80',
'editor81', 'editor81-first', 'editor81-given', 'editor81-last', 'editor81-link', 'editor81-mask', 'editor81-surname', 'editor-first81', 'editor-given81', 'editor-last81', 'editor-link81', 'editor-mask81', 'editor-surname81',
'editor82', 'editor82-first', 'editor82-given', 'editor82-last', 'editor82-link', 'editor82-mask', 'editor82-surname', 'editor-first82', 'editor-given82', 'editor-last82', 'editor-link82', 'editor-mask82', 'editor-surname82',
'editor83', 'editor83-first', 'editor83-given', 'editor83-last', 'editor83-link', 'editor83-mask', 'editor83-surname', 'editor-first83', 'editor-given83', 'editor-last83', 'editor-link83', 'editor-mask83', 'editor-surname83',
'editor84', 'editor84-first', 'editor84-given', 'editor84-last', 'editor84-link', 'editor84-mask', 'editor84-surname', 'editor-first84', 'editor-given84', 'editor-last84', 'editor-link84', 'editor-mask84', 'editor-surname84',
'editor85', 'editor85-first', 'editor85-given', 'editor85-last', 'editor85-link', 'editor85-mask', 'editor85-surname', 'editor-first85', 'editor-given85', 'editor-last85', 'editor-link85', 'editor-mask85', 'editor-surname85',
'editor86', 'editor86-first', 'editor86-given', 'editor86-last', 'editor86-link', 'editor86-mask', 'editor86-surname', 'editor-first86', 'editor-given86', 'editor-last86', 'editor-link86', 'editor-mask86', 'editor-surname86',
'editor87', 'editor87-first', 'editor87-given', 'editor87-last', 'editor87-link', 'editor87-mask', 'editor87-surname', 'editor-first87', 'editor-given87', 'editor-last87', 'editor-link87', 'editor-mask87', 'editor-surname87',
'editor88', 'editor88-first', 'editor88-given', 'editor88-last', 'editor88-link', 'editor88-mask', 'editor88-surname', 'editor-first88', 'editor-given88', 'editor-last88', 'editor-link88', 'editor-mask88', 'editor-surname88',
'editor89', 'editor89-first', 'editor89-given', 'editor89-last', 'editor89-link', 'editor89-mask', 'editor89-surname', 'editor-first89', 'editor-given89', 'editor-last89', 'editor-link89', 'editor-mask89', 'editor-surname89',
'editor90', 'editor90-first', 'editor90-given', 'editor90-last', 'editor90-link', 'editor90-mask', 'editor90-surname', 'editor-first90', 'editor-given90', 'editor-last90', 'editor-link90', 'editor-mask90', 'editor-surname90',
'editor91', 'editor91-first', 'editor91-given', 'editor91-last', 'editor91-link', 'editor91-mask', 'editor91-surname', 'editor-first91', 'editor-given91', 'editor-last91', 'editor-link91', 'editor-mask91', 'editor-surname91',
'editor92', 'editor92-first', 'editor92-given', 'editor92-last', 'editor92-link', 'editor92-mask', 'editor92-surname', 'editor-first92', 'editor-given92', 'editor-last92', 'editor-link92', 'editor-mask92', 'editor-surname92',
'editor93', 'editor93-first', 'editor93-given', 'editor93-last', 'editor93-link', 'editor93-mask', 'editor93-surname', 'editor-first93', 'editor-given93', 'editor-last93', 'editor-link93', 'editor-mask93', 'editor-surname93',
'editor94', 'editor94-first', 'editor94-given', 'editor94-last', 'editor94-link', 'editor94-mask', 'editor94-surname', 'editor-first94', 'editor-given94', 'editor-last94', 'editor-link94', 'editor-mask94', 'editor-surname94',
'editor95', 'editor95-first', 'editor95-given', 'editor95-last', 'editor95-link', 'editor95-mask', 'editor95-surname', 'editor-first95', 'editor-given95', 'editor-last95', 'editor-link95', 'editor-mask95', 'editor-surname95',
'editor96', 'editor96-first', 'editor96-given', 'editor96-last', 'editor96-link', 'editor96-mask', 'editor96-surname', 'editor-first96', 'editor-given96', 'editor-last96', 'editor-link96', 'editor-mask96', 'editor-surname96',
'editor97', 'editor97-first', 'editor97-given', 'editor97-last', 'editor97-link', 'editor97-mask', 'editor97-surname', 'editor-first97', 'editor-given97', 'editor-last97', 'editor-link97', 'editor-mask97', 'editor-surname97',
'editor98', 'editor98-first', 'editor98-given', 'editor98-last', 'editor98-link', 'editor98-mask', 'editor98-surname', 'editor-first98', 'editor-given98', 'editor-last98', 'editor-link98', 'editor-mask98', 'editor-surname98',
'editor99', 'editor99-first', 'editor99-given', 'editor99-last', 'editor99-link', 'editor99-mask', 'editor99-surname', 'editor-first99', 'editor-given99', 'editor-last99', 'editor-link99', 'editor-mask99', 'editor-surname99'
);

const TITLE_LINK_ALIASES = ['title-link', 'titlelink'];
const ARXIV_ALIASES = ['arxiv', 'eprint'];
const COAUTHOR_ALIASES = ['coauthor', 'coauthors'];
const CHAPTER_ALIASES = ['chapter', 'contribution', 'article', 'entry', 'section'];
const DISPLAY_AUTHORS = ['display-authors', 'displayauthors'];
const DISPLAY_EDITORS = ['display-editors', 'displayeditors'];
const DOI_BROKEN_ALIASES = ['doi-broken', 'doi_brokendate', 'doi-broken-date', 'doi_inactivedate', 'doi-inactive-date'];
const FIRST_AUTHOR_ALIASES = ['last1', 'last', 'author', 'author1', 'vauthor', 'surname1', 'surname', 'author1-surname', 'author1-surname', 'author-surname'];
const FIRST_FORENAME_ALIASES = ['first1', 'first', 'author', 'author1', 'given', 'given1', 'author-given', 'author-given1', 'author1-given'];
const FIRST_EDITOR_ALIASES = ['editor1', 'editor', 'editor-last', 'editor1-last', 'editor-last1', 'veditor', 'editor1-surname', 'editor1-given', 'editor-surname', 'editor-given', 'editor-surname1', 'editor-given1'];
const ISSUE_ALIASES = ['issue', 'number'];
const PAGE_ALIASES = ['page', 'pages', 'pp', 'p', 'at'];
const TIME_ALIASES = ['date', 'year'];
const WORK_ALIASES = ['work', 'journal', 'newspaper', 'magazine', 'periodical', 'website', 'encyclopedia', 'encyclopaedia'];
const ACCESS_ALIASES = ['accessdate', 'access-date'];
const ISBN_ALIASES = ['ISBN', 'isbn13', 'ISBN13', 'isbn'];
const LANG_ALIASES = ['language', 'lang'];
const TYPE_ALIASES = ['medium', 'type'];

const ALL_ALIASES = [TITLE_LINK_ALIASES, ARXIV_ALIASES, COAUTHOR_ALIASES, CHAPTER_ALIASES,
              DISPLAY_AUTHORS, DISPLAY_EDITORS, DOI_BROKEN_ALIASES, FIRST_AUTHOR_ALIASES,
              FIRST_FORENAME_ALIASES, FIRST_EDITOR_ALIASES, ISSUE_ALIASES, PAGE_ALIASES,
              TIME_ALIASES, WORK_ALIASES, FLATTENED_AUTHOR_PARAMETERS, ACCESS_ALIASES,
              ISBN_ALIASES, LANG_ALIASES, TYPE_ALIASES, LOTS_OF_EDITORS];

// Includes many parameters usually from templates that we do not modify such as {{cite patent}}, because
// that information can also be presented using the generic {{citation}} template, which we do modify.
// This list even includes items that are no longer supported, since we need to leave fixing them to humans
// See https://en.wikipedia.org/wiki/Module:Citation/CS1/Whitelist
const PARAMETER_LIST = array(
  'ASIN', 'CITATION_BOT_PLACEHOLDER_BARE_URL', 'DOI', 'EISSN', 'HDL', 'ID', 'ISBN',
  'ISMN', 'ISSN', 'JFM', 'JSTOR', 'LCCN', 'MR', 'OCLC', 'OL', 'OSTI', 'PMC', 'PMID', 'RFC',
  'S2CID', 'SBN', 'SSRN', 'URL', 'ZBL', 'access-date', 'accessdate', 'agency', 'air-date',
  'airdate', 'archive-date', 'archive-format', 'archive-url', 'archivedate', 'archiveurl',
  'article', 'article-format', 'article-url', 'article-url-access', 'arxiv', 'asin',
  'asin-tld', 'assign', 'assign#', 'assignee', 'at', 'audio-visual', 'author', 'author#',
  'author#-first', 'author#-given', 'author#-last', 'author#-link', 'author#-mask',
  'author#-surname', 'author#link', 'author-first', 'author-first#',
  'author-given', 'author-given#', 'author-last', 'author-last#', 'author-link',
  'author-link#', 'author-mask', 'author-mask#', 'author-surname', 'author-surname#',
  'authorlink', 'authorlink#', 'authors', 'bibcode',
  'bibcode-access', 'biorxiv', 'book-title', 'cartography', 'chapter',
  'chapter-format', 'chapter-url', 'chapter-url-access',
  'citation_bot_placeholder_bare_url', 'citeseerx', 'class', 'collaboration',
  'conference', 'conference-format', 'conference-url',
  'contribution', 'contribution-format', 'contribution-url', 'contribution-url-access',
  'contributor', 'contributor#', 'contributor#-first',
  'contributor#-given', 'contributor#-last', 'contributor#-link', 'contributor#-mask',
  'contributor#-surname', 'contributor-first', 'contributor-first#', 'contributor-given',
  'contributor-given#', 'contributor-last', 'contributor-last#', 'contributor-link',
  'contributor-link#', 'contributor-mask', 'contributor-mask#', 'contributor-surname',
  'contributor-surname#', 'country', 'country-code', 'credits', 'date', 'degree',
  'department', 'description', 'df', 'dictionary', 'display-authors',
  'display-contributors', 'display-editors', 'display-interviewers',
  'display-subjects', 'display-translators', 'docket', 'doi',
  'doi-access', 'doi-broken-date', 'edition', 'editor', 'editor#', 'editor#-first',
  'editor#-given', 'editor#-last', 'editor#-link', 'editor#-mask', 'editor#-surname',
  'editor-first', 'editor-first#', 'editor-given', 'editor-given#',
  'editor-last', 'editor-last#', 'editor-link', 'editor-link#', 'editor-mask',
  'editor-mask#', 'editor-surname', 'editor-surname#',
  'eissn', 'encyclopaedia', 'encyclopedia', 'entry', 'entry-format',
  'entry-url', 'entry-url-access', 'episode', 'episode-link', 'eprint',
  'event', 'fdate', 'first', 'first#',
  'format', 'gdate', 'given', 'given#', 'hdl', 'hdl-access', 'host', 'host#', 'id',
  'inset', 'institution', 'interviewer', 'interviewer#',
  'interviewer#-first', 'interviewer#-given', 'interviewer#-last', 'interviewer#-link',
  'interviewer#-mask', 'interviewer#-surname', 'interviewer-first', 'interviewer-first#',
  'interviewer-given', 'interviewer-given#', 'interviewer-last', 'interviewer-last#',
  'interviewer-link', 'interviewer-link#', 'interviewer-mask', 'interviewer-mask#',
  'interviewer-surname', 'interviewer-surname#', 'invent#', 'inventor', 'inventor#',
  'inventor#-first', 'inventor#-given', 'inventor#-last', 'inventor#-link',
  'inventor#-surname', 'inventor#link', 'inventor-first', 'inventor-first#',
  'inventor-given', 'inventor-given#', 'inventor-last', 'inventor-last#',
  'inventor-link', 'inventor-link#', 'inventor-surname', 'inventor-surname#',
  'inventorlink', 'inventorlink#', 'isbn', 'ismn', 'issn', 'issue',
  'issue-date', 'jfm', 'journal', 'jstor', 'jstor-access', 'lang', 'language',
  'last', 'last#', 'lay-date', 'lay-format',
  'lay-source', 'lay-url', 'lccn', 'location',
  'magazine', 'mailing-list', 'map', 'map-format', 'map-url',
  'map-url-access', 'medium', 'message-id', 'minutes', 'mode', 'mr',
  'name-list-style', 'network', 'newsgroup', 'newspaper',
  'no-pp', 'no-tracking', 'number', 'oclc', 'ol', 'ol-access',
  'orig-date', 'orig-year', 'origyear', 'osti', 'osti-access', 'others', 'p',
  'page', 'pages', 'patent-number', 'people', 'periodical', 'place', 'pmc',
  'pmc-embargo-date', 'pmid', 'postscript', 'pp', 'pridate', 'pubdate',
  'publication-date', 'publication-number', 'publication-place',
  'publisher', 'quotation', 'quote', 'quote-page', 'quote-pages',
  'ref', 'rfc', 's2cid', 's2cid-access', 'sbn', 'scale', 'script-article',
  'script-chapter', 'script-contribution', 'script-entry', 'script-journal',
  'script-magazine', 'script-map', 'script-newspaper', 'script-periodical',
  'script-quote', 'script-section', 'script-title', 'script-website',
  'script-work', 'season', 'section', 'section-format', 'section-url',
  'section-url-access', 'sections', 'series', 'series-link',
  'series-no', 'series-number',
  'sheet', 'sheets', 'ssrn', 'ssrn-access', 'station', 'status', 'subject', 'subject#',
  'subject#-link', 'subject#-mask', 'subject-link', 'subject-link#', 'subject-mask', 'subject-mask#',
  'surname', 'surname#', 'template-doc-demo', 'time',
  'time-caption', 'title', 'title-link',
  'trans-article', 'trans-chapter', 'trans-contribution', 'trans-entry',
  'trans-journal', 'trans-magazine', 'trans-map', 'trans-newspaper',
  'trans-periodical', 'trans-quote', 'trans-section', 'trans-title',
  'trans-website', 'trans-work', 'transcript', 'transcript-format',
  'transcript-url', 'transcripturl', 'translator', 'translator#',
  'translator#-first', 'translator#-given', 'translator#-last', 'translator#-link',
  'translator#-mask', 'translator#-surname', 'translator-first',
  'translator-first#', 'translator-given', 'translator-given#', 'translator-last',
  'translator-last#', 'translator-link', 'translator-link#', 'translator-mask',
  'translator-mask#', 'translator-surname', 'translator-surname#', 'type',
  'url', 'url-access', 'url-status', 'vauthors', 'veditors', 'version',
  'via', 'volume', 'website', 'work', 'year', 'zbl'
);

 const DEAD_PARAMETERS = array('PPPrefix', 'PPrefix', 'Ref', 'albumlink', 'albumtype',
     'author-format', 'author-name-separator', 'author-separator', 'authors#', 'began', 'call-sign',
     'chapter-link', 'city', 'coauthor', 'day', 'dead-url', 'deadurl',
     'editor-format', 'editor-name-separator', 'editor-separator', 'editorformat',
     'editors#', 'ended', 'in', 'interviewers', 'lay-summary', 'month', 'name-separator',
     'p-prefix', 'pp-prefix', 'program', 'registration', 'separator',
     'subscription', 'author_separator', 'coauthors', 'urldate',
     'isbn2', 'isbn3', 'isbn4', 'isbn5', 'isbn6', 'isbn7', 'deadlink', 'displayeditors',
     'doi-broken', 'doi-inactive-date', 'editormask', 'editor#mask', 'editormask#',
     'embargo', 'ignoreisbnerror', 'interviewerlink', 'interviewermask', 'no-cat',
     'notracking', 'series-separator', 'authormask', 'displayauthors',
     ' editor#link', 'editorlink', 'editorlink#', 'editors', 'event-format', 'event-url',
     'eventurl', 'ignore-isbn-error', 'last-author-amp', 'lastauthoramp', 'nocat',
     'seriesnumber', 'subjectlink', 'subjectlink#', 'conferenceurl', 'contributionurl',
     'laydate', 'laysource', 'layurl', 'name-list-format', 'sectionurl', 'seriesno',
     'timecaption', 'titlelink', 'ref name', 'ISBN13', 'booktitle', 'chapterurl', 'episodelink',
     'isbn13', 'mailinglist', 'mapurl', 'nopp', 'publicationdate', 'publicationplace',
     'serieslink', 'sid');  // sid is actually page range in some no english wiki's but do not fix since so close to id=

