# configuration related to pull request comments
comment: no # do not comment PR with the result

coverage:
    range: 50..90 # coverage lower than 50 is red, higher than 90 green, between color code

    status:
        project: # settings affecting project coverage
            enabled: yes
            target: auto # auto % coverage target
            threshold: 50%  # allow for 50% reduction of coverage without failing - basically disabled
        # do not run coverage on patch nor changes
        patch: no
        changes: no
