name: Actionlint

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '25 17 * * 1'

permissions:
  contents: read

jobs:
  actionlint:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v7.0.1

    - name: Run actionlint
      uses: raven-actions/actionlint@v2.2.0
