name: Actionlint

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '25 17 * * 1'

permissions:
  contents: read

jobs:
  actionlint:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v7.0.0

    - name: Download actionlint v1.7.12
      run: |
        curl -sSLO https://github.com/rhysd/actionlint/releases/download/v1.7.12/actionlint_1.7.12_linux_amd64.tar.gz
        tar xzf actionlint_1.7.12_linux_amd64.tar.gz

    - name: Run actionlint
      run: ./actionlint -color
