name: HTML5 and CSS Validator

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]
    schedule:
        - cron: '45 17 * * 1'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v7.0.1

    - name: Convert index.php to HTML
      uses: jacobtomlinson/gha-find-replace@v3
      with:
        find: '<\?php[\s\S]*?\?>'
        replace: ''
        regex: true
        include: 'index.php'

    - name: Run validator
      uses: Cyb3r-Jak3/html5validator-action@v8.0.0
      with:
        root: src/
        css: true
        log_level: INFO
        extra: --match *.html *.htm *.css index.php
