name: Link checker

on:
  schedule:
    - cron: '25 17 * * 1'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  lychee:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v6.0.3

    - name: Check links
      uses: lycheeverse/lychee-action@v2.8.0
      with:
        args: '--no-progress --include-mail "**/*.md" "**/*.html"'
