name: Link checker

on:
  schedule:
    - cron: '25 17 * * 1'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  lychee:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v7.0.1

    - name: Check links
      uses: lycheeverse/lychee-action@v2.9.0
      with:
        args: '--no-progress --include-mail "**/*.md" "**/*.html" "catalog-info.yaml" "CITATION.cff" --timeout 60 --host-concurrency 2 --host-request-interval 1s --max-concurrency 16 --verbose'
