name: PHP Static Coding Tests Part 3

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '25 17 * * 1'

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Setup PHP with PCOV
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        ini-values: pcov.directory=.
        coverage: pcov
        extensions: mbstring, intl

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Configure composer and dependencies
      run: composer config allow-plugins.third-party/required-plugin true && composer config minimum-stability dev && composer config prefer-stable true && composer config --no-plugins allow-plugins.bamarni/composer-bin-plugin true && composer require mediawiki/oauthclient:2.0.0 && composer require --dev qossmic/deptrac && composer require --dev bamarni/composer-bin-plugin

    - name: Install dependencies
      if: steps.composer-cache.outputs.cache-hit != 'true'
      run: composer install --prefer-dist  -vvv --no-progress

    - name: PHP phpinsights
      run: php -d memory_limit=2000M ./vendor/bin/phpinsights

    - name: PHP deptrac
      run: vendor/bin/deptrac init && vendor/bin/deptrac
