name: PHP Composer

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-
            
    - name: confiugre composer and dependecies
      run: composer config minimum-stability dev && composer config prefer-stable true && composer require overtrue/phplint  phpstan/phpstan   mediawiki/oauthclient:1.1.0  phan/phan:3.x vimeo/psalm designsecurity/progpilot
      
    - name: Install dependencies
      if: steps.composer-cache.outputs.cache-hit != 'true'
      run: composer install --prefer-dist  -vvv --no-progress

    - name: PHP Lint test
      run: ./vendor/bin/phplint --exclude=vendor --no-interaction -vv ./

    - name: PHP phpstan
      run: php ./vendor/bin/phpstan --no-interaction analyse --memory-limit=2G constants/*.php  Parameter.php user_messages.php constants.php expandFns.php Zotero.php apiFunctions.php NameTools.php Comment.php Page.php WikipediaBot.php Template.php setup.php category.php generate_template.php linked_pages.php unlock_git.php process_page.php authenticate.php

    - name: PHP phan
      run: php ./vendor/bin/phan --allow-polyfill-parser constants/*.php constants.php    user_messages.php  Parameter.php expandFns.php  NameTools.php  Zotero.php apiFunctions.php Comment.php  Template.php WikipediaBot.php setup.php Page.php category.php generate_template.php gitpull.php linked_pages.php process_page.php  authenticate.php unlock_git.php

    - name: PHP psalm
      run: php ./vendor/bin/psalm
      
    - name: PHP psalm Taint
      run: php ./vendor/bin/psalm --taint-analysis
      
    - name: PHP Design Security
      run: ./vendor/bin/progpilot  category.php generate_template.php gitpull.php linked_pages.php process_page.php authenticate.php unlock_git.php
      
    - name: Full test with PHP 7.3
      uses: php-actions/phpunit@v9
      
    - name: Code Coverage
      run: /bin/bash <(curl -s https://codecov.io/bash)
      
