name: PHP Security Checker

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '55 17 * * 1'

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-24.04

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v7.0.1

    - name: Setup PHP
      uses: shivammathur/setup-php@2.37.2
      with:
        php-version: '8.5'
        coverage: none

    - name: Validate composer.json and composer.lock
      run: composer update --no-install && composer validate

    - name: PHP Security Checker
      uses: StephaneBour/actions-php-security-checker@1.2
