name: PHP Security Checker

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '55 17 * * 1'

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-24.04

    steps:
    - name: Checkout Repo
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

    - name: Setup PHP
      uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # 2.37.2
      with:
        php-version: '8.4'
        coverage: none

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: PHP Security Checker
      uses: StephaneBour/actions-php-security-checker@625e87650b4709fa61746bfa890d1b55ae6d7067 # 1.2
