name: PHP psalm security check

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '25 17 * * 1'

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-24.04

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v7.0.1

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.4'
        coverage: none

    - name: Cache Composer dependencies
      id: composer-cache
      uses: actions/cache@v6
      with:
        path: vendor
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-composer-
    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Install dependencies
      run: composer install -vvv --no-progress

    - name: PHP psalm Taint
      run: composer run psalm-taint
